Source = \
	LoggerTest.cpp \

IncludeDirs = \
	/usr/include \
	${COMPILER_VERSION} \
	${ACE_ROOT} \

LibraryDirs = \
        /usr/lib \
	${ACE_ROOT}/ace \

Libraries = \
	platformutilities \
	platformlogger \
	ACE \

Main      = LoggerTest2

include $(DEV_ROOT)/make/Makefile
