// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from 
// be/be_codegen.cpp:887

#ifndef CPPSESSION_SESSIONI_H_
#define CPPSESSION_SESSIONI_H_

#include "ems/idls/cppsource/sessionS.h"

class  session_Session_I_i : public virtual POA_session::Session_I, public virtual PortableServer::RefCountServantBase
{
public:
  //Constructor 
  session_Session_I_i (void);
  
  //Destructor 
  virtual ~session_Session_I_i (void);
  
  virtual ::session::Session_I_ptr associatedSession ( ) ACE_THROW_SPEC (( CORBA::SystemException));
  
  virtual void ping ( ) ACE_THROW_SPEC (( CORBA::SystemException));
 
  virtual void endSession ( ) ACE_THROW_SPEC (( CORBA::SystemException));

  /** Set the Associated Session reference */
  void setAssociatedSession( session::Session_I_ptr associatedSession);

private:
  session::Session_I_ptr associatedSession_;
};


#endif /* CPPSESSION_SESSIONI_H_  */
