Source = \
	DataManagerTest.cpp \

IncludeDirs = \
	/usr/include \
	${COMPILER_VERSION} \
	${ACE_ROOT} \

LibraryDirs = \
        /usr/lib \
	${ACE_ROOT}/ace \
	${DB_ROOT}/lib \

Libraries = \
	platformutilities \
	platformopm \
	platformlogger \
	platformdatamgr \
	ACE \
	pq \
	pgtypes \

Main      = DataManagerTest

include $(DEV_ROOT)/make/Makefile
