Source = \
	Callback.cpp \
        DiscoveryLocalMessage.cpp \
        DiscoveryManager.cpp \
        DiscoveryMessage.cpp \
	DistributedMailbox.cpp \
	DistributedMailboxProxy.cpp \
	GroupMailbox.cpp \
	GroupMailboxProxy.cpp \
	LocalMailbox.cpp \
	LocalSMBuffer.cpp \
	LocalSMMailbox.cpp \
	LocalSMMailboxQueue.cpp \
	LocalSMMailboxProxy.cpp \
	MailboxAddress.cpp \
	MailboxBase.cpp \
	MailboxHandle.cpp \
	MailboxLookupService.cpp \
	MailboxOwnerHandle.cpp \
	MailboxProcessor.cpp \
	MessageBase.cpp \
	MessageBlockWrapper.cpp \
	MessageBuffer.cpp \
	MessageFactory.cpp \
	MessageHandlerList.cpp \
	ReusableMessageBase.cpp \
	TimerMessage.cpp \

IncludeDirs = \
        /usr/include \
        ${COMPILER_VERSION} \
        ${ACE_ROOT} \

LibraryDirs = \
        /usr/lib \
        ${ACE_ROOT}/ace \

Libraries = \
        ACE \
	platformutilities \
	platformlogger \
	platformthreadmgr \
	platformopm \

Main    = 

include $(DEV_ROOT)/make/Makefile
