package ems.idls.alarms;

/**
* ems/idls/alarms/alarmInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from alarms.idl
* Tuesday, January 15, 2015 5:02:23 PM CST
*/


/**
    * Command/Method interface
    */
public final class alarmInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public ems.idls.alarms.alarmInterface value = null;

  public alarmInterfaceHolder ()
  {
  }

  public alarmInterfaceHolder (ems.idls.alarms.alarmInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ems.idls.alarms.alarmInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ems.idls.alarms.alarmInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ems.idls.alarms.alarmInterfaceHelper.type ();
  }

}
