package ems.idls.alarms;


/**
* ems/idls/alarms/alarmInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from alarms.idl
* Tuesday, January 15, 2015 5:02:23 PM CST
*/


/**
    * Command/Method interface
    */
abstract public class alarmInterfaceHelper
{
  private static String  _id = "IDL:alarms/alarmInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, ems.idls.alarms.alarmInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ems.idls.alarms.alarmInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ems.idls.alarms.alarmInterfaceHelper.id (), "alarmInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ems.idls.alarms.alarmInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_alarmInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ems.idls.alarms.alarmInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ems.idls.alarms.alarmInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ems.idls.alarms.alarmInterface)
      return (ems.idls.alarms.alarmInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ems.idls.alarms._alarmInterfaceStub stub = new ems.idls.alarms._alarmInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ems.idls.alarms.alarmInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ems.idls.alarms.alarmInterface)
      return (ems.idls.alarms.alarmInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ems.idls.alarms._alarmInterfaceStub stub = new ems.idls.alarms._alarmInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
