package ems.idls.alarms;

/**
* ems/idls/alarms/AlarmCategoryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from alarms.idl
* Tuesday, January 15, 2015 5:02:23 PM CST
*/


/**
    * Alarm Category Type
    */
public final class AlarmCategoryHolder implements org.omg.CORBA.portable.Streamable
{
  public ems.idls.alarms.AlarmCategory value = null;

  public AlarmCategoryHolder ()
  {
  }

  public AlarmCategoryHolder (ems.idls.alarms.AlarmCategory initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ems.idls.alarms.AlarmCategoryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ems.idls.alarms.AlarmCategoryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ems.idls.alarms.AlarmCategoryHelper.type ();
  }

}
