package ems.idls.alarms;

/**
* ems/idls/alarms/AlarmInformationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from alarms.idl
* Tuesday, January 15, 2015 5:02:23 PM CST
*/

public final class AlarmInformationHolder implements org.omg.CORBA.portable.Streamable
{
  public ems.idls.alarms.AlarmInformation value = null;

  public AlarmInformationHolder ()
  {
  }

  public AlarmInformationHolder (ems.idls.alarms.AlarmInformation initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ems.idls.alarms.AlarmInformationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ems.idls.alarms.AlarmInformationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ems.idls.alarms.AlarmInformationHelper.type ();
  }

}
