package ems.idls.alarms;


/**
* ems/idls/alarms/AlarmNotification.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from alarms.idl
* Tuesday, January 15, 2015 5:02:23 PM CST
*/

public final class AlarmNotification implements org.omg.CORBA.portable.IDLEntity
{
  public String neid = null;
  public int code = (int)0;
  public int mObject = (int)0;
  public long mObjectInstance = (long)0;
  public ems.idls.alarms.Severity sev = null;
  public String tStamp = null;
  public String ack = null;

  public AlarmNotification ()
  {
  } // ctor

  public AlarmNotification (String _neid, int _code, int _mObject, long _mObjectInstance, ems.idls.alarms.Severity _sev, String _tStamp, String _ack)
  {
    neid = _neid;
    code = _code;
    mObject = _mObject;
    mObjectInstance = _mObjectInstance;
    sev = _sev;
    tStamp = _tStamp;
    ack = _ack;
  } // ctor

} // class AlarmNotification
