package ems.idls.alarms;

/**
* ems/idls/alarms/AlarmNotificationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from alarms.idl
* Tuesday, January 15, 2015 5:02:23 PM CST
*/

public final class AlarmNotificationHolder implements org.omg.CORBA.portable.Streamable
{
  public ems.idls.alarms.AlarmNotification value = null;

  public AlarmNotificationHolder ()
  {
  }

  public AlarmNotificationHolder (ems.idls.alarms.AlarmNotification initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ems.idls.alarms.AlarmNotificationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ems.idls.alarms.AlarmNotificationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ems.idls.alarms.AlarmNotificationHelper.type ();
  }

}
