package ems.idls.alarms;


/**
* ems/idls/alarms/alarmInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from alarms.idl
* Tuesday, January 15, 2015 5:02:23 PM CST
*/


/**
    * Command/Method interface
    */
public interface alarmInterface extends alarmInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface alarmInterface
