package ems.idls.alarms;


/**
* ems/idls/alarms/AlarmCategory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from alarms.idl
* Tuesday, January 15, 2015 5:02:23 PM CST
*/


/**
    * Alarm Category Type
    */
public class AlarmCategory implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 5;
  private static ems.idls.alarms.AlarmCategory[] __array = new ems.idls.alarms.AlarmCategory [__size];

  public static final int _COMMUNICATIONS_ALARM = 0;
  public static final ems.idls.alarms.AlarmCategory COMMUNICATIONS_ALARM = new ems.idls.alarms.AlarmCategory(_COMMUNICATIONS_ALARM);
  public static final int _QUALITY_OF_SERVICE_ALARM = 1;
  public static final ems.idls.alarms.AlarmCategory QUALITY_OF_SERVICE_ALARM = new ems.idls.alarms.AlarmCategory(_QUALITY_OF_SERVICE_ALARM);
  public static final int _PROCESSING_ERROR_ALARM = 2;
  public static final ems.idls.alarms.AlarmCategory PROCESSING_ERROR_ALARM = new ems.idls.alarms.AlarmCategory(_PROCESSING_ERROR_ALARM);
  public static final int _EQUIPMENT_ALARM = 3;
  public static final ems.idls.alarms.AlarmCategory EQUIPMENT_ALARM = new ems.idls.alarms.AlarmCategory(_EQUIPMENT_ALARM);
  public static final int _ENVIRONMENTAL_ALARM = 4;
  public static final ems.idls.alarms.AlarmCategory ENVIRONMENTAL_ALARM = new ems.idls.alarms.AlarmCategory(_ENVIRONMENTAL_ALARM);

  public int value ()
  {
    return __value;
  }

  public static ems.idls.alarms.AlarmCategory from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected AlarmCategory (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class AlarmCategory
