package ems.idls.alarms;


/**
* ems/idls/alarms/AlarmInformationHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from alarms.idl
* Tuesday, January 15, 2015 5:02:23 PM CST
*/

abstract public class AlarmInformationHelper
{
  private static String  _id = "IDL:alarms/AlarmInformation/AlarmInformation:1.0";

  public static void insert (org.omg.CORBA.Any a, ems.idls.alarms.AlarmInformation that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ems.idls.alarms.AlarmInformation extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [9];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ems.idls.alarms.AlarmCodeHelper.id (), "AlarmCode", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "code",
            _tcOf_members0,
            null);
          _tcOf_members0 = ems.idls.alarms.AlarmCategoryHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "aCategory",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_longlong);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ems.idls.alarms.HighWaterMarkHelper.id (), "HighWaterMark", _tcOf_members0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "hWaterMark",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_longlong);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ems.idls.alarms.LowWaterMarkHelper.id (), "LowWaterMark", _tcOf_members0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "lWaterMark",
            _tcOf_members0,
            null);
          _tcOf_members0 = ems.idls.alarms.SeverityHelper.type ();
          _members0[4] = new org.omg.CORBA.StructMember (
            "sev",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ems.idls.alarms.IsAutoClearingHelper.id (), "IsAutoClearing", _tcOf_members0);
          _members0[5] = new org.omg.CORBA.StructMember (
            "autoClearing",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ems.idls.alarms.IsFilterEnabledHelper.id (), "IsFilterEnabled", _tcOf_members0);
          _members0[6] = new org.omg.CORBA.StructMember (
            "filterEnabled",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ems.idls.alarms.DescriptionHelper.id (), "Description", _tcOf_members0);
          _members0[7] = new org.omg.CORBA.StructMember (
            "desc",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ems.idls.alarms.ResolutionHelper.id (), "Resolution", _tcOf_members0);
          _members0[8] = new org.omg.CORBA.StructMember (
            "res",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ems.idls.alarms.AlarmInformationHelper.id (), "AlarmInformation", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ems.idls.alarms.AlarmInformation read (org.omg.CORBA.portable.InputStream istream)
  {
    ems.idls.alarms.AlarmInformation value = new ems.idls.alarms.AlarmInformation ();
    value.code = istream.read_long ();
    value.aCategory = ems.idls.alarms.AlarmCategoryHelper.read (istream);
    value.hWaterMark = istream.read_longlong ();
    value.lWaterMark = istream.read_longlong ();
    value.sev = ems.idls.alarms.SeverityHelper.read (istream);
    value.autoClearing = istream.read_boolean ();
    value.filterEnabled = istream.read_boolean ();
    value.desc = istream.read_string ();
    value.res = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ems.idls.alarms.AlarmInformation value)
  {
    ostream.write_long (value.code);
    ems.idls.alarms.AlarmCategoryHelper.write (ostream, value.aCategory);
    ostream.write_longlong (value.hWaterMark);
    ostream.write_longlong (value.lWaterMark);
    ems.idls.alarms.SeverityHelper.write (ostream, value.sev);
    ostream.write_boolean (value.autoClearing);
    ostream.write_boolean (value.filterEnabled);
    ostream.write_string (value.desc);
    ostream.write_string (value.res);
  }

}
