package ems.idls.alarms;


/**
* ems/idls/alarms/AlarmNotificationHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from alarms.idl
* Tuesday, January 15, 2015 5:02:23 PM CST
*/

abstract public class AlarmNotificationHelper
{
  private static String  _id = "IDL:alarms/AlarmNotification/AlarmNotification:1.0";

  public static void insert (org.omg.CORBA.Any a, ems.idls.alarms.AlarmNotification that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ems.idls.alarms.AlarmNotification extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [7];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ems.idls.alarms.NEIDTypeHelper.id (), "NEIDType", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "neid",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ems.idls.alarms.AlarmCodeHelper.id (), "AlarmCode", _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "code",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ems.idls.alarms.ManagedObjectHelper.id (), "ManagedObject", _tcOf_members0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "mObject",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_longlong);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ems.idls.alarms.ManagedObjectInstanceHelper.id (), "ManagedObjectInstance", _tcOf_members0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "mObjectInstance",
            _tcOf_members0,
            null);
          _tcOf_members0 = ems.idls.alarms.SeverityHelper.type ();
          _members0[4] = new org.omg.CORBA.StructMember (
            "sev",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ems.idls.alarms.TimeStampHelper.id (), "TimeStamp", _tcOf_members0);
          _members0[5] = new org.omg.CORBA.StructMember (
            "tStamp",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ems.idls.alarms.AcknowledgementHelper.id (), "Acknowledgement", _tcOf_members0);
          _members0[6] = new org.omg.CORBA.StructMember (
            "ack",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ems.idls.alarms.AlarmNotificationHelper.id (), "AlarmNotification", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ems.idls.alarms.AlarmNotification read (org.omg.CORBA.portable.InputStream istream)
  {
    ems.idls.alarms.AlarmNotification value = new ems.idls.alarms.AlarmNotification ();
    value.neid = istream.read_string ();
    value.code = istream.read_long ();
    value.mObject = istream.read_long ();
    value.mObjectInstance = istream.read_longlong ();
    value.sev = ems.idls.alarms.SeverityHelper.read (istream);
    value.tStamp = istream.read_string ();
    value.ack = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ems.idls.alarms.AlarmNotification value)
  {
    ostream.write_string (value.neid);
    ostream.write_long (value.code);
    ostream.write_long (value.mObject);
    ostream.write_longlong (value.mObjectInstance);
    ems.idls.alarms.SeverityHelper.write (ostream, value.sev);
    ostream.write_string (value.tStamp);
    ostream.write_string (value.ack);
  }

}
