package ems.idls.alarms;


/**
* ems/idls/alarms/AlarmInformationSequenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from alarms.idl
* Tuesday, January 15, 2015 5:02:23 PM CST
*/


/**
    * Sequence(vector) of Alarm Information structures
    */
public final class AlarmInformationSequenceHolder implements org.omg.CORBA.portable.Streamable
{
  public ems.idls.alarms.AlarmInformation value[] = null;

  public AlarmInformationSequenceHolder ()
  {
  }

  public AlarmInformationSequenceHolder (ems.idls.alarms.AlarmInformation[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ems.idls.alarms.AlarmInformationSequenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ems.idls.alarms.AlarmInformationSequenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ems.idls.alarms.AlarmInformationSequenceHelper.type ();
  }

}
