package ems.idls.alarms;


/**
* ems/idls/alarms/AlarmInformation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from alarms.idl
* Tuesday, January 15, 2015 5:02:23 PM CST
*/

public final class AlarmInformation implements org.omg.CORBA.portable.IDLEntity
{
  public int code = (int)0;
  public ems.idls.alarms.AlarmCategory aCategory = null;
  public long hWaterMark = (long)0;
  public long lWaterMark = (long)0;
  public ems.idls.alarms.Severity sev = null;
  public boolean autoClearing = false;
  public boolean filterEnabled = false;
  public String desc = null;
  public String res = null;

  public AlarmInformation ()
  {
  } // ctor

  public AlarmInformation (int _code, ems.idls.alarms.AlarmCategory _aCategory, long _hWaterMark, long _lWaterMark, ems.idls.alarms.Severity _sev, boolean _autoClearing, boolean _filterEnabled, String _desc, String _res)
  {
    code = _code;
    aCategory = _aCategory;
    hWaterMark = _hWaterMark;
    lWaterMark = _lWaterMark;
    sev = _sev;
    autoClearing = _autoClearing;
    filterEnabled = _filterEnabled;
    desc = _desc;
    res = _res;
  } // ctor

} // class AlarmInformation
