package ems.idls.alarms;


/**
* ems/idls/alarms/alarmInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from alarms.idl
* Tuesday, January 15, 2015 5:02:23 PM CST
*/


/**
    * Command/Method interface
    */
public interface alarmInterfaceOperations 
{

  /**
         * Retrieve the list of outstanding Alarms from the EMS. This is used when
         * the client first establishes connection and when the client wishes to 
         * resynchronize its outstanding alarms list.
         */
  void getOutstandingAlarms (ems.idls.alarms.AlarmNotificationSequenceHolder outstandingAlarms);

  /**
         * Retrieve the list of all possible Alarms in the system. This list includes
         * all Alarm descriptors and attributes and should be used by the client
         * entity for displaying outstanding alarms.
         */
  void getAlarmInventory (ems.idls.alarms.AlarmInformationSequenceHolder alarmInventory);
} // interface alarmInterfaceOperations
