package ems.idls.alarms;


/**
* ems/idls/alarms/Severity.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from alarms.idl
* Tuesday, January 15, 2015 5:02:23 PM CST
*/


/**
    * Alarm Severity Type (User Severity gets reported)
    */
public class Severity implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 5;
  private static ems.idls.alarms.Severity[] __array = new ems.idls.alarms.Severity [__size];

  public static final int _CRITICAL = 0;
  public static final ems.idls.alarms.Severity CRITICAL = new ems.idls.alarms.Severity(_CRITICAL);
  public static final int _MAJOR = 1;
  public static final ems.idls.alarms.Severity MAJOR = new ems.idls.alarms.Severity(_MAJOR);
  public static final int _MINOR = 2;
  public static final ems.idls.alarms.Severity MINOR = new ems.idls.alarms.Severity(_MINOR);
  public static final int _WARNING = 3;
  public static final ems.idls.alarms.Severity WARNING = new ems.idls.alarms.Severity(_WARNING);
  public static final int _CLEAR = 4;
  public static final ems.idls.alarms.Severity CLEAR = new ems.idls.alarms.Severity(_CLEAR);

  public int value ()
  {
    return __value;
  }

  public static ems.idls.alarms.Severity from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected Severity (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class Severity
