package ems.idls.alarms;

/**
* ems/idls/alarms/SeverityHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from alarms.idl
* Tuesday, January 15, 2015 5:02:23 PM CST
*/


/**
    * Alarm Severity Type (User Severity gets reported)
    */
public final class SeverityHolder implements org.omg.CORBA.portable.Streamable
{
  public ems.idls.alarms.Severity value = null;

  public SeverityHolder ()
  {
  }

  public SeverityHolder (ems.idls.alarms.Severity initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ems.idls.alarms.SeverityHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ems.idls.alarms.SeverityHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ems.idls.alarms.SeverityHelper.type ();
  }

}
