Source = \
	AlarmEventMessage.cpp \

IncludeDirs = \
        /usr/include \
        ${COMPILER_VERSION} \
        ${ACE_ROOT} \

LibraryDirs = \
        /usr/lib \
        ${ACE_ROOT}/ace \

Libraries = \
        ACE \
	ACE_RMCast \
	platformlogger \
	platformmsgmgr \

Main    = 

include $(DEV_ROOT)/make/Makefile
