Source = \
	run.cpp \

IncludeDirs = \
	/usr/include \
	${COMPILER_VERSION} \
	${ACE_ROOT} \

LibraryDirs = \
        /usr/lib \
	${ACE_ROOT}/ace \

Libraries = \
	ACE \

Main      = test3

include $(DEV_ROOT)/make/Makefile
