// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_codegen.cpp:135

#ifndef _TAO_IDL_CPPSOURCE_ALARMSC_H_
#define _TAO_IDL_CPPSOURCE_ALARMSC_H_


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/VarOut_T.h"
#include /**/ "tao/Versioned_Namespace.h"

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from 
// ../../../TAO/TAO_IDL/be/be_visitor_root/root_ch.cpp:62
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  class Collocation_Proxy_Broker;
  template<typename T> class Narrow_Utils;
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:49

namespace alarms
{
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typedef/typedef_ch.cpp:413
  
  typedef char * NEIDType;
  typedef ::CORBA::String_var NEIDType_var;
  typedef ::CORBA::String_out NEIDType_out;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_NEIDType;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typedef/typedef_ch.cpp:379
  
  typedef ::CORBA::Long AlarmCode;
  typedef ::CORBA::Long_out AlarmCode_out;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_AlarmCode;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typedef/typedef_ch.cpp:379
  
  typedef ::CORBA::Long ManagedObject;
  typedef ::CORBA::Long_out ManagedObject_out;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_ManagedObject;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typedef/typedef_ch.cpp:379
  
  typedef ::CORBA::LongLong ManagedObjectInstance;
  typedef ::CORBA::LongLong_out ManagedObjectInstance_out;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_ManagedObjectInstance;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_enum/enum_ch.cpp:57
  
  enum Severity
  {
    CRITICAL,
    MAJOR,
    MINOR,
    WARNING,
    CLEAR
  };
  
  typedef Severity &Severity_out;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_Severity;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typedef/typedef_ch.cpp:413
  
  typedef char * TimeStamp;
  typedef ::CORBA::String_var TimeStamp_var;
  typedef ::CORBA::String_out TimeStamp_out;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_TimeStamp;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typedef/typedef_ch.cpp:413
  
  typedef char * Acknowledgement;
  typedef ::CORBA::String_var Acknowledgement_var;
  typedef ::CORBA::String_out Acknowledgement_out;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_Acknowledgement;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_type.cpp:269
  
  struct AlarmNotification;
  
  typedef
    TAO_Var_Var_T<
        AlarmNotification
      >
    AlarmNotification_var;
  
  typedef
    TAO_Out_T<
        AlarmNotification
      >
    AlarmNotification_out;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:57
  
  struct  AlarmNotification
  {
    typedef AlarmNotification_var _var_type;
    typedef AlarmNotification_out _out_type;
    
    static void _tao_any_destructor (void *);
    TAO::String_Manager neid;
    alarms::AlarmCode code;
    alarms::ManagedObject mObject;
    alarms::ManagedObjectInstance mObjectInstance;
    alarms::Severity sev;
    TAO::String_Manager tStamp;
    TAO::String_Manager ack;
  };
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_AlarmNotification;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_sequence/sequence_ch.cpp:107

#if !defined (_ALARMS_ALARMNOTIFICATIONSEQUENCE_CH_)
#define _ALARMS_ALARMNOTIFICATIONSEQUENCE_CH_
  
  class AlarmNotificationSequence;
  
  typedef
    TAO_VarSeq_Var_T<
        AlarmNotificationSequence
      >
    AlarmNotificationSequence_var;
  
  typedef
    TAO_Seq_Out_T<
        AlarmNotificationSequence
      >
    AlarmNotificationSequence_out;
  
  class  AlarmNotificationSequence
    : public
        TAO::unbounded_value_sequence<
            AlarmNotification
          >
  {
  public:
    AlarmNotificationSequence (void);
    AlarmNotificationSequence ( ::CORBA::ULong max);
    AlarmNotificationSequence (
        ::CORBA::ULong max,
        ::CORBA::ULong length,
        AlarmNotification* buffer, 
        ::CORBA::Boolean release = false
      );
    AlarmNotificationSequence (const AlarmNotificationSequence &);
    virtual ~AlarmNotificationSequence (void);
    
    static void _tao_any_destructor (void *);
    
    typedef AlarmNotificationSequence_var _var_type;
    typedef AlarmNotificationSequence_out _out_type;
    
    
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_AlarmNotificationSequence;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_enum/enum_ch.cpp:57
  
  enum AlarmCategory
  {
    COMMUNICATIONS_ALARM,
    QUALITY_OF_SERVICE_ALARM,
    PROCESSING_ERROR_ALARM,
    EQUIPMENT_ALARM,
    ENVIRONMENTAL_ALARM
  };
  
  typedef AlarmCategory &AlarmCategory_out;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_AlarmCategory;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typedef/typedef_ch.cpp:379
  
  typedef ::CORBA::LongLong HighWaterMark;
  typedef ::CORBA::LongLong_out HighWaterMark_out;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_HighWaterMark;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typedef/typedef_ch.cpp:379
  
  typedef ::CORBA::LongLong LowWaterMark;
  typedef ::CORBA::LongLong_out LowWaterMark_out;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_LowWaterMark;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typedef/typedef_ch.cpp:379
  
  typedef ::CORBA::Boolean IsAutoClearing;
  typedef ::CORBA::Boolean_out IsAutoClearing_out;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_IsAutoClearing;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typedef/typedef_ch.cpp:379
  
  typedef ::CORBA::Boolean IsFilterEnabled;
  typedef ::CORBA::Boolean_out IsFilterEnabled_out;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_IsFilterEnabled;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typedef/typedef_ch.cpp:413
  
  typedef char * Description;
  typedef ::CORBA::String_var Description_var;
  typedef ::CORBA::String_out Description_out;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_Description;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typedef/typedef_ch.cpp:413
  
  typedef char * Resolution;
  typedef ::CORBA::String_var Resolution_var;
  typedef ::CORBA::String_out Resolution_out;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_Resolution;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_type.cpp:269
  
  struct AlarmInformation;
  
  typedef
    TAO_Var_Var_T<
        AlarmInformation
      >
    AlarmInformation_var;
  
  typedef
    TAO_Out_T<
        AlarmInformation
      >
    AlarmInformation_out;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:57
  
  struct  AlarmInformation
  {
    typedef AlarmInformation_var _var_type;
    typedef AlarmInformation_out _out_type;
    
    static void _tao_any_destructor (void *);
    alarms::AlarmCode code;
    alarms::AlarmCategory aCategory;
    alarms::HighWaterMark hWaterMark;
    alarms::LowWaterMark lWaterMark;
    alarms::Severity sev;
    alarms::IsAutoClearing autoClearing;
    alarms::IsFilterEnabled filterEnabled;
    TAO::String_Manager desc;
    TAO::String_Manager res;
  };
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_AlarmInformation;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_sequence/sequence_ch.cpp:107

#if !defined (_ALARMS_ALARMINFORMATIONSEQUENCE_CH_)
#define _ALARMS_ALARMINFORMATIONSEQUENCE_CH_
  
  class AlarmInformationSequence;
  
  typedef
    TAO_VarSeq_Var_T<
        AlarmInformationSequence
      >
    AlarmInformationSequence_var;
  
  typedef
    TAO_Seq_Out_T<
        AlarmInformationSequence
      >
    AlarmInformationSequence_out;
  
  class  AlarmInformationSequence
    : public
        TAO::unbounded_value_sequence<
            AlarmInformation
          >
  {
  public:
    AlarmInformationSequence (void);
    AlarmInformationSequence ( ::CORBA::ULong max);
    AlarmInformationSequence (
        ::CORBA::ULong max,
        ::CORBA::ULong length,
        AlarmInformation* buffer, 
        ::CORBA::Boolean release = false
      );
    AlarmInformationSequence (const AlarmInformationSequence &);
    virtual ~AlarmInformationSequence (void);
    
    static void _tao_any_destructor (void *);
    
    typedef AlarmInformationSequence_var _var_type;
    typedef AlarmInformationSequence_out _out_type;
    
    
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_AlarmInformationSequence;
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_interface.cpp:638

#if !defined (_ALARMS_ALARMINTERFACE__VAR_OUT_CH_)
#define _ALARMS_ALARMINTERFACE__VAR_OUT_CH_
  
  class alarmInterface;
  typedef alarmInterface *alarmInterface_ptr;
  
  typedef
    TAO_Objref_Var_T<
        alarmInterface
      >
    alarmInterface_var;
  
  typedef
    TAO_Objref_Out_T<
        alarmInterface
      >
    alarmInterface_out;

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:54

#if !defined (_ALARMS_ALARMINTERFACE_CH_)
#define _ALARMS_ALARMINTERFACE_CH_
  
  class  alarmInterface
    : public virtual ::CORBA::Object
  {
  public:
    friend class TAO::Narrow_Utils<alarmInterface>;
    typedef alarmInterface_ptr _ptr_type;
    typedef alarmInterface_var _var_type;
    typedef alarmInterface_out _out_type;
    
    // The static operations.
    static alarmInterface_ptr _duplicate (alarmInterface_ptr obj);
    
    static void _tao_release (alarmInterface_ptr obj);
    
    static alarmInterface_ptr _narrow (::CORBA::Object_ptr obj);
    static alarmInterface_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static alarmInterface_ptr _nil (void)
    {
      return static_cast<alarmInterface_ptr> (0);
    }
    
    static void _tao_any_destructor (void *);
    
    // TAO_IDL - Generated from
    // ../../../TAO/TAO_IDL/be/be_visitor_operation/operation_ch.cpp:46
    
    virtual void getOutstandingAlarms (
        ::alarms::AlarmNotificationSequence_out outstandingAlarms);
    
    // TAO_IDL - Generated from
    // ../../../TAO/TAO_IDL/be/be_visitor_operation/operation_ch.cpp:46
    
    virtual void getAlarmInventory (
        ::alarms::AlarmInformationSequence_out alarmInventory);
    
    // TAO_IDL - Generated from
    // ../../../TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:216
    
    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  private:
    TAO::Collocation_Proxy_Broker *the_TAO_alarmInterface_Proxy_Broker_;
  
  protected:
    // Concrete interface only.
    alarmInterface (void);
    
    // These methods travese the inheritance tree and set the
    // parents piece of the given class in the right mode.
    virtual void alarms_alarmInterface_setup_collocation (void);
    
    // Concrete non-local interface only.
    alarmInterface (
        IOP::IOR *ior,
        TAO_ORB_Core *orb_core = 0);
    
    // Non-local interface only.
    alarmInterface (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = 0,
        TAO_ORB_Core *orb_core = 0);
    
    virtual ~alarmInterface (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    alarmInterface (const alarmInterface &);
    
    void operator= (const alarmInterface &);
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_alarmInterface;

// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:78

} // module alarms

// Proxy Broker Factory function pointer declarations.

// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_root/root.cpp:139

extern 
TAO::Collocation_Proxy_Broker *
(*alarms__TAO_alarmInterface_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj
  );

// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_traits.cpp:64

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_ALARMS_ALARMINTERFACE__TRAITS_)
#define _ALARMS_ALARMINTERFACE__TRAITS_
  
  template<>
  struct  Objref_Traits< ::alarms::alarmInterface>
  {
    static ::alarms::alarmInterface_ptr duplicate (
        ::alarms::alarmInterface_ptr
      );
    static void release (
        ::alarms::alarmInterface_ptr
      );
    static ::alarms::alarmInterface_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::alarms::alarmInterface_ptr p,
        TAO_OutputCDR & cdr
      );
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_enum/any_op_ch.cpp:52
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 void operator<<= (::CORBA::Any &, alarms::Severity);
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, alarms::Severity &);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const alarms::AlarmNotification &); // copying version
 void operator<<= (::CORBA::Any &, alarms::AlarmNotification*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, alarms::AlarmNotification *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const alarms::AlarmNotification *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_sequence/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= ( ::CORBA::Any &, const alarms::AlarmNotificationSequence &); // copying version
 void operator<<= ( ::CORBA::Any &, alarms::AlarmNotificationSequence*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, alarms::AlarmNotificationSequence *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const alarms::AlarmNotificationSequence *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_enum/any_op_ch.cpp:52
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 void operator<<= (::CORBA::Any &, alarms::AlarmCategory);
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, alarms::AlarmCategory &);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_structure/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const alarms::AlarmInformation &); // copying version
 void operator<<= (::CORBA::Any &, alarms::AlarmInformation*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, alarms::AlarmInformation *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const alarms::AlarmInformation *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_sequence/any_op_ch.cpp:53


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= ( ::CORBA::Any &, const alarms::AlarmInformationSequence &); // copying version
 void operator<<= ( ::CORBA::Any &, alarms::AlarmInformationSequence*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, alarms::AlarmInformationSequence *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const alarms::AlarmInformationSequence *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_interface/any_op_ch.cpp:54



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace alarms
{
   void operator<<= ( ::CORBA::Any &, alarmInterface_ptr); // copying
   void operator<<= ( ::CORBA::Any &, alarmInterface_ptr *); // non-copying
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, alarmInterface_ptr &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, alarms::alarmInterface_ptr); // copying
 void operator<<= (::CORBA::Any &, alarms::alarmInterface_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, alarms::alarmInterface_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_enum/cdr_op_ch.cpp:50


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &strm, alarms::Severity _tao_enumerator);
 ::CORBA::Boolean operator>> (TAO_InputCDR &strm, alarms::Severity &_tao_enumerator);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const alarms::AlarmNotification &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, alarms::AlarmNotification &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_sequence/cdr_op_ch.cpp:71

#if !defined _TAO_CDR_OP_alarms_AlarmNotificationSequence_H_
#define _TAO_CDR_OP_alarms_AlarmNotificationSequence_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const alarms::AlarmNotificationSequence &_tao_sequence
  );
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    alarms::AlarmNotificationSequence &_tao_sequence
  );
TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_alarms_AlarmNotificationSequence_H_ */

// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_enum/cdr_op_ch.cpp:50


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &strm, alarms::AlarmCategory _tao_enumerator);
 ::CORBA::Boolean operator>> (TAO_InputCDR &strm, alarms::AlarmCategory &_tao_enumerator);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const alarms::AlarmInformation &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, alarms::AlarmInformation &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_sequence/cdr_op_ch.cpp:71

#if !defined _TAO_CDR_OP_alarms_AlarmInformationSequence_H_
#define _TAO_CDR_OP_alarms_AlarmInformationSequence_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const alarms::AlarmInformationSequence &_tao_sequence
  );
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    alarms::AlarmInformationSequence &_tao_sequence
  );
TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_alarms_AlarmInformationSequence_H_ */

// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_interface/cdr_op_ch.cpp:55

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const alarms::alarmInterface_ptr );
 ::CORBA::Boolean operator>> (TAO_InputCDR &, alarms::alarmInterface_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_codegen.cpp:1228
#if defined (__ACE_INLINE__)
#include "alarmsC.inl"
#endif /* defined INLINE */

#endif /* ifndef */


