// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_codegen.cpp:487

#ifndef _TAO_IDL_CPPSOURCE_ALARMSS_H_
#define _TAO_IDL_CPPSOURCE_ALARMSS_H_


#include "alarmsC.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

#include "tao/Collocation_Proxy_Broker.h"
#include "tao/PortableServer/PortableServer.h"
#include "tao/PortableServer/Servant_Base.h"

// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_module/module_sh.cpp:49

namespace POA_alarms
{
  
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_interface/interface_sh.cpp:87
  
  class alarmInterface;
  typedef alarmInterface *alarmInterface_ptr;
  
  class  alarmInterface
    : public virtual PortableServer::ServantBase
  {
  protected:
    alarmInterface (void);
  
  public:
    // Useful for template programming.
    typedef ::alarms::alarmInterface _stub_type;
    typedef ::alarms::alarmInterface_ptr _stub_ptr_type;
    typedef ::alarms::alarmInterface_var _stub_var_type;
    
    alarmInterface (const alarmInterface& rhs);
    virtual ~alarmInterface (void);
    
    virtual ::CORBA::Boolean _is_a (const char* logical_type_id);
    
    static void _is_a_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant
      );
    
    static void _non_existent_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant
      );
    
    static void _interface_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant
      );
    
    static void _component_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant
      );
    
    static void _repository_id_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    virtual void _dispatch (
        TAO_ServerRequest & req,
        void * servant_upcall);
    
    ::alarms::alarmInterface *_this (void);
    
    virtual const char* _interface_repository_id (void) const;
    
    // TAO_IDL - Generated from
    // ../../../TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:45
    
    virtual void getOutstandingAlarms (
        ::alarms::AlarmNotificationSequence_out outstandingAlarms) = 0;
    
    static void getOutstandingAlarms_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant
      );
    
    // TAO_IDL - Generated from
    // ../../../TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:45
    
    virtual void getAlarmInventory (
        ::alarms::AlarmInformationSequence_out alarmInventory) = 0;
    
    static void getAlarmInventory_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant
      );
  };

// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_module/module_sh.cpp:80

} // module alarms

// TAO_IDL - Generated from 
// ../../../TAO/TAO_IDL/be/be_codegen.cpp:1290


#if defined (__ACE_INLINE__)
#include "alarmsS.inl"
#endif /* defined INLINE */

#endif /* ifndef */

