Source = \
	alarmsC.cpp \
	alarmsS.cpp \
	platformConfigC.cpp \
	platformConfigS.cpp \
	sessionC.cpp \
	sessionS.cpp \

LocalCppOptions =

IncludeDirs = \
        /usr/include \
        ${COMPILER_VERSION} \
        ${ACE_ROOT} \
	${TAO_ROOT} \

LibraryDirs = \
        /usr/lib \
        ${ACE_ROOT}/ace \
	${ACE_ROOT}/lib \

Libraries = \
        ACE \
	TAO \

Main    = 

include $(DEV_ROOT)/make/Makefile
