// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from 
// ../../../TAO/TAO_IDL/be/be_codegen.cpp:1135

#ifndef CPPSOURCE_PLATFORMCONFIGI_H_
#define CPPSOURCE_PLATFORMCONFIGI_H_

#include "platformConfigS.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
#pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

class  platformConfig_platformConfig_I_i
  : public virtual POA_platformConfig::platformConfig_I
{
public:
  // Constructor 
  platformConfig_platformConfig_I_i (void);
  
  // Destructor 
  virtual ~platformConfig_platformConfig_I_i (void);
  
  virtual
  void getLogLevels (
      ::platformConfig::platformConfigLogLevels_out logLevels);
  
  virtual
  void setLogLevel (
      const ::platformConfig::platformConfigLogLevel & logLevel);
  
  virtual
  void setLogLevels (
      const ::platformConfig::platformConfigLogLevels & logLevels);
};


#endif /* CPPSOURCE_PLATFORMCONFIGI_H_  */

