// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from 
// ../../../TAO/TAO_IDL/be/be_codegen.cpp:1135

#ifndef CPPSOURCE_SESSIONI_H_
#define CPPSOURCE_SESSIONI_H_

#include "sessionS.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
#pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

class  session_Session_I_i
  : public virtual POA_session::Session_I
{
public:
  // Constructor 
  session_Session_I_i (void);
  
  // Destructor 
  virtual ~session_Session_I_i (void);
  
  virtual
  ::session::Session_I_ptr associatedSession (
      void);
  
  virtual
  void ping (
      void);
  
  virtual
  void endSession (
      void);
};


#endif /* CPPSOURCE_SESSIONI_H_  */

