// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_codegen.cpp:381


#include "sessionC.h"
#include "tao/AnyTypeCode/Null_RefCount_Policy.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/AnyTypeCode/Alias_TypeCode_Static.h"
#include "tao/AnyTypeCode/Objref_TypeCode_Static.h"
#include "tao/CDR.h"
#include "tao/Exception_Data.h"
#include "tao/Invocation_Adapter.h"
#include "tao/Object_T.h"
#include "tao/CDR.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/AnyTypeCode/Any_Impl_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Object_Argument_T.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "sessionC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:73

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
  
  // TAO_IDL - Generated from
  // ../../../TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:141

#if !defined (_SESSION_SESSION_I__ARG_TRAITS_)
#define _SESSION_SESSION_I__ARG_TRAITS_
  
  template<>
  class  Arg_Traits<session::Session_I>
    : public
        Object_Arg_Traits_T<
            session::Session_I_ptr,
            session::Session_I_var,
            session::Session_I_out,
            TAO::Objref_Traits<session::Session_I>,
            TAO::Any_Insert_Policy_Stream <session::Session_I_ptr>
          >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:60

// Traits specializations for session::Session_I.

session::Session_I_ptr
TAO::Objref_Traits<session::Session_I>::duplicate (
    session::Session_I_ptr p)
{
  return session::Session_I::_duplicate (p);
}

void
TAO::Objref_Traits<session::Session_I>::release (
    session::Session_I_ptr p)
{
  ::CORBA::release (p);
}

session::Session_I_ptr
TAO::Objref_Traits<session::Session_I>::nil (void)
{
  return session::Session_I::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<session::Session_I>::marshal (
    const session::Session_I_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

// Function pointer for collocation factory initialization.
TAO::Collocation_Proxy_Broker * 
(*session__TAO_Session_I_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj
  ) = 0;

// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_operation/operation_cs.cpp:78

::session::Session_I_ptr session::Session_I::associatedSession (
    void)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_Session_I_Proxy_Broker_ == 0)
    {
      session_Session_I_setup_collocation ();
    }
  
  TAO::Arg_Traits< ::session::Session_I>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_associatedSession",
      22,
      this->the_TAO_Session_I_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_operation/operation_cs.cpp:78

void session::Session_I::ping (
    void)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_Session_I_Proxy_Broker_ == 0)
    {
      session_Session_I_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "ping",
      4,
      this->the_TAO_Session_I_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_operation/operation_cs.cpp:78

void session::Session_I::endSession (
    void)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_Session_I_Proxy_Broker_ == 0)
    {
      session_Session_I_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "endSession",
      10,
      this->the_TAO_Session_I_Proxy_Broker_,
      TAO::TAO_ONEWAY_INVOCATION
    );
  
  _tao_call.invoke (0, 0);
}

session::Session_I::Session_I (void)
 : the_TAO_Session_I_Proxy_Broker_ (0)
{
  this->session_Session_I_setup_collocation ();
}

void
session::Session_I::session_Session_I_setup_collocation ()
{
  if (::session__TAO_Session_I_Proxy_Broker_Factory_function_pointer)
    {
      this->the_TAO_Session_I_Proxy_Broker_ =
        ::session__TAO_Session_I_Proxy_Broker_Factory_function_pointer (this);
    }
}

session::Session_I::~Session_I (void)
{}

void 
session::Session_I::_tao_any_destructor (void *_tao_void_pointer)
{
  Session_I *_tao_tmp_pointer =
    static_cast<Session_I *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

session::Session_I_ptr
session::Session_I::_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return
    TAO::Narrow_Utils<Session_I>::narrow (
        _tao_objref,
        "IDL:mtnm.tmforum.org/session/Session_I:1.0",
        session__TAO_Session_I_Proxy_Broker_Factory_function_pointer
      );
}

session::Session_I_ptr
session::Session_I::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return
    TAO::Narrow_Utils<Session_I>::unchecked_narrow (
        _tao_objref,
        "IDL:mtnm.tmforum.org/session/Session_I:1.0",
        session__TAO_Session_I_Proxy_Broker_Factory_function_pointer
      );
}

session::Session_I_ptr
session::Session_I::_duplicate (Session_I_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  
  return obj;
}

void
session::Session_I::_tao_release (Session_I_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
session::Session_I::_is_a (const char *value)
{
  if (
      !ACE_OS::strcmp (
          value,
          "IDL:mtnm.tmforum.org/session/Session_I:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* session::Session_I::_interface_repository_id (void) const
{
  return "IDL:mtnm.tmforum.org/session/Session_I:1.0";
}

::CORBA::Boolean
session::Session_I::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_typecode/objref_typecode.cpp:76

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_session_Session_I (
    ::CORBA::tk_objref,
    "IDL:mtnm.tmforum.org/session/Session_I:1.0",
    "Session_I");
  
namespace session
{
  ::CORBA::TypeCode_ptr const _tc_Session_I =
    &_tao_tc_session_Session_I;
}



// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_interface/any_op_cs.cpp:51
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<session::Session_I>::to_object (
      ::CORBA::Object_ptr &_tao_elem
    ) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace session
{
  
  
  /// Copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      Session_I_ptr _tao_elem)
  {
    Session_I_ptr _tao_objptr =
      Session_I::_duplicate (_tao_elem);
    _tao_any <<= &_tao_objptr;
  }
  
  /// Non-copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      Session_I_ptr *_tao_elem)
  {
    TAO::Any_Impl_T<Session_I>::insert (
        _tao_any,
        Session_I::_tao_any_destructor,
        _tc_Session_I,
        *_tao_elem)
  }
  
  ::CORBA::Boolean
  operator>>= (
      const ::CORBA::Any &_tao_any,
      Session_I_ptr &_tao_elem)
  {
    return
      TAO::Any_Impl_T<Session_I>::extract (
          _tao_any,
          Session_I::_tao_any_destructor,
          _tc_Session_I,
          _tao_elem)
  }
}

#else

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



/// Copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    session::Session_I_ptr _tao_elem)
{
  session::Session_I_ptr _tao_objptr =
    session::Session_I::_duplicate (_tao_elem);
  _tao_any <<= &_tao_objptr;
}

/// Non-copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    session::Session_I_ptr *_tao_elem)
{
  TAO::Any_Impl_T<session::Session_I>::insert (
      _tao_any,
      session::Session_I::_tao_any_destructor,
      session::_tc_Session_I,
      *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    session::Session_I_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<session::Session_I>::extract (
        _tao_any,
        session::Session_I::_tao_any_destructor,
        session::_tc_Session_I,
        _tao_elem);
}

TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_interface/cdr_op_cs.cpp:63

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const session::Session_I_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    session::Session_I_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;
  
  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  typedef ::session::Session_I RHS_SCOPED_NAME;
  
  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (
        obj.in (),
        session__TAO_Session_I_Proxy_Broker_Factory_function_pointer
      );
    
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



