// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from 
// ../../../TAO/TAO_IDL/be/be_codegen.cpp:1198

#include "cppsource/sessionI.h"

// Implementation skeleton constructor
session_Session_I_i::session_Session_I_i (void)
{
}

// Implementation skeleton destructor
session_Session_I_i::~session_Session_I_i (void)
{
}

::session::Session_I_ptr session_Session_I_i::associatedSession (
    void)
{
  // Add your implementation here
}

void session_Session_I_i::ping (
    void)
{
  // Add your implementation here
}

void session_Session_I_i::endSession (
    void)
{
  // Add your implementation here
}


