// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from 
// be/be_codegen.cpp:948

#include "sessionI.h"

#include "platform/logger/Logger.h"

// Implementation skeleton constructor
session_Session_I_i::session_Session_I_i (void)
   : associatedSession_(NULL)
{
}

// Implementation skeleton destructor
session_Session_I_i::~session_Session_I_i (void)
{
}

::session::Session_I_ptr session_Session_I_i::associatedSession ( ) ACE_THROW_SPEC (( CORBA::SystemException))
{
  // Add your implementation here
  return associatedSession_;
}

void session_Session_I_i::ping ( ) ACE_THROW_SPEC (( CORBA::SystemException))
{
  // Add your implementation here
  TRACELOG(DEBUGLOG, CLICLIENTLOG, "Received Agent initiated ping request",0,0,0,0,0,0);
}

void session_Session_I_i::endSession ( ) ACE_THROW_SPEC (( CORBA::SystemException))
{
  // Add your implementation here
  TRACELOG(DEBUGLOG, CLICLIENTLOG, "Received Agent initiated end session request",0,0,0,0,0,0);
}

void session_Session_I_i::setAssociatedSession( session::Session_I_ptr associatedSession)
{
   associatedSession_ = associatedSession;
}//end setAssociatedSession

