Source = \
	OPMTest.cpp \

IncludeDirs = \
	/usr/include \
	${COMPILER_VERSION} \
	${ACE_ROOT} \

LibraryDirs = \
        /usr/lib \
	${ACE_ROOT}/ace \

Libraries = \
	platformutilities \
	platformopm \
	platformlogger \
	ACE \

Main      = OPMTest

include $(DEV_ROOT)/make/Makefile
