Source = \
	platformConfig_IHelper.java \
	platformConfig_IHolder.java \
	platformConfig_I.java \
	platformConfig_IOperations.java \
	platformConfig_IPOA.java \
	_platformConfig_IStub.java \
	platformConfigLogLevelHelper.java \
	platformConfigLogLevelHolder.java \
	platformConfigLogLevel.java \
	platformConfigLogLevelsHelper.java \
	platformConfigLogLevelsHolder.java \

Main    = 

include $(DEV_ROOT)/make/Makefile
