package ems.idls.platformConfig;


/**
* ems/idls/platformConfig/platformConfigLogLevel.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from platformConfig.idl
* Tuesday, January 15, 2015 5:02:24 PM CST
*/

public final class platformConfigLogLevel implements org.omg.CORBA.portable.IDLEntity
{

  /** Should correspond to the sequence index */
  public short subsystemEnum = (short)0;
  public String subsystemName = null;
  public short severityLevel = (short)0;

  public platformConfigLogLevel ()
  {
  } // ctor

  public platformConfigLogLevel (short _subsystemEnum, String _subsystemName, short _severityLevel)
  {
    subsystemEnum = _subsystemEnum;
    subsystemName = _subsystemName;
    severityLevel = _severityLevel;
  } // ctor

} // class platformConfigLogLevel
