package ems.idls.platformConfig;


/**
* ems/idls/platformConfig/platformConfig_I.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from platformConfig.idl
* Tuesday, January 15, 2015 5:02:24 PM CST
*/


/**
    * Command/Method interface
    */
public interface platformConfig_I extends platformConfig_IOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface platformConfig_I
