package ems.idls.platformConfig;

/**
* ems/idls/platformConfig/platformConfig_IHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from platformConfig.idl
* Tuesday, January 15, 2015 5:02:24 PM CST
*/


/**
    * Command/Method interface
    */
public final class platformConfig_IHolder implements org.omg.CORBA.portable.Streamable
{
  public ems.idls.platformConfig.platformConfig_I value = null;

  public platformConfig_IHolder ()
  {
  }

  public platformConfig_IHolder (ems.idls.platformConfig.platformConfig_I initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ems.idls.platformConfig.platformConfig_IHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ems.idls.platformConfig.platformConfig_IHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ems.idls.platformConfig.platformConfig_IHelper.type ();
  }

}
