package ems.idls.platformConfig;

/**
* ems/idls/platformConfig/platformConfigLogLevelHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from platformConfig.idl
* Tuesday, January 15, 2015 5:02:24 PM CST
*/

public final class platformConfigLogLevelHolder implements org.omg.CORBA.portable.Streamable
{
  public ems.idls.platformConfig.platformConfigLogLevel value = null;

  public platformConfigLogLevelHolder ()
  {
  }

  public platformConfigLogLevelHolder (ems.idls.platformConfig.platformConfigLogLevel initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ems.idls.platformConfig.platformConfigLogLevelHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ems.idls.platformConfig.platformConfigLogLevelHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ems.idls.platformConfig.platformConfigLogLevelHelper.type ();
  }

}
