SharedMemoryManager Class Reference
Public Member Functions
virtual ~SharedMemoryManager ()
Static Public Member Functions
static ALLOCATOR * getAllocator ()
Friends
class FixCompilerWarning
Constructor & Destructor Documentation
SharedMemoryManager::~SharedMemoryManager () [virtual]
Virtual Destructor
Member Function Documentation
ALLOCATOR * SharedMemoryManager::getAllocator () [static]
Returns the static instance of the Shared memory mapped allocator. Performs lazy instantiation of the allocator
Referenced by LoggerSMConfig::initialize(), LoggerSMQueue::setupQueue(), FaultSMQueue::setupQueue(), and LocalSMMailboxQueue::setupQueue().
The documentation for this class was generated from the following files:
SharedMemoryManager.h
SharedMemoryManager.cpp