ems.guiclient.GuiClient Class Reference
Public Member Functions
GuiClient ()
final void initializeGUI ()
final void initializeOrb (String[] arguments)
final String toString ()
Static Public Member Functions
static void main (String[] aArguments)
Public Attributes
GuiFrame guiFrame_ = null
Detailed Description
GuiClient implements a graphical client interface for communicating to the EMS via CORBA.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
ems.guiclient.GuiClient.GuiClient () [inline]
Default Constructor
Referenced by ems.guiclient.GuiClient.main().
Member Function Documentation
final void ems.guiclient.GuiClient.initializeGUI () [inline]
Initialize the GUI Client Widgets
Referenced by ems.guiclient.GuiClient.main().
final void ems.guiclient.GuiClient.initializeOrb (String[] arguments) [inline]
Initialization Method that JacOrb CORBA initialization
Parameters
arguments Command line arguments to the Gui Client are passed directly to the JacOrb Orb for parsing out Corba specific initialization parameters.
References ems.guiclient.GuiFrame.setAgentSession(), and ems.guiclient.Session_IImpl.setAssociatedSession().
Referenced by ems.guiclient.GuiClient.main().
static void ems.guiclient.GuiClient.main (String[] aArguments) [inline], [static]
Gui Client Main Method
References ems.guiclient.GuiClient.GuiClient(), ems.guiclient.GuiClient.initializeGUI(), and ems.guiclient.GuiClient.initializeOrb().
final String ems.guiclient.GuiClient.toString () [inline]
String'ized debugging method
Returns
string representation of the contents of this object
Member Data Documentation
GuiFrame ems.guiclient.GuiClient.guiFrame_ = null
Reference to the Gui Widget
The documentation for this class was generated from the following file:
GuiClient.java