OPM Class Reference
#include <OPM.h>
Static Public Member Functions
static bool initialize ()
static void shutdown ()
static int createPool (const char *objectType, long objectInitParam, OPM_INIT_PTR bootStrapMethod, double thresholdPercentage, int capacityIncrement, int initialSize, bool threadSafe, OPMGrowthModeType growthMode)
static bool isPoolCreated (const char *objectType, long objectInitParam)
static int getObjectPoolID (const char *objectType, long objectInitParam)
static OPMBase * reserveObject (int objectPoolID, bool blockWaitingForAccess=true)
static bool releaseObject (OPMBase *object, const char *callingFileName, int callingLineNumb)
static bool isCreatedByOPM (OPMBase *objectRef)
static bool setPoolCapacityIncrement (int objectPoolID, int capacityIncrement)
static int getPoolCapacityIncrement (int objectPoolID)
static double getPoolThresholdPercentage (int objectPoolID)
static int getPoolObjectInitParam (int objectPoolID)
static void printAllPoolsSummary ()
static void printPoolSummary (int objectPoolID)
static void checkForUnreleasedObjects ()
Friends
void cliPrintAllPoolsSummary ()
void cliPrintOPMPoolSummary (int objectPoolID)
void checkForUnreleasedOPMObjects ()
Detailed Description
OPM (Object Pool Manager) manages the creation of a pool of reusable objects that can be reserved for use within the program and made available again for reuse.
OPM contains overloaded methods for creating the object pool, getting the objects from the pool and releasing the objects back into the pool. NOTE: There currently is no support for deleting/destroying existing pools and their objects.
Author
Stephen Horton
Revision
1
Member Function Documentation
void OPM::checkForUnreleasedObjects () [static]
Method tests all of the pools and prints the statistics per Object Pool for objects which HAVE NOT been properly returned/released into the OPM.
References ObjectPool::getCurrentCapacity(), ObjectPool::getCurrentUsedObjects(), and ObjectPool::getObjectType().
int OPM::createPool (const char * objectType, long objectInitParam, OPM_INIT_PTR bootStrapMethod, double thresholdPercentage, int capacityIncrement, int initialSize, bool threadSafe, OPMGrowthModeType growthMode) [static]
Method for Creating an Object Pool of Specified Object Type, Object Count, Initial capacity, capacity increment, threshold, and growth Mode.
Note that this method allows for an object Initializer to be specified for all objects in the pool.
Note that if the Object Pool already exists (ie. was created earlier by another part of the application), then the existing object Pool ID is returned.
Parameters
objectType Type of the object to be Created
objectInitParam long or pointer to initialization data needed by each of the objects in the pool, or NULL if none is needed
bootStrapMethod pointer to a function or method (OPMBase::initialize) that will create the object and return a pointer to it
thresholdPercentage double representing the percentage of the initial capacity above which to autoincrease the pool size.
capacityIncrement integer number of objects to add to the pool when autoincrementing the pool capacity
initialSize initial capacity of objects to create within the pool
threadSafe Boolean to determine if the ObjectPool should be created as thread safe or not
growthMode Either NO_GROWTH, GROWTH_ALLOWED, or GROW_AND_SHRINK
Returns
integer objectPoolID used by applications in referencing this particular object pool for retrieving objects (or ERROR if pool already exists for the specified objectType and initializer).
References getObjectPoolID().
Referenced by DistributedMailboxProxy::DistributedMailboxProxy(), GroupMailboxProxy::GroupMailboxProxy(), LocalMailbox::LocalMailbox(), LocalSMMailboxProxy::LocalSMMailboxProxy(), and ConnectionSet::performActivation().
int OPM::getObjectPoolID (const char * objectType, long objectInitParam) [static]
Method to return the Object Pool ID for an existing object Pool.
Parameters
objectType type string of the objects being pooled
objectInitParam long or pointer to initialization data needed by each of the objects in the pool
Returns
the Object Pool ID for an existing object Pool; otherwise, ERROR if the object pool does not exist.
Referenced by createPool().
int OPM::getPoolCapacityIncrement (int objectPoolID) [static]
Get the Pool Capacity Increment value which is the number of objects to add to the pool when the threshold value is reached.
Parameters
objectPoolID integer used by applications in referencing this particular object pool for retrieving objects (this is returned by createPool)
Returns
Returns the Pool Capacity Increment or -1 if there is an error
References ObjectPool::getCapacityIncrement(), and ObjectPool::release().
int OPM::getPoolObjectInitParam (int objectPoolID) [static]
Get the Pool's object initializer (or 0/NULL if there is none).
Parameters
objectPoolID integer used by applications in referencing this particular object pool for retrieving objects (this is returned by createPool)
Returns
Returns the integer initializer, pointer to data, or 0(NULL) if there is none
References ObjectPool::getObjectInitParam(), and ObjectPool::release().
double OPM::getPoolThresholdPercentage (int objectPoolID) [static]
Get the Pool Threshold Percentage value which is the factor (double) of the current capacity at which to increase the capacity.
Parameters
objectPoolID integer used by applications in referencing this particular object pool for retrieving objects (this is returned by createPool)
Returns
Returns the Pool threshold percentage as a float or 0 if there is an error
References ObjectPool::getThresholdPercentage(), and ObjectPool::release().
bool OPM::initialize () [static]
initializes the Object Pool Manager (OPM).
Referenced by FaultManager::processMailbox(), ResourceMonitor::toString(), and ProcessManager::toString().
bool OPM::isCreatedByOPM (OPMBase * objectRef) [static]
Method to test if an Object was created by the OPM. Remember that for this to be called from Multiple threads, the object pool must be thread safe.
Parameters
object OPMBase Object pointer to test
Returns
true if the specified Object was created by OPM
 false if the specified Object was created elsewhere
References ObjectPool::containsObject(), OPMBase::getPoolID(), and ObjectPool::release().
Referenced by MailboxOwnerHandle::cancelTimer(), and MessageBase::deleteMessage().
bool OPM::isPoolCreated (const char * objectType, long objectInitParam) [static]
Method to verify if an object pool has been created for the specified Object type
Parameters
objectType type string of the objects being pooled
objectInitParam long or pointer to initialization data needed by each of the objects in the pool
Returns
true if the named object pool exists
 false if the named object pool does not exist
void OPM::printAllPoolsSummary () [static]
Method prints the usage summary for all Object Pools being managed within the OPM. This method is called by default when the shutdown method is called.
void OPM::printPoolSummary (int objectPoolID) [static]
Method prints the usage summary for a particular Object Pool.
Parameters
objectPoolID integer used by applications in referencing this particular object pool for retrieving objects (this is returned by createPool)
References ObjectPool::release().
bool OPM::releaseObject (OPMBase * object, const char * callingFileName, int callingLineNumb) [static]
Method for releasing the specified object back into the OPM pool after it is no longer in-use.
Parameters
object Pointer to the Object to be released back into the Pool
callingFileName - Specifies the source file from which the object is being released (this will be printed as a DEBUG log using a MACRO)
callingLineNumb - Specifies the source line from which the object is being released (this will be printed as a DEBUG log using a MACRO)
Returns
true if the specified Object was successfully released
 false if the Object Reference was not found in the Pool's USED data structure (could be wrong pool, is already released, or) was not created via OPM)
References ObjectPool::release().
OPMBase * OPM::reserveObject (int objectPoolID, bool blockWaitingForAccess = true) [static]
Method to retrieve an object from a specified pool being managed within OPM.
Parameters
objectPoolID integer used by applications in referencing this particular object pool for retrieving objects (this is returned by createPool)
blockWaitingForAccess If true, this method will block until an object becomes available if they are all in use. Otherwise, if false, this method will return NULL if all objects are in use.
Returns
OPMBase object if the specified object type exists within OPM; otherwise, it returns NULL. NOTE that it can also return NULL if the user has requested a non-blocking call (blockWaitingForAccess = false)
References ObjectPool::release(), and ObjectPool::reserve().
bool OPM::setPoolCapacityIncrement (int objectPoolID, int capacityIncrement) [static]
Method sets the capacityIncrement for the specified Object Pool. This value is either initially specified as a parameter to the createPool() method or is chosen by the default constructor of ObjectPool.
Parameters
objectPoolID integer used by applications in referencing this particular object pool for retrieving objects (this is returned by createPool)
capacityIncrement Number of objects to add to the pool when increasing
Returns
true if the capacity increment was successfully changed
 false if setting the capacity increment failed
References ObjectPool::release(), and ObjectPool::setCapacityIncrement().
void OPM::shutdown () [static]
Method to be called when the node is shutdown. This method will reset all Objects to NULL
Friends And Related Function Documentation
void checkForUnreleasedOPMObjects () [friend]
Friend function tests all of the pools and prints the statistics per Object Pool for objects which HAVE NOT been properly returned/released into the OPM.
void cliPrintAllPoolsSummary () [friend]
Friend function prints the usage summary for all Object Pools being managed within the OPM.
void cliPrintOPMPoolSummary (int objectPoolID) [friend]
Friend function prints the usage summary for a particular Object Pool.
Parameters
objectPoolID integer used by applications in referencing this particular object pool for retrieving objects (this is returned by createPool)
The documentation for this class was generated from the following files:
OPM.h
OPM.cpp