ObjectBase Class Reference
#include <ObjectBase.h>
Public Member Functions
ObjectBase ()
virtual ~ObjectBase ()
void setPoolable (bool isPoolable)
Protected Member Functions
bool isPoolable ()
Detailed Description
Simple base class for identifying objects as OPM poolable or not, that is, whether or not they inherit from OPMBase.
Using this class the OPM and MsgMgr frameworks can distinguish between objects and messages that need to be instantiated and then deleted versus objects and messages that should be retrieved from a message pool and checked back in. Application developers should NOT derive from this class.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
ObjectBase::ObjectBase ()
Constructor
ObjectBase::~ObjectBase () [virtual]
Virtual Destructor
Member Function Documentation
bool ObjectBase::isPoolable () [protected]
Return whether or not this object is OPM poolable (inherits from OPMBase)
Referenced by MessageBase::isPoolable(), and setPoolable().
void ObjectBase::setPoolable (bool isPoolable)
Set whether or not this object is OPM poolable, that is, whether or not the object inherits from OPMBase.
References isPoolable().
Referenced by OPMBase::OPMBase().
The documentation for this class was generated from the following files:
ObjectBase.h
ObjectBase.cpp