ResourceMonitor Class Reference
Public Member Functions
ResourceMonitor ()
virtual ~ResourceMonitor ()
void processMailbox ()
int initialize (int argc, ACE_TCHAR *argv[])
string toString ()
Static Public Member Functions
static void catchShutdownSignal ()
Constructor & Destructor Documentation
ResourceMonitor::ResourceMonitor ()
Constructor
Referenced by toString().
ResourceMonitor::~ResourceMonitor () [virtual]
Virtual Destructor
Member Function Documentation
void ResourceMonitor::catchShutdownSignal () [static]
Catch the shutdown signal and begin the graceful shutdown
Referenced by initialize().
int ResourceMonitor::initialize (int argc, ACE_TCHAR * argv[])
Perform ResourceMonitor initialization
References DataManager::activateConnectionSet(), catchShutdownSignal(), ThreadManager::createThread(), SystemInfo::getLocalNEID(), MailboxAddress::inetAddress, OSResource::initialize(), DataManager::initialize(), MailboxAddress::locationType, MailboxAddress::mailboxName, MailboxAddress::neid, and MailboxOwnerHandle::scheduleTimer().
Referenced by toString().
void ResourceMonitor::processMailbox ()
Start the mailbox processing loop
References MailboxOwnerHandle::activate(), and MailboxProcessor::processMailbox().
Referenced by toString().
string ResourceMonitor::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
References MessageHandlerList::add(), OSResource::checkCPUUsage(), OSResource::checkDiskUsage(), OSResource::checkMemoryUsage(), DistributedMailbox::createMailbox(), Faults::getInstance(), Logger::getInstance(), initialize(), OPM::initialize(), Faults::initialize(), Logger::initialize(), processMailbox(), ResourceMonitor(), and Logger::setSubsystemLogLevel().
The documentation for this class was generated from the following files:
ResourceMonitor.h
ResourceMonitor.cpp