OSResource Class Reference
#include <OSResource.h>
Public Member Functions
OSResource ()
virtual ~OSResource ()
int initialize ()
int checkDiskUsage ()
int checkCPUUsage ()
int checkMemoryUsage ()
Detailed Description
OSResource provides the mechanisms for monitoring OS-controlled resources including Memory, CPU, and Disk usages.
With regard to measuring CPU usage on Linux: Linux provides cumulative counts for the number of jiffies spent in user, nice, system, and idle CPU mode since the system was booted, or since the jiffy count last wrapped round. A jiffy is a proverbial short amount of time, which is 1/100 second on most CPUs (1/1024 on Alphas).
The four jiffy counts are given in the /proc/stat file, on a line beginning with the word cpu. On multiprocessor systems, the counts are given for each cpu, each on a line beginning with the word cpun, where n is the zero-based CPU number, and the line starting with cpu contains the sums for all processors.
The duration of a jiffy, and the cumulative number of jiffies, are not much use to us; what is important is the number of jiffies spent in each mode since the last time we had a look. We calculate the differences for each of the modes, and express each difference as a percentage of the total difference.
For measuring memory usage, we inspect the fields taken from /proc/meminfo. Note that this calculation should agree with the output of the 'free' utility (2nd output line). The calculations are as follows: Memory Used = MemTotal - MemFree - Buffers - Cached Also perform Swap calculation: Swap Used = SwapTotal - SwapFree - SwapCached
Disk usage values are gathered by comparing /etc/fstab with the output from the statfs library call.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
OSResource::OSResource ()
Constructor
OSResource::~OSResource () [virtual]
Virtual Destructor
Member Function Documentation
int OSResource::checkCPUUsage ()
Check CPU usage based on statistics in the Linux proc filesystem
Returns
ERROR upon failure; otherwise OK
Could use NEID as the managed object instance??
References SystemInfo::getLocalNEID().
Referenced by ResourceMonitor::toString().
int OSResource::checkDiskUsage ()
Check disk usage for all detected filesystem partitions
Returns
ERROR upon failure; otherwise OK
References SystemInfo::getLocalNEID().
Referenced by ResourceMonitor::toString().
int OSResource::checkMemoryUsage ()
Check memory usage based on statistics in the Linux proc filesystem
Returns
ERROR upon failure; otherwise OK
Could use NEID as the managed object instance??
References SystemInfo::getLocalNEID().
Referenced by ResourceMonitor::toString().
int OSResource::initialize ()
Initialize the structures for tracking resource usage
Returns
ERROR upon failure; otherwise OK
References DbConnectionHandle::closeCommandResult(), DbConnectionHandle::executeCommand(), DbConnectionHandle::getColumnCount(), DbConnectionHandle::getColumnIndex(), DbConnectionHandle::getIntValueAt(), DbConnectionHandle::getRowCount(), DbConnectionHandle::getShortValueAt(), Logger::getSubsystemLogLevel(), DataManager::releaseConnection(), and DataManager::reserveConnection().
Referenced by ResourceMonitor::initialize().
The documentation for this class was generated from the following files:
OSResource.h
OSResource.cpp