DiscoveryManager Class Reference
Public Member Functions
DiscoveryManager ()
virtual ~DiscoveryManager ()
int initialize ()
int registerForDiscoveryUpdates (vector< MailboxAddress > &currentlyRegisteredAddresses, MailboxAddress &matchCriteria, MailboxOwnerHandle *mailboxToNotify)
int deregisterForDiscoveryUpdates (MailboxOwnerHandle *mailboxToNotify)
int registerLocalAddress (MailboxAddress &localRemoteTypeAddress)
int deregisterLocalAddress (MailboxAddress &localRemoteTypeAddress)
void listAllMailboxAddresses ()
void processMailbox ()
Constructor & Destructor Documentation
DiscoveryManager::DiscoveryManager ()
Constructor
References SystemInfo::getLocalNEID(), MailboxAddress::inetAddress, MailboxAddress::locationType, MailboxAddress::mailboxName, and MailboxAddress::neid.
DiscoveryManager::~DiscoveryManager () [virtual]
Virtual Destructor
Member Function Documentation
int DiscoveryManager::deregisterForDiscoveryUpdates (MailboxOwnerHandle * mailboxToNotify)
Allows mailboxes to deregister for Discovery Update notifications
Returns
OK upon success; otherwise ERROR
Referenced by MailboxLookupService::deregisterMailbox().
int DiscoveryManager::deregisterLocalAddress (MailboxAddress & localRemoteTypeAddress)
Remove the local registration of a remote type Non-Proxy MailboxAddress. This will facilitate a discovery DEREGISTER update being sent to all other DiscoveryManagers.
Returns
OK upon successful registration; otherwise ERROR
References MailboxOwnerHandle::post().
Referenced by MailboxLookupService::deregisterMailbox().
int DiscoveryManager::initialize ()
Perform initialization of Discovery Manager which communicates mailbox updates between distributed nodes.
Returns
OK upon success; otherwise ERROR
References MailboxOwnerHandle::activate(), MessageHandlerList::add(), GroupMailbox::createMailbox(), DiscoveryMessage::deserialize(), and MessageFactory::registerSupport().
Referenced by MailboxLookupService::initializeDiscoveryManager().
void DiscoveryManager::listAllMailboxAddresses ()
Display a list of all the registered remote type Non-Proxy mailbox addresses This method displays its output in trace logs.
References MailboxOwnerHandle::post().
Referenced by MailboxLookupService::listAllMailboxAddresses().
void DiscoveryManager::processMailbox ()
Start the mailbox processing loop
References MailboxOwnerHandle::activate(), GroupMailboxProxy::createMailbox(), DiscoveryMessage::getDiscoveryAddress(), DiscoveryLocalMessage::getDiscoveryAddress(), DiscoveryMessage::getOperationType(), DiscoveryLocalMessage::getOperationType(), DiscoveryMessage::getOriginatingPID(), MessageBase::getSourceAddress(), MailboxAddress::isMatchingAddress(), MailboxOwnerHandle::post(), MailboxProcessor::processMailbox(), MailboxOwnerHandle::setDebugValue(), DiscoveryLocalMessage::toString(), DiscoveryMessage::toString(), and MailboxAddress::toString().
Referenced by MailboxLookupService::getDebugForAllMailboxAddresses().
int DiscoveryManager::registerForDiscoveryUpdates (vector< MailboxAddress > & currentlyRegisteredAddresses, MailboxAddress & matchCriteria, MailboxOwnerHandle * mailboxToNotify)
Allows mailboxes to register for Discovery Update notifications. If a DiscoveryMessage update is received whose discovery Mailbox Address matches that of the matchCriteria, then a copy of the DiscoveryMessage is posted to the mailboxToNotify. The caller is required to pre-allocate a vector of MailboxAddresses which will be populated with 'already-discovered' MailboxAddresses and returned.
Note that current there is no support for a user-initiated deregistration mechanism. This is because the discovery update mechanism should not be used as a substitute for IPC between nodes.
Parameters
matchCriteria MailboxAddress object used to determine which discovery Mailbox Addresses match what the application wants to be notified about. NOTE: The calling application should leave all fields default except those that the caller wished to be used in the match comparison. For example, if the caller wants to be notified when any Mailboxes with the MailboxName 'CallProcessor' are discovered, the matchCriteria field 'MailboxName' will be set to 'CallProcessor' and all other fields left as the default.
mailboxToNotify MailboxOwnerHandle of the mailbox that will receive the DiscoveryMessage notification when an update is received. This mailbox must provide a MessageHandler method for the Discovery Message id (MSGMGR_DISCOVERY_MSG_ID)
Returns
OK upon successful registration; otherwise ERROR
References MailboxAddress::isMatchingAddress().
Referenced by MailboxLookupService::registerForDiscoveryUpdates().
int DiscoveryManager::registerLocalAddress (MailboxAddress & localRemoteTypeAddress)
Add local registration of a remote type Non-Proxy Mailbox Address. This will facilitate a discovery REGISTER update being sent to all other DiscoveryManagers
Returns
OK upon successful registration; otherwise ERROR
References MailboxOwnerHandle::post().
Referenced by MailboxLookupService::registerMailbox().
The documentation for this class was generated from the following files:
DiscoveryManager.h
DiscoveryManager.cpp