PgConnection Class Reference
Public Member Functions
virtual ~PgConnection ()
void clean ()
int checkConnectionHealth ()
int executeCommand (string &command)
int executeCommand (const char *command)
int executeCommandWithParams (const char *command, int numberParams, const char *const *paramValues, const int *paramLengths, const int *isBinary)
int beginTransaction ()
int rollbackTransaction ()
int commitTransaction ()
int initializePreparedCommand (const char *statementName, const char *sqlCommand, int numberParams, const DataManagerFieldType *paramTypeArray)
int executePreparedCommand (const char *statementName, int numberParams, const char *const *paramValues, const int *paramLengths, const int *isBinary)
int closeCommandResult ()
int getColumnCount ()
string getColumnName (int columnIndex)
int getColumnIndex (const char *columnName)
int getRowCount ()
const char * getStringValueAt (int rowIndex, int columnIndex)
short getShortValueAt (int rowIndex, int columnIndex)
int getIntValueAt (int rowIndex, int columnIndex)
bool getBooleanValueAt (int rowIndex, int columnIndex)
const char * getTimestampValueAt (int rowIndex, int columnIndex)
bool isValueNULL (int rowIndex, int columnIndex)
int getValueLength (int rowIndex, int columnIndex)
void shutdown ()
string toString ()
Static Public Member Functions
static OPMBase * initialize (int initializer)
Protected Member Functions
PgConnection ()
Additional Inherited Members
Constructor & Destructor Documentation
PgConnection::~PgConnection () [virtual]
Virtual Destructor
PgConnection::PgConnection () [protected]
Constructor
Referenced by initialize().
Member Function Documentation
int PgConnection::beginTransaction () [virtual]
Begin a transaction on this connection. Autocommit is ENABLED for all executed commands UNLESS beginTransaction has been called--that is, beginTransaction disabled autocommit until either rollbackTransaction or commitTransaction is called. Postgresql optionally supports the passing of the following isolation levels when the transaction is begun. Support for these can be added to this interface in the future: ISOLATION LEVEL { SERIALIZABLE | REPEATABLE READ | READ COMMITTED | READ UNCOMMITTED } READ WRITE | READ ONLY
Implements DbConnection .
References executeCommand().
int PgConnection::checkConnectionHealth () [virtual]
Check the health of the database connection.
Returns
OK if the connection is valid; otherwise ERROR
Implements DbConnection .
Referenced by clean().
void PgConnection::clean () [virtual]
Inherited from OPMBase. Pure Virtual method will be called before releasing the object back into the OPM pool.
Implements OPMBase .
References checkConnectionHealth(), and closeCommandResult().
int PgConnection::closeCommandResult () [virtual]
If an outstanding/open resultSet exists for this connection, then close it. return ERROR for failure; otherwise OK
Implements DbConnection .
Referenced by clean(), executeCommand(), executeCommandWithParams(), executePreparedCommand(), initializePreparedCommand(), and shutdown().
int PgConnection::commitTransaction () [virtual]
Commit the outstanding transaction on this connection
Implements DbConnection .
References executeCommand().
int PgConnection::executeCommand (string & command) [virtual]
Execute an SQL command to the database using this connection. This command can be a QUERY, UPDATE, INSERT, or DELETE operation. For Postgresql, the execution command string can contain multiple SQL statements separated by semicolons. However, this should be used with care, especially around external interfaces, since it could be vulnerable against SQL injection attacks. 'executeCommandWithParms' will only allow a single SQL statement and is not vulnerable in this way.
Returns
OK if the command was executed successfully; otherwise ERROR
Implements DbConnection .
References closeCommandResult().
Referenced by beginTransaction(), commitTransaction(), and rollbackTransaction().
int PgConnection::executeCommand (const char * command) [virtual]
Execute an SQL command to the database using this connection. This command can be a QUERY, UPDATE, INSERT, or DELETE operation. (To work with ostringstream.str().c_str()). For Postgresql, the execution command string can contain multiple SQL statements separated by semicolons. However, this should be used with care, especially around external interfaces, since it could be vulnerable against SQL injection attacks. 'executeCommandWithParms' will only allow a single SQL statement and is not vulnerable in this way.
Returns
OK if the command was executed successfully; otherwise ERROR
Implements DbConnection .
References closeCommandResult().
int PgConnection::executeCommandWithParams (const char * command, int numberParams, const char *const * paramValues, const int * paramLengths, const int * isBinary) [virtual]
Execute an SQL command to the database using this connection. This command can be a QUERY, UPDATE, INSERT or DELETE operation. For Postgresql, only a single execution command can be contained in this static string. The number of Substitution parameters and a pointer array of their values should be passed in for the server to operate on.
Parameters
numberParams number of passed in parameters in the char* array
paramValues specifies the actual values of the parameters (char* array)
paramLengths specifies the actual data lengths of binary-format parameters. It is ignored for null parameters and text-format parameters. The array pointer may be null when there are no binary parameters.
isBinary array for each param value to determine if the value is binary or textual (TRUE for binary / FALSE for text). The array pointer may be null when there are no binary parameters.
Returns
OK if the command was executed successfully; otherwise ERROR
Implements DbConnection .
References closeCommandResult().
int PgConnection::executePreparedCommand (const char * statementName, int numberParams, const char *const * paramValues, const int * paramLengths, const int * isBinary) [virtual]
Execute an SQL prepared statement command to the database using this connection. This command can be a QUERY, UPDATE, INSERT, or DELETE operation.
Parameters
statementName string name assigned to the statement when initializePreparedCommand is called.
numberParams number of passed in parameters in the char* array
paramValues specifies the actual values of the parameters (char* array)
paramLengths specifies the actual data lengths of binary-format parameters. It is ignored for null parameters and text-format parameters. The array pointer may be null when there are no binary parameters.
isBinary array for each param value to determine if the value is binary or textual (TRUE for binary / FALSE for text). The array pointer may be null when there are no binary parameters.
Returns
OK if the command was successfully executed; otherwise ERROR
Implements DbConnection .
References closeCommandResult().
bool PgConnection::getBooleanValueAt (int rowIndex, int columnIndex) [virtual]
Return the value at the specified column/row location in the current commandResult. The value returned will be a boolean type. NOTE: Use of this method requires that the developer be aware of the of the schema and result field type.
Implements DbConnection .
int PgConnection::getColumnCount () [virtual]
Return the number of columns in the current commandResult structure
Implements DbConnection .
int PgConnection::getColumnIndex (const char * columnName) [virtual]
Return the column index based on the specified column name
Implements DbConnection .
string PgConnection::getColumnName (int columnIndex) [virtual]
Return the specified column header name in the current commandResult
Implements DbConnection .
int PgConnection::getIntValueAt (int rowIndex, int columnIndex) [virtual]
Return the value at the specified column/row location in the current commandResult. The value returned will be a 4-byte integer type. NOTE: Use of this method requires that the developer be aware of the of the schema and result field type.
Implements DbConnection .
int PgConnection::getRowCount () [virtual]
Return the number of rows in the current commandResult
Implements DbConnection .
short PgConnection::getShortValueAt (int rowIndex, int columnIndex) [virtual]
Return the value at the specified column/row location in the current commandResult. The value returned will be a 2-byte short type. NOTE: Use of this method requires that the developer be aware of the of the schema and result field type.
Implements DbConnection .
const char * PgConnection::getStringValueAt (int rowIndex, int columnIndex) [virtual]
Return the value at the specified column/row location in the current commandResult. The value is returned as a string. NOTE: Use of this method requires that the developer be aware of the of the schema and result field type.
Implements DbConnection .
const char * PgConnection::getTimestampValueAt (int rowIndex, int columnIndex) [virtual]
Return the value at the specified column/row location in the current commandResult. The value returned will be a string; this is because timestamps are internally stored using 8 bytes (64 bits)!! We have to use the Postgres library to convert them back into ascii. NOTE: Use of this method requires that the developer be aware of the of the schema and result field type.
Implements DbConnection .
int PgConnection::getValueLength (int rowIndex, int columnIndex) [virtual]
Returns the actual length of a field value in bytes
Implements DbConnection .
OPMBase * PgConnection::initialize (int initializer) [static]
Inherited from OPMBase. Method will be called when the pool is created with these objects. This method bootstraps the creation of each object. THIS OVERRIDES the initialize method in OPMBASE (can't be both virtual and static)
Parameters
initializer - Initializer integer or pointer to initialization data needed by the object. In this case, we pass in a pointer to a PgInitParams struct.
Returns
Pointer to the new OPMBase object.
References PgConnection().
Referenced by ConnectionSet::performActivation().
int PgConnection::initializePreparedCommand (const char * statementName, const char * sqlCommand, int numberParams, const DataManagerFieldType * paramTypeArray) [virtual]
Setup for a prepared statement command on this connection
Parameters
statementName string name arbitrarily assigned to the statement
sqlCommand QUERY, UPDATE, INSERT, or DELETE sql operation.
numberParams number of passed in parameters in the char* array
paramTypeArray array of field types because the database cannot infer the field type formatting without it.
Returns
OK if the preparation was successful; otherwise ERROR
Implements DbConnection .
References closeCommandResult().
bool PgConnection::isValueNULL (int rowIndex, int columnIndex) [virtual]
Returns true if the field Value is NULL
Implements DbConnection .
int PgConnection::rollbackTransaction () [virtual]
Rollback a transaction on this connection
Implements DbConnection .
References executeCommand().
void PgConnection::shutdown () [virtual]
Close the socket connection to the database server
Implements DbConnection .
References closeCommandResult().
string PgConnection::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
The documentation for this class was generated from the following files:
PgConnection.h
PgConnection.cpp