DiscoveryLocalMessage Class Reference
Public Member Functions
DiscoveryLocalMessage (const MailboxAddress &sourceAddress, DiscoveryLocalOperationType operation, const MailboxAddress &discoveryAddress)
DiscoveryLocalMessage (const DiscoveryLocalMessage &rhs)
virtual ~DiscoveryLocalMessage ()
unsigned short getMessageId () const
DiscoveryLocalOperationType getOperationType () const
const MailboxAddress & getDiscoveryAddress () const
string toString ()
Additional Inherited Members
Constructor & Destructor Documentation
DiscoveryLocalMessage::DiscoveryLocalMessage (const MailboxAddress & sourceAddress, DiscoveryLocalOperationType operation, const MailboxAddress & discoveryAddress)
Constructor
Parameters
sourceAddress Mailbox Address for this DiscoveryManager (on this node)
operation Type of discovery operation (register, deregister, display, etc.)
discoveryAddress Mailbox Address that is being registered/deregistered
DiscoveryLocalMessage::DiscoveryLocalMessage (const DiscoveryLocalMessage & rhs)
Copy Constructor
DiscoveryLocalMessage::~DiscoveryLocalMessage () [virtual]
Virtual Destructor
Member Function Documentation
const MailboxAddress & DiscoveryLocalMessage::getDiscoveryAddress () const
Returns the Discovery Address which is being registered/deregistered
Referenced by DiscoveryManager::processMailbox().
unsigned short DiscoveryLocalMessage::getMessageId () const [virtual]
Returns the Message Id
Implements MessageBase .
DiscoveryLocalOperationType DiscoveryLocalMessage::getOperationType () const
Returns the Discovery Operation type
Referenced by DiscoveryManager::processMailbox().
string DiscoveryLocalMessage::toString () [virtual]
String'ized debugging method
Returns
string representation of the contents of this object
Implements MessageBase .
References MessageBase::sourceAddress_, and MailboxAddress::toString().
Referenced by DiscoveryManager::processMailbox().
The documentation for this class was generated from the following files:
DiscoveryLocalMessage.h
DiscoveryLocalMessage.cpp