OPMLinkedList Class Reference
#include <OPMLinkedList.h>
Public Member Functions
OPMLinkedList ()
virtual ~OPMLinkedList ()
OPMBase * removeFirst ()
OPMBase * remove (OPMBase *object)
void insertFirst (OPMBase *object)
void insertLast (OPMBase *object)
int getListSize ()
bool isEmpty ()
bool containsObject (OPMBase *object)
void deleteListContents ()
string toString ()
Detailed Description
This utility class implements a doubly linked list with both a head and tail pointers for storing OPMBase objects. All list operations are done by manipulating pointers since OPMBase stores the references for the 'NEXT' and 'PREV' pointers.
This class is currently NOT THREAD SAFE.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
OPMLinkedList::OPMLinkedList ()
Constructor
OPMLinkedList::~OPMLinkedList () [virtual]
Virtual Destructor
Member Function Documentation
bool OPMLinkedList::containsObject (OPMBase * object)
Walk the linked list and check to see if the object is a member
References OPMBase::getNext(), and OPMBase::isNextNull().
Referenced by ObjectPool::containsObject().
void OPMLinkedList::deleteListContents ()
Delete the contents of the list - does not delete the list objects, but rather deletes the list references.
References OPMBase::getNext(), OPMBase::isNextNull(), OPMBase::setNext(), and OPMBase::setPrev().
Referenced by ObjectPool::~ObjectPool().
int OPMLinkedList::getListSize ()
Return the size of the List
void OPMLinkedList::insertFirst (OPMBase * object)
Insert an OPMBase object at the Head (First) of the Linked List
Parameters
object Pointer to OPMBase object to insert
References OPMBase::setPrev().
Referenced by ObjectPool::ObjectPool(), ObjectPool::release(), and ObjectPool::reserve().
void OPMLinkedList::insertLast (OPMBase * object)
Insert an OPMBase object at the Tail (Last) of the Linked List
Parameters
object Pointer to OPMBase object to insert
References OPMBase::setNext().
bool OPMLinkedList::isEmpty ()
Check if the list is currently empty
Referenced by ObjectPool::isEmpty(), and ObjectPool::reserve().
OPMBase * OPMLinkedList::remove (OPMBase * object)
Remove a specified OPMBase object from the Linked List by manipulating the previous and next pointers and return the object back to the user.
Returns
OPMBase pointer to object or null if the List is empty
References OPMBase::getNext(), OPMBase::getPrev(), OPMBase::setNext(), and OPMBase::setPrev().
Referenced by ObjectPool::release().
OPMBase * OPMLinkedList::removeFirst ()
Remove an OPMBase object from the Head (First) of the Linked List and return the object back to the user.
Returns
OPMBase pointer to object or null if the List is empty
References OPMBase::getNext(), and OPMBase::setPrev().
Referenced by ObjectPool::release(), and ObjectPool::reserve().
string OPMLinkedList::toString ()
Display the contents of the list
References OPMBase::getNext(), OPMBase::isNextNull(), and OPMBase::toString().
The documentation for this class was generated from the following files:
OPMLinkedList.h
OPMLinkedList.cpp