DistributedMailbox Class Reference
Public Types
typedef map< ACE_HANDLE, ACE_SOCK_Stream * > ClientConnectorMap
Public Member Functions
virtual bool rename (const MailboxAddress &newRemoteAddress)
virtual int activate (MailboxOwnerHandle *mailboxOwnerHandle)
virtual int deactivate (MailboxOwnerHandle *mailboxOwnerHandle)
MailboxAddress & getMailboxAddress ()
string toString ()
Static Public Member Functions
static MailboxOwnerHandle * createMailbox (const MailboxAddress &remoteAddress)
Protected Member Functions
DistributedMailbox (const MailboxAddress &distributedAddress)
virtual ~DistributedMailbox ()
Additional Inherited Members
Member Typedef Documentation
typedef map<ACE_HANDLE, ACE_SOCK_Stream*> DistributedMailbox::ClientConnectorMap
Create a map for storing ACE_HANDLEs and their associated ACE_SOCK_Stream objects. Each map entry corresponds to a single client 'connector' connection to this distributed mailbox.
Constructor & Destructor Documentation
DistributedMailbox::DistributedMailbox (const MailboxAddress & distributedAddress) [protected]
Constructor - protected so that applications cannot create their own mailboxes and must use the static createMailbox() method
References DistributedMailbox().
Referenced by DistributedMailbox().
DistributedMailbox::~DistributedMailbox () [protected], [virtual]
Virtual Destructor. Protected since this is a reference counted object.
References MailboxBase::isShuttingDown_.
Member Function Documentation
int DistributedMailbox::activate (MailboxOwnerHandle * mailboxOwnerHandle) [virtual]
Activate the mailbox. For security, one must possess an Owner Handle in order to activate the mailbox and register it with the Lookup Service.
Reimplemented from LocalMailbox .
References LocalMailbox::activate(), LocalMailbox::deactivate(), MailboxAddress::inetAddress, and MailboxBase::isActive().
MailboxOwnerHandle * DistributedMailbox::createMailbox (const MailboxAddress & remoteAddress) [static]
Allows applications to create a mailbox and get a handle to it.
Since we do not want applications to have direct access to a mailbox object this method is provided. Applications that create mailboxes use this method to get a handle to their mailbox rather than have direct access. The handle returned is a owner handle which has all the privileges of the actual mailbox (getMessage/post etc). This method creates the mailbox, activates it (which in turn registers it with the lookup service) and then creates an owner handle, acquires it and then returns that handle. Both the mailbox and the returned handle are created on the heap.
References MessageBuffer::areContentsProcessed(), MessageBuffer::clearBuffer(), ThreadManager::createThread(), MailboxBase::debugValue_, MessageBuffer::getBuffer(), MessageBase::getMessageId(), MessageBase::getSourceAddress(), MailboxBase::incrementReceivedCount(), MailboxAddress::inetAddress, MailboxAddress::locationType, LocalMailbox::post(), MessageFactory::recreateMessageFromBuffer(), MailboxBase::selectReactor_, MessageBuffer::setInsertPosition(), MessageBase::setPriority(), LocalMailbox::startReactor(), and MessageBase::toString().
Referenced by FaultManager::processMailbox(), and ResourceMonitor::toString().
int DistributedMailbox::deactivate (MailboxOwnerHandle * mailboxOwnerHandle) [virtual]
Deactivate the mailbox. For security, one must possess an Owner Handle in order to deactivate the mailbox and deregister it with the Lookup Service.
Reimplemented from LocalMailbox .
References LocalMailbox::deactivate().
MailboxAddress & DistributedMailbox::getMailboxAddress () [virtual]
Return the mailbox distributed address
Implements MailboxBase .
References MailboxBase::isShuttingDown_.
bool DistributedMailbox::rename (const MailboxAddress & newRemoteAddress) [virtual]
Method to allow application to rename a mailbox's remote address.
TBD: What are the redundancy implications and usage here??
Reimplemented from MailboxBase .
string DistributedMailbox::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
The documentation for this class was generated from the following files:
DistributedMailbox.h
DistributedMailbox.cpp