Faults Class Reference
#include <Faults.h>
Public Member Functions
~Faults ()
int initialize ()
Static Public Member Functions
static void raiseAlarm (const char *neid, AlarmCodeType alarmcode, ManagedObjectType managedObject, unsigned int managedObjectInstance, unsigned int pid)
static void clearAlarm (const char *neid, AlarmCodeType alarmcode, ManagedObjectType managedObject, unsigned int managedObjectInstance, unsigned int pid)
static void reportEvent (EventCodeType eventcode, ManagedObjectType managedObject, unsigned int managedObjectInstance, unsigned int pid)
static Faults * getInstance ()
Detailed Description
Faults provides the main mechanism and API to the developers for raising and clearing alarms and generating informational event reports.
Developers use the Fault MACROS to issue alarms. These macros hide the API mechanism for enqueuing the alarms for output. In this way, the fault manager subsystem can be transparently modified in the future to include additional data without impact to the application developers.
The key goal for implementing and maintaining this fault interface is to allow applications to issue alarms with the MINIMAL amount of buffer copying and alarm processing as possible.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
Faults::~Faults ()
Destructor
Member Function Documentation
void Faults::clearAlarm (const char * neid, AlarmCodeType alarmcode, ManagedObjectType managedObject, unsigned int managedObjectInstance, unsigned int pid) [static]
Method to handle enqueuing/clearing of the alarms. Supports being able to clear Alarms on behalf of another NEID/node.
References FaultMessage::alarmCode, FaultMessage::alarmSeverity, FaultSMQueue::enqueueAlarm(), FaultMessage::managedObject, FaultMessage::managedObjectInstance, FaultMessage::neid, FaultMessage::neidPI, FaultMessage::pid, and FaultMessage::timeStamp.
Faults * Faults::getInstance () [static]
Return a singleton instance
Referenced by ResourceMonitor::toString().
int Faults::initialize ()
Perform initialization of shared memory queue, etc.
Returns
OK on success; otherwise ERROR
References FaultSMQueue::setupQueue().
Referenced by ResourceMonitor::toString().
void Faults::raiseAlarm (const char * neid, AlarmCodeType alarmcode, ManagedObjectType managedObject, unsigned int managedObjectInstance, unsigned int pid) [static]
Method to handle enqueuing/raising of the alarms. Supports being able to raise Alarms on behalf of another NEID/node.
References FaultMessage::alarmCode, FaultMessage::alarmSeverity, FaultSMQueue::enqueueAlarm(), FaultMessage::managedObject, FaultMessage::managedObjectInstance, FaultMessage::neid, FaultMessage::neidPI, FaultMessage::pid, and FaultMessage::timeStamp.
void Faults::reportEvent (EventCodeType eventcode, ManagedObjectType managedObject, unsigned int managedObjectInstance, unsigned int pid) [static]
Method to handle generation of informational event reports.
References FaultMessage::alarmSeverity, FaultSMQueue::enqueueAlarm(), FaultMessage::eventCode, FaultMessage::managedObject, FaultMessage::managedObjectInstance, FaultMessage::pid, and FaultMessage::timeStamp.
The documentation for this class was generated from the following files:
Faults.h
Faults.cpp