LoggerSMQueue Class Reference
#include <LoggerSMQueue.h>
Public Types
typedef UnboundedSMQueue< LogMessage > LOGGERSMQUEUE
Public Member Functions
LoggerSMQueue (const char *queueName, const char *coordinatingMutexName)
virtual ~LoggerSMQueue ()
int setupQueue ()
int enqueueLog (LogMessage &message)
int dequeueLog (LogMessage &message)
void clearQueue ()
bool isEmpty ()
string toString ()
Detailed Description
LoggerSMQueue sets up an Unbounded Queue in Shared Memory for the purpose of exchanging LoggerMessageType messages between processes and the LoggerProcessor which controls the output flow of logs to log files.
This shared memory queue uses the Position Independent Malloc/Allocation factory in ACE, and it handles queue growth using the automatic OS exception handling facilities to trap SIGSEGV and perform an ACE::remap.
Author
Stephen Horton
Revision
1
Member Typedef Documentation
typedef UnboundedSMQueue<LogMessage> LoggerSMQueue::LOGGERSMQUEUE
Shared Memory Queue type for LogMessages
Constructor & Destructor Documentation
LoggerSMQueue::LoggerSMQueue (const char * queueName, const char * coordinatingMutexName)
Constructor
LoggerSMQueue::~LoggerSMQueue () [virtual]
Virtual Destructor
Member Function Documentation
void LoggerSMQueue::clearQueue ()
Clears the contents (logs) of the shared memory queue
References UnboundedSMQueue< T >::delete_nodes().
int LoggerSMQueue::dequeueLog (LogMessage & message)
Dequeue a LogMessage from the shared memory queue. The calling code is responsible for allocating the LogMessage and passing it in as a reference to be populated.
Returns
OK on success; otherwise ERROR
References UnboundedSMQueue< T >::dequeue_head(), and UnboundedSMQueue< T >::is_empty().
Referenced by LogProcessor::catchShutdownSignal(), and LogProcessor::processLogs().
int LoggerSMQueue::enqueueLog (LogMessage & message)
Enqueue a LogMessage to the shared memory queue
Returns
OK on success; otherwise ERROR
References UnboundedSMQueue< T >::enqueue_tail().
bool LoggerSMQueue::isEmpty ()
Returns true if the queue is empty
References UnboundedSMQueue< T >::is_empty().
Referenced by LogProcessor::catchShutdownSignal(), and LogProcessor::processLogs().
int LoggerSMQueue::setupQueue ()
Create the (or get a reference to an already created) queue
Returns
OK on success; otherwise ERROR
References SharedMemoryManager::getAllocator().
Referenced by LogProcessor::initialize().
string LoggerSMQueue::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
The documentation for this class was generated from the following files:
LoggerSMQueue.h
LoggerSMQueue.cpp