CliMenuStateActions Class Reference
#include <CliMenuStateActions.h>
Public Member Functions
CliMenuStateActions ()
virtual ~CliMenuStateActions ()
void initialize (session::Session_I_ptr session_I_ptr)
void sendUnlock ()
void sendLock ()
Additional Inherited Members
Detailed Description
CliMenuStateActions contains static handler methods for the State Transition Command Menu Items.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
CliMenuStateActions::CliMenuStateActions ()
Constructor
CliMenuStateActions::~CliMenuStateActions () [virtual]
Virtual Destructor
Member Function Documentation
void CliMenuStateActions::initialize (session::Session_I_ptr session_I_ptr)
Initialization Method
Referenced by CliMenuController::initialize().
void CliMenuStateActions::sendLock ()
Lock State Transition Command
Referenced by CliMenuController::initialize().
void CliMenuStateActions::sendUnlock ()
Unlock State Transition Command
Referenced by CliMenuController::initialize().
The documentation for this class was generated from the following files:
CliMenuStateActions.h
CliMenuStateActions.cpp