ThreadManager Class Reference
#include <ThreadManager.h>
Public Member Functions
virtual ~ThreadManager ()
void apply (void)
Static Public Member Functions
static ACE_thread_t createThread (ACE_THR_FUNC function, void *functionArgs, const char *threadName, bool shouldRestart, long threadFlags=THR_NEW_LWP|THR_JOINABLE|THR_SCHED_DEFAULT, long priority=ACE_DEFAULT_THREAD_PRIORITY, int threadGroup=-1, size_t stackSize=0)
static ACE_thread_t * createThreadPool (size_t Nthreads, ACE_THR_FUNC function, void *functionArgs, const char *threadName, bool shouldRestart, long threadFlags=THR_NEW_LWP|THR_JOINABLE|THR_SCHED_DEFAULT, long priority=ACE_DEFAULT_THREAD_PRIORITY, int threadGroup=-1, size_t stackSize=0)
Detailed Description
ThreadManager wraps the ACE Thread mechanism in order to provide Thread monitoring, Thread naming, and death detection and restart capabilities.
The main developer interface is the createThread() method, which returns an OS-assigned unique thread Id. This thread id can be stored by the application and used with the ACE_Thread_Manager class for suspending, resuming, waiting on, or managing groups of threads (see ace/Thread_Manager.h).
In the case of createThreadPool(), a pointer to an array of ACE_Thread_t Thread Ids is returned--one for each of the N threads.
In the event of a thread death/restart, we cannot just re-call createThread from the space of the ACE_At_Exit handler, as the ACE_Thread_Manager is locked (we are inside the lock), and we will need to lock it to call 'spawn', and that would result in a DEADLOCK. Therefore, our strategy is to post the thread details (threadparameters) to a static map, and have an independent thread periodically every second or so check to see if the map contains any threads that need restarting. Any other strategies for notification and restart of the thread are very complex!
ALSO NOTE:!! Upon restart, the thread Id originally made available to the application for this thread will be invalid. We can (IN THE FUTURE) allow the application developer to pass in a call back function (with unsigned long parameter) that can be called and passed the new Thread Id.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
ThreadManager::~ThreadManager () [virtual]
Virtual Destructor
Member Function Documentation
void ThreadManager::apply (void)
Inheritied from ACE_At_Thread_Exit. Gets called upon thread death/exit.
ACE_thread_t ThreadManager::createThread (ACE_THR_FUNC function, void * functionArgs, const char * threadName, bool shouldRestart, long threadFlags = THR_NEW_LWP | THR_JOINABLE | THR_SCHED_DEFAULT, long priority = ACE_DEFAULT_THREAD_PRIORITY, int threadGroup = -1, size_t stackSize = 0) [static]
Main Thread creation API
Parameters
function Static C++ method or C-style function to start the new thread with
functionArgs Array of arguments to pass to the function as parameters
threadName String identifier that should be unique to each thread
shouldRestart 'true' if the thread should be restarted upon exit;otherwise, it will be allowed to terminate
threadFlags define the characteristics of the thread
priority is the relative priority of the new thread (from 1 to 127). Specifying priority other than the default is Discouraged, and should only be used RARELY!
threadGroup can be provided if thread pooling or grouping is desired.
stackSize specifies the size of the stack allocated for this thread
Returns
the unique thread Id upon success; otherwise 0 upon failure. In Linux, this is an unsigned long (see /usr/include/bits/pthread_types.h), so cannot use ERROR
Referenced by LocalSMMailbox::activate(), DistributedMailbox::createMailbox(), LocalSMMailbox::createMailbox(), GroupMailbox::createMailbox(), LocalMailbox::createMailbox(), createThreadPool(), ResourceMonitor::initialize(), ProcessManager::initialize(), FaultManager::initialize(), and MailboxLookupService::initializeDiscoveryManager().
ACE_thread_t * ThreadManager::createThreadPool (size_t Nthreads, ACE_THR_FUNC function, void * functionArgs, const char * threadName, bool shouldRestart, long threadFlags = THR_NEW_LWP | THR_JOINABLE | THR_SCHED_DEFAULT, long priority = ACE_DEFAULT_THREAD_PRIORITY, int threadGroup = -1, size_t stackSize = 0) [static]
Thread Pool creation API
Parameters
Nthreads Number of threads to create in the pool
function Static C++ method or C-style function to start the new thread with
functionArgs Array of arguments to pass to the function as parameters
threadName String identifier that should be unique to each thread
shouldRestart 'true' if the thread should be restarted upon exit;otherwise, it will be allowed to terminate
threadFlags define the characteristics of the thread
priority is the relative priority of the new thread (from 1 to 127). Specifying priority other than the default is Discouraged, and should only be used RARELY!
threadGroup can be provided if thread pooling or grouping is desired.
stackSize specifies the size of the stack allocated for this thread
Returns
Pointer array of unique thread Ids upon success; otherwise 0 upon failure. This array of ACE_Thread_t thread ids is allocated on the heap, so ownership is deferred to the application owner. In Linux, these values are unsigned longs (see /usr/include/bits/pthread_types.h), so cannot use ERROR
References createThread().
Referenced by MailboxProcessor::processMailbox().
The documentation for this class was generated from the following files:
ThreadManager.h
ThreadManager.cpp