MailboxBase Class Reference
Public Member Functions
virtual int activate (MailboxOwnerHandle *mailboxOwnerHandle)
virtual int deactivate (MailboxOwnerHandle *mailboxOwnerHandle)
virtual const ACE_Time_Value & getPostDefaultTimeout ()=0
virtual int post (MessageBase *messagePtr, const ACE_Time_Value *timeout=&ACE_Time_Value::zero)=0
virtual MessageBase * getMessage (unsigned short timeoutValue=0)=0
virtual MessageBase * getMessageNonBlocking ()=0
virtual int acquire ()
virtual void release ()
virtual int getDebugValue ()=0
virtual void setDebugValue (int debugValue)=0
virtual MailboxAddress & getMailboxAddress ()=0
unsigned int getSentCount ()
unsigned int getReceivedCount ()
virtual bool rename (const MailboxAddress &newRemoteAddress)
int handle_timeout (const ACE_Time_Value &tv, const void *argument)
unsigned int getActiveTimers ()
void incrementActiveTimers ()
void decrementActiveTimers ()
ACE_Reactor * getReactor ()
bool isProxy ()
unsigned int isActive ()
string toString ()
Protected Member Functions
MailboxBase ()
virtual ~MailboxBase ()
void setActive (unsigned int active)
void incrementReceivedCount ()
void incrementSentCount ()
Protected Attributes
int debugValue_
bool isProxy_
ACE_Reactor * selectReactor_
Static Protected Attributes
static ACE_Atomic_Op< ACE_Thread_Mutex, unsigned int > isShuttingDown_ = FALSE
Constructor & Destructor Documentation
MailboxBase::MailboxBase () [protected]
Constructor
MailboxBase::~MailboxBase () [protected], [virtual]
Virtual Destructor. Protected since this is a reference counted object.
Member Function Documentation
int MailboxBase::acquire () [virtual]
Acquire a handle to this mailbox. Here we do reference counting. We implement a reference count mechanism to keep track of mailbox objects. When an application wants to access a mailbox it acquires a handle to the mailbox which increments the reference count for the mailbox. When the application is done with a mailbox (for a transient usage) it releases the mailbox which decrements the reference count. When the reference count returns to 0 the mailbox deletes itself.
Returns
ERROR if failure; otherwise OK
Referenced by MailboxHandle::MailboxHandle(), and MailboxOwnerHandle::MailboxOwnerHandle().
int MailboxBase::activate (MailboxOwnerHandle * mailboxOwnerHandle) [virtual]
This method activates the mailbox. A mailbox is NOT active on creation. Making it virtual allows sub-classes to refine this behavior. For security, one must possess an Owner Handle to the mailbox in order to activate it.
Returns
ERROR on failure, OK on success
Reimplemented in GroupMailbox , GroupMailboxProxy , DistributedMailbox , LocalSMMailbox , LocalSMMailboxProxy , DistributedMailboxProxy , and LocalMailbox .
Referenced by MailboxOwnerHandle::activate().
int MailboxBase::deactivate (MailboxOwnerHandle * mailboxOwnerHandle) [virtual]
This method deactivates the mailbox. Making it virtual allows sub-classes to refine this behavior. For security, one must possess an Owner Handle to the mailbox in order to deactivate it.
Returns
ERROR on failure, OK on success
Reimplemented in GroupMailbox , GroupMailboxProxy , DistributedMailbox , LocalSMMailbox , LocalSMMailboxProxy , DistributedMailboxProxy , and LocalMailbox .
Referenced by MailboxOwnerHandle::deactivate(), MailboxLookupService::registerMailbox(), and release().
void MailboxBase::decrementActiveTimers ()
Decrement Active Timer count
Referenced by MailboxOwnerHandle::cancelTimer(), and handle_timeout().
unsigned int MailboxBase::getActiveTimers ()
Return number of active, outstanding Timers
virtual int MailboxBase::getDebugValue () [pure virtual]
Return the debug flag
Implemented in GroupMailboxProxy , LocalMailbox , LocalSMMailboxProxy , and DistributedMailboxProxy .
Referenced by MailboxHandle::getDebugValue(), and MailboxOwnerHandle::getDebugValue().
virtual MailboxAddress& MailboxBase::getMailboxAddress () [pure virtual]
Return the Mailbox address
Implemented in GroupMailbox , GroupMailboxProxy , LocalMailbox , LocalSMMailboxProxy , DistributedMailbox , DistributedMailboxProxy , and LocalSMMailbox .
Referenced by MailboxHandle::getMailboxAddress(), and MailboxOwnerHandle::getMailboxAddress().
virtual MessageBase* MailboxBase::getMessage (unsigned short timeoutValue = 0) [pure virtual]
Will block until an message is available. May return NULL if no message available (if mailbox deactivated).
Implemented in LocalMailbox .
Referenced by MailboxOwnerHandle::getMessage().
virtual MessageBase* MailboxBase::getMessageNonBlocking () [pure virtual]
Will not block until an message is available.
If the application has a need to do non-blocking calls to get (or check to see if) messages pending on the mailbox queue, then the application needs to implement this call -instead- of calling MailboxProcess::processMailbox(). If this is indeed the case, then the application will either need to implement the case switching on the Message Type -or- implement the find for the MessageHandlerList (functor lookup).
Returns
NULL if no message available (and if mailbox deactivated).
Implemented in LocalMailbox .
Referenced by MailboxOwnerHandle::getMessageNonBlocking().
virtual const ACE_Time_Value& MailboxBase::getPostDefaultTimeout () [pure virtual]
Subclass implementations should return the appropriate default timeout for the post()
Implemented in GroupMailboxProxy , LocalSMMailboxProxy , DistributedMailboxProxy , and LocalMailbox .
ACE_Reactor * MailboxBase::getReactor ()
Return pointer to the select reactor used for event dispatch
References selectReactor_.
Referenced by MailboxOwnerHandle::cancelTimer(), MailboxOwnerHandle::resetTimerInterval(), and MailboxOwnerHandle::scheduleTimer().
unsigned int MailboxBase::getReceivedCount ()
Return the received message counter value
unsigned int MailboxBase::getSentCount ()
Return the sent message counter value
Referenced by MailboxHandle::getSentCount(), and MailboxOwnerHandle::getSentCount().
int MailboxBase::handle_timeout (const ACE_Time_Value & tv, const void * argument)
Overriden ACE_Event_Handler method.
Method to handle timer expirations from the ACE reactor. This is base class functionality since all Mailboxes should have Timer capability.
References decrementActiveTimers(), post(), and TimerMessage::setExpirationTime().
void MailboxBase::incrementActiveTimers ()
Increment Active Timer count
Referenced by MailboxOwnerHandle::scheduleTimer().
void MailboxBase::incrementReceivedCount () [protected]
Increments the Mailbox's received message count
Referenced by DistributedMailbox::createMailbox(), GroupMailbox::createMailbox(), and LocalSMMailbox::getMailboxAddress().
void MailboxBase::incrementSentCount () [protected]
Increments the Mailbox's sent message count
Referenced by DistributedMailboxProxy::post(), LocalSMMailboxProxy::post(), and GroupMailboxProxy::post().
unsigned int MailboxBase::isActive ()
Indicates whether the Mailbox has been activated or not
Returns
TRUE or FALSE
Referenced by LocalMailbox::activate(), DistributedMailboxProxy::activate(), LocalSMMailboxProxy::activate(), LocalSMMailbox::activate(), DistributedMailbox::activate(), GroupMailboxProxy::activate(), GroupMailbox::activate(), LocalMailbox::deactivate(), DistributedMailboxProxy::deactivate(), LocalSMMailboxProxy::deactivate(), GroupMailboxProxy::deactivate(), LocalSMMailbox::getMailboxAddress(), LocalMailbox::getMessage(), LocalMailbox::getMessageNonBlocking(), DistributedMailboxProxy::post(), LocalSMMailboxProxy::post(), LocalMailbox::post(), GroupMailboxProxy::post(), and release().
bool MailboxBase::isProxy ()
Indicate whether this mailbox is a Proxy side mailbox for posting messages
References isProxy_.
Referenced by MailboxHandle::isProxy(), MailboxOwnerHandle::isProxy(), and MailboxLookupService::registerMailbox().
virtual int MailboxBase::post (MessageBase * messagePtr, const ACE_Time_Value * timeout = &ACE_Time_Value::zero) [pure virtual]
Post a message to this mailbox. Subclass implementations should examine the `active_` state.
Returns
ERROR for an error, OK otherwise.
Implemented in GroupMailboxProxy , LocalMailbox , LocalSMMailboxProxy , and DistributedMailboxProxy .
Referenced by handle_timeout(), MailboxHandle::post(), and MailboxOwnerHandle::post().
void MailboxBase::release () [virtual]
Release the handle for this mailbox. Here we do reference counting. When the referenceCount for this Mailbox returns to zero, the Mailbox will de-register itself with the Mailbox Lookup Service and then delete itself.
References deactivate(), MailboxLookupService::deregisterMailbox(), and isActive().
Referenced by MailboxHandle::~MailboxHandle(), and MailboxOwnerHandle::~MailboxOwnerHandle().
bool MailboxBase::rename (const MailboxAddress & newRemoteAddress) [virtual]
Rename the Mailbox address
Reimplemented in GroupMailbox , and DistributedMailbox .
Referenced by MailboxOwnerHandle::rename().
void MailboxBase::setActive (unsigned int active) [protected]
Sets the activate state flag
Referenced by LocalMailbox::activate(), DistributedMailboxProxy::activate(), LocalSMMailboxProxy::activate(), GroupMailboxProxy::activate(), LocalMailbox::deactivate(), DistributedMailboxProxy::deactivate(), LocalSMMailboxProxy::deactivate(), and GroupMailboxProxy::deactivate().
virtual void MailboxBase::setDebugValue (int debugValue) [pure virtual]
Set the debug flag
Implemented in GroupMailboxProxy , LocalMailbox , LocalSMMailboxProxy , and DistributedMailboxProxy .
Referenced by MailboxHandle::setDebugValue(), and MailboxOwnerHandle::setDebugValue().
string MailboxBase::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
Referenced by LocalMailbox::post().
Member Data Documentation
int MailboxBase::debugValue_ [protected]
Debug Flag
Referenced by DistributedMailbox::createMailbox(), GroupMailbox::createMailbox(), DistributedMailboxProxy::getDebugValue(), LocalSMMailboxProxy::getDebugValue(), LocalMailbox::getDebugValue(), GroupMailboxProxy::getDebugValue(), LocalSMMailbox::getMailboxAddress(), LocalSMMailbox::LocalSMMailbox(), DistributedMailboxProxy::post(), LocalSMMailboxProxy::post(), LocalMailbox::post(), GroupMailboxProxy::post(), DistributedMailboxProxy::setDebugValue(), LocalSMMailboxProxy::setDebugValue(), LocalMailbox::setDebugValue(), and GroupMailboxProxy::setDebugValue().
bool MailboxBase::isProxy_ [protected]
Flag to indicate whether this mailbox is a Proxy side mailbox for posting messages
Referenced by DistributedMailboxProxy::DistributedMailboxProxy(), GroupMailboxProxy::GroupMailboxProxy(), isProxy(), and LocalSMMailboxProxy::LocalSMMailboxProxy().
ACE_Atomic_Op< ACE_Thread_Mutex, unsigned int > MailboxBase::isShuttingDown_ = FALSE [static], [protected]
Flag to indicate that the Mailbox is being shutdown. Set in the Mailbox's destructor for loops to see
Referenced by DistributedMailbox::getMailboxAddress(), GroupMailbox::getMailboxAddress(), LocalMailbox::startReactor(), DistributedMailbox::~DistributedMailbox(), DistributedMailboxProxy::~DistributedMailboxProxy(), GroupMailbox::~GroupMailbox(), GroupMailboxProxy::~GroupMailboxProxy(), LocalMailbox::~LocalMailbox(), LocalSMMailbox::~LocalSMMailbox(), and LocalSMMailboxProxy::~LocalSMMailboxProxy().
ACE_Reactor* MailboxBase::selectReactor_ [protected]
ACE_Select_Reactor used for event dispatch. This only gets instantiated by non-proxy mailboxes
Referenced by DistributedMailbox::createMailbox(), LocalSMMailbox::createMailbox(), GroupMailbox::createMailbox(), LocalMailbox::createMailbox(), getReactor(), and LocalMailbox::~LocalMailbox().
The documentation for this class was generated from the following files:
MailboxBase.h
MailboxBase.cpp