ProcessController Class Reference
#include <ProcessController.h>
Public Member Functions
ProcessController ()
virtual ~ProcessController ()
int init (int argc, ACE_TCHAR *argv[])
int fini ()
int info (ACE_TCHAR **, size_t) const
int suspend ()
int resume ()
int restartProcess ()
string toString ()
Detailed Description
The purpose of this class is to create an ACE_Service_Object subclass to allow dynamic loading/unloading of our application processes. This class acts as a bridge pattern between the Service Configurator(Service Object) and the ACE Process_Manager
Each instance of this class corresponds to a configured Service/Process in the system.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
ProcessController::ProcessController ()
Constructor
ProcessController::~ProcessController () [virtual]
Virtual Destructor
Member Function Documentation
int ProcessController::fini ()
Inherited from ACE_Service_Object. Perform service shutdown; here we destroy the process associated with this instance
References ProcessDeathHandler::setTerminatedFlag().
int ProcessController::info (ACE_TCHAR ** infoString, size_t size) const
Inherited from ACE_Service_Object. Return service descriptive information and state data
int ProcessController::init (int argc, ACE_TCHAR * argv[])
Inherited from ACE_Service_Object. Perform service startup; here we will start the process which is passed to this instance in these parameter arguments (which originate from svc.conf)
References restartProcess(), ProcessDeathHandler::setProcessIdentity(), and ProcessDeathHandler::setTerminatedFlag().
int ProcessController::restartProcess ()
Attempt a process restart. This method is called from the Process Death Handler.
References ProcessDeathHandler::setProcessIdentity().
Referenced by init().
int ProcessController::resume ()
Inherited from ACE_Service_Object. Resume activity for this Service/Process
int ProcessController::suspend ()
Inherited from ACE_Service_Object. Suspend activity for this Service/Process
string ProcessController::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
The documentation for this class was generated from the following files:
ProcessController.h
ProcessController.cpp