LocalMailbox Class Reference
Public Member Functions
virtual int activate (MailboxOwnerHandle *mailboxOwnerHandle)
virtual int deactivate (MailboxOwnerHandle *mailboxOwnerHandle)
virtual const ACE_Time_Value & getPostDefaultTimeout ()
virtual int post (MessageBase *messagePtr, const ACE_Time_Value *timeout=&ACE_Time_Value::zero)
virtual MessageBase * getMessage (unsigned short timeoutValue=0)
virtual MessageBase * getMessageNonBlocking ()
virtual int getDebugValue ()
virtual void setDebugValue (int debugValue)
MailboxAddress & getMailboxAddress ()
Static Public Member Functions
static MailboxOwnerHandle * createMailbox (const MailboxAddress &localAddress)
Protected Member Functions
LocalMailbox (const MailboxAddress &localAddress)
virtual ~LocalMailbox ()
Static Protected Member Functions
static void startReactor (void *arg)
Protected Attributes
MailboxAddress localAddress_
ACE_Message_Queue< ACE_MT_SYNCH > messageQueue_
Additional Inherited Members
Constructor & Destructor Documentation
LocalMailbox::LocalMailbox (const MailboxAddress & localAddress) [protected]
Default Constructor - protected so that applications cannot create their own mailboxes and must use the static createMailbox() method
References OPM::createPool(), MessageBlockWrapper::initialize(), and LocalMailbox().
Referenced by LocalMailbox().
LocalMailbox::~LocalMailbox () [protected], [virtual]
Virtual Destructor. Protected since this is a reference counted object
References MessageBase::deleteMessage(), MessageBase::isPoolable(), MailboxBase::isShuttingDown_, messageQueue_, and MailboxBase::selectReactor_.
Member Function Documentation
int LocalMailbox::activate (MailboxOwnerHandle * mailboxOwnerHandle) [virtual]
Activate the mailbox. For security, one must possess an Owner Handle to the mailbox in order to activate it and register it with the Lookup Service.
Reimplemented from MailboxBase .
Reimplemented in GroupMailbox , DistributedMailbox , and LocalSMMailbox .
References MailboxBase::isActive(), messageQueue_, MailboxLookupService::registerMailbox(), and MailboxBase::setActive().
Referenced by LocalSMMailbox::activate(), DistributedMailbox::activate(), GroupMailbox::activate(), and createMailbox().
MailboxOwnerHandle * LocalMailbox::createMailbox (const MailboxAddress & localAddress) [static]
Allows applications to create a mailbox and get a handle to it.
Since we do not want applications to have direct access to a mailbox object this method is provided. Applications that create mailboxes use this method to get a handle to their mailbox rather than have direct access. The handle returned is a owner handle which has all the privileges of the actual mailbox (getMessage/post etc). This method creates the mailbox, activates it (which in turn registers it with the lookup service) and then creates an owner handle, acquires it and then returns that handle. Both the mailbox and the returned handle are created on the heap.
References activate(), ThreadManager::createThread(), MailboxAddress::defaultUnknownInetAddress_, MailboxAddress::inetAddress, MailboxAddress::locationType, MailboxAddress::mailboxName, MailboxAddress::mailboxType, MailboxAddress::neid, MailboxAddress::redundantRole, MailboxBase::selectReactor_, MailboxAddress::shelfNumber, MailboxAddress::slotNumber, and startReactor().
Referenced by ProcessManager::toString().
int LocalMailbox::deactivate (MailboxOwnerHandle * mailboxOwnerHandle) [virtual]
Deactivate the mailbox. For security, one must possess an Owner Handle to the mailbox in order to deactivate it and deregister it with the Lookup Service.
Reimplemented from MailboxBase .
Reimplemented in GroupMailbox , DistributedMailbox , and LocalSMMailbox .
References MailboxLookupService::deregisterMailbox(), MailboxBase::isActive(), messageQueue_, and MailboxBase::setActive().
Referenced by DistributedMailbox::activate(), GroupMailbox::activate(), LocalSMMailbox::deactivate(), DistributedMailbox::deactivate(), and GroupMailbox::deactivate().
int LocalMailbox::getDebugValue () [virtual]
Returns the Debug flag value for this mailbox.
Implements MailboxBase .
References MailboxBase::debugValue_.
MailboxAddress & LocalMailbox::getMailboxAddress () [virtual]
Return the mailbox address
Implements MailboxBase .
Reimplemented in LocalSMMailbox .
References localAddress_.
MessageBase * LocalMailbox::getMessage (unsigned short timeoutValue = 0) [virtual]
Will block until a message is available. Note that all non-Proxy Mailbox types use the LocalMailbox's getMessage method to dequeue MsgMgr messages. May return NULL if no message available (if mailbox deactivated).
Implements MailboxBase .
References MailboxBase::isActive(), and messageQueue_.
MessageBase * LocalMailbox::getMessageNonBlocking () [virtual]
Will not block until a message is available.
If the application has a need to do non-blocking calls to get (or check to see if) messages pending on the mailbox queue, then the application needs to implement this call -instead- of calling MailboxProcessor::processMailbox(). If this is indeed the case, then the application will either need to implement the case switching on the Message Type -or- implement the find for the MessageHandlerList (functor lookup).
Note that all non-Proxy Mailbox types use the LocalMailbox's getMessage method to dequeue MsgMgr messages.
Returns
NULL if no message available (and if mailbox deactivated).
Implements MailboxBase .
References MailboxBase::isActive(), and messageQueue_.
const ACE_Time_Value & LocalMailbox::getPostDefaultTimeout () [virtual]
Return the post timeout
Implements MailboxBase .
int LocalMailbox::post (MessageBase * messagePtr, const ACE_Time_Value * timeout = &ACE_Time_Value::zero) [virtual]
Post a message to this mailbox.
Returns
ERROR for an error, OK otherwise.
Implements MailboxBase .
References MessageBlockWrapper::base(), MailboxBase::debugValue_, MessageBase::getMessageId(), MessageBase::getPriority(), MessageBase::getSourceAddress(), MailboxBase::isActive(), localAddress_, messageQueue_, MessageBase::toString(), MailboxAddress::toString(), and MailboxBase::toString().
Referenced by DistributedMailbox::createMailbox(), GroupMailbox::createMailbox(), and LocalSMMailbox::getMailboxAddress().
void LocalMailbox::setDebugValue (int debugValue) [virtual]
Sets the Debug flag value for this mailbox.
Implements MailboxBase .
References MailboxBase::debugValue_.
void LocalMailbox::startReactor (void * arg) [static], [protected]
This static method is called in a new thread context to start the ACE Reactor event processing loop during mailbox activation. This will run the event loop until the <ACE_Reactor::handle_events> or <ACE_Reactor::alertable_handle_events> methods returns -1, the <end_reactor_event_loop> method is invoked, or the <ACE_Time_Value> expires.
Parameters
arg Pointer to the reactor that we are going to start
References MailboxBase::isShuttingDown_.
Referenced by DistributedMailbox::createMailbox(), LocalSMMailbox::createMailbox(), GroupMailbox::createMailbox(), and createMailbox().
Member Data Documentation
MailboxAddress LocalMailbox::localAddress_ [protected]
Address of this Mailbox
Referenced by getMailboxAddress(), and post().
ACE_Message_Queue<ACE_MT_SYNCH> LocalMailbox::messageQueue_ [protected]
Message queue for storing received messages
Referenced by activate(), deactivate(), getMessage(), getMessageNonBlocking(), post(), and ~LocalMailbox().
The documentation for this class was generated from the following files:
LocalMailbox.h
LocalMailbox.cpp