LoggerSMConfig Class Reference
#include <LoggerSMConfig.h>
Public Member Functions
LoggerSMConfig (const char *configName, const char *coordinatingMutexName)
virtual ~LoggerSMConfig ()
int initialize ()
int getLogLevel (int subsystem)
int setLogLevel (int subsystem, int severityLevel)
void reset ()
string toString ()
Detailed Description
LoggerSMConfig handles storing and retrieving the Logger configuration parameters (such as log level) to and from Shared Memory.
LoggerSMConfig uses position independent shared memory to provide access of the configuration parameters to both the LogProcessor server daemon as well as to the Logger client apis that exist as part of each of the application processes.
The shared memory configuration parameters are stored inside a LoggerSMConfigValues structure.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
LoggerSMConfig::LoggerSMConfig (const char * configName, const char * coordinatingMutexName)
Constructor
Parameters
configName String name of the Logger SM Config value structure used to identify it in the underlying shared memory map
coordinatingMutexName Name used to identify the process mutex for other processes
LoggerSMConfig::~LoggerSMConfig () [virtual]
Virtual Destructor
Member Function Documentation
int LoggerSMConfig::getLogLevel (int subsystem)
Get the Log Level configuration values
References LoggerSMConfigValues::logLevelsPI.
int LoggerSMConfig::initialize ()
Create the (or get a reference to an already created) config values structure
Returns
OK on success; otherwise ERROR
References SharedMemoryManager::getAllocator(), and LoggerSMConfigValues::reset().
void LoggerSMConfig::reset (void)
Reset the contents of the shared memory configuration structure to defaults.
References LoggerSMConfigValues::reset().
int LoggerSMConfig::setLogLevel (int subsystem, int severityLevel)
Set the Log Level configuration values.
Returns
ERROR on failure; otherwise OK
References LoggerSMConfigValues::logLevels, and LoggerSMConfigValues::logLevelsPI.
string LoggerSMConfig::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
The documentation for this class was generated from the following files:
LoggerSMConfig.h
LoggerSMConfig.cpp