DataManager Class Reference
#include <DataManager.h>
Public Member Functions
virtual ~DataManager ()
Static Public Member Functions
static int initialize (string configurationFileLocation)
static int activateConnectionSet (string connectionSetName)
static int deActivateConnectionSet (string connectionSetName)
static int deActivateAllConnectionSets ()
static DbConnectionHandle * reserveConnection (string connectionSetName)
static DbConnectionHandle * reserveConnectionNonBlocking (string connectionSetName)
static void releaseConnection (DbConnectionHandle *connectionHandle)
Detailed Description
DataManager provides an application interface for setting and retrieving data to and from the persistent store.
DataManager is provided to hide some of the complexity of working with the database. It is intended to allow the database to be transparently replaced by different products/mechanisms without requiring the applications to do major surgery. Additionally, the DataManager defines the concurrency model for how the applications will interact with the database. For example, an application program will have multiple threads; each thread requires periodic access to the database. A connection set will be created for this application that contains FEWER connections than the number of threads that need them. Each thread is required to reserve a database connection, use it, and then release it back into the DataManager pool so that another thread can then reserve and access. Of course the number of pooled connections versus the number of application threads is a systems engineering exercise and is configurable. Note that each connection is itself NOT thread safe and multiple threads should not attempt to access the same connection object (DbConnectionHandle) after it has been reserved by a single thread (this is typically the concurrency architecture for most database drivers). (This is possible with additional mutex/concurrency mechanisms implemented by the application, but it is NOT ADVISABLE, and not necessary).
The general error handling strategy for the application developer should be as follows. If any errors are encountered while issuing query/update/insert/delete commands or while analyzing results, the developer should release the connection back into the pool and attempt to reserve another connection for use. The release process includes a health check on the connection that will attempt to re-establish/ renew that connection in the event of a failure.
DataManager exists as a library for each of the application processes to use for managing its database connections. DataManager supports pooling of connections, and connection re-establishment and retry. Because the DataManager is a bootstrap requirement for the applications obtaining all of their other configuration information (from the database), the DataManager reads ITS configuration from a file. Furthermore, because DataManager is used by multiple processes, this file must contain process-specific configuration sections to meet each process's unique database connection requirements (with regards to the number of connections, both local and remote, etc.)
The format of the DataManager configuration file is:
  [Configuration]
  DEBUGLEVEL=5
  [ConnectionSet Name]
  # Some comments
  # Perhaps some more comments
  USERID=userid
  PASSWORD=password (NOTE: This will need to be encrypted later...suggest MD5)
  DRIVERNAME=libpq
  CONNECTIONTYPE=LOCAL (or REMOTE)
  CONNECTIONSTRING="hostaddr=127.0.0.1 port=3180"
  NUMBERCONNECTIONS=1
  DSN=someDSN
  [Next ConnectionSet Name]
  ...
The above [Configuration] section exists in order to set DataManager-wide configuration parameters. Each subsequent [ConnectionSet Name] section establishes the configuration for a pool of connections. Note that an OPM object pool is created even if only 1 connection is indicated. An application process can have multiple [ConnectionSet] sections for its use in the configuration file. The application process would then call DataManager::activateConnectionSet(string connectionSetName) for each configured connection set that it needs to use.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
DataManager::~DataManager () [virtual]
Virtual Destructor
Member Function Documentation
int DataManager::activateConnectionSet (string connectionSetName) [static]
Application processes will call this method for each ConnectionSet in the configuration file that they need to use. This method will create the database connection pools.
Parameters
connectionSetName must match a name in the configuration file
Returns
ERROR for database connection failures; otherwise OK
Referenced by ResourceMonitor::initialize(), and FaultManager::initialize().
int DataManager::deActivateAllConnectionSets () [static]
Method for performing deActivation of All Connection Sets within this application process. All connections to the database are closed.
Returns
ERROR for database connection shutdown failures; otherwise OK
int DataManager::deActivateConnectionSet (string connectionSetName) [static]
Method for performing deActivation of the Connection Set. All connections to the database are closed.
Parameters
connectionSetName must match a name in the configuration file
Returns
ERROR for database connection shutdown failures; otherwise OK
int DataManager::initialize (string configurationFileLocation) [static]
Initialize the DataManager with the location of the configuration file.
Open and parse the entire configuration file. This creates a ConnectionSet object for each section in the file.
Returns
ERROR for File IO or File format parsing errors; otherwise OK
References ConnectionSet::setConnectionString(), ConnectionSet::setConnectionType(), ConnectionSet::setDriverName(), ConnectionSet::setDSN(), ConnectionSet::setNumberConnections(), ConnectionSet::setPassword(), and ConnectionSet::setUserid().
Referenced by ResourceMonitor::initialize(), and FaultManager::initialize().
void DataManager::releaseConnection (DbConnectionHandle * connectionHandle) [static]
Method to release the DbConnection back into the Connection Set pool.
Parameters
connectionHandle wraps the connection to be released to the pool
Returns
NULL if the connectionSetName could not be found
Referenced by OSResource::initialize(), and FaultManager::processMailbox().
DbConnectionHandle * DataManager::reserveConnection (string connectionSetName) [static]
Method to retrieve a pointer to a DbConnection from the Connection Set pool. This method blocks until a DbConnection becomes available if they are all currently in use.
Parameters
connectionSetName must match a name in the configuration file
Returns
NULL if the connectionSetName could not be found
Referenced by OSResource::initialize(), and FaultManager::processMailbox().
DbConnectionHandle * DataManager::reserveConnectionNonBlocking (string connectionSetName) [static]
Method to retrieve a pointer to a DbConnection from the Connection Set pool. This method does NOT block if there are no DbConnections available in the pool. NOTE that the pools are configured not to GROW and/or SHRINK
Parameters
connectionSetName must match a name in the configuration file
Returns
NULL if no DbConnection available, or if the connectionSetName could not be found
The documentation for this class was generated from the following files:
DataManager.h
DataManager.cpp