MessageBase Class Reference
#include <MessageBase.h>
Public Member Functions
MessageBase (const MailboxAddress &sourceAddress, unsigned int versionNumber, unsigned int sourceContextId=0, unsigned int destinationContextId=0)
virtual ~MessageBase ()
virtual unsigned short getMessageId () const =0
virtual unsigned char getDestinationMailboxId () const
virtual int serialize (MessageBuffer &buffer)
virtual unsigned int getSourceContextId () const
virtual unsigned int getDestinationContextId () const
virtual const MailboxAddress & getSourceAddress () const
virtual void deleteMessage ()
virtual string toString ()=0
void setPriority (unsigned int priorityLevel=0)
void setVersion (unsigned int versionNumber)
unsigned int getPriority ()
unsigned int getVersion ()
bool isPoolable ()
bool isReusable ()
Static Public Member Functions
static unsigned short getStaticMessageId ()
static MessageBase * deserialize (MessageBuffer *buffer)
Protected Attributes
MailboxAddress sourceAddress_
unsigned int sourceContextId_
unsigned int destinationContextId_
unsigned int versionNumber_
bool isReusable_
Additional Inherited Members
Detailed Description
MessageBase is the base class for all messages.
This is an abstract class and cannot be instantiated. All messages in the system will be derived ultimately from this base class.
The following 4 types of message subclasses are possible in the MsgMgr:
Non-reusable / Not OPM Pooled Example: Distributed Message that will only be used once at initialization
Non-reusable / OPM Pooled Example: Messages used for different purposes within Callp
Reusable / Not OPM Pooled Example: Periodically recurring TimerMessage, but only one is needed for the application's lifetime.
Reusable / OPM Pooled Example: Many TimerMessages are needed by the application. Each Timer will be periodically recurring for a finite number of times before being released back into the OPM.
Message subclasses do not automatically inherit from OPMBase. If a message subclass is required to be OPM poolable, then it will need to do multiple inheritance from both MessageBase (or ReusableMessageBase) and OPMBase. This is ALSO true for timers which inherit from the TimerMessage base class. Note that TimerMessage will behave like either a MessageBase or ReusableMessageBase depending on whether a non-default 'RestartInterval' parameter is given to make the Timer periodically recurring.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
MessageBase::MessageBase (const MailboxAddress & sourceAddress, unsigned int versionNumber, unsigned int sourceContextId = 0, unsigned int destinationContextId = 0)
Constructor
References MessageBase().
Referenced by MessageBase().
MessageBase::~MessageBase () [virtual]
Virtual Destructor
Member Function Documentation
void MessageBase::deleteMessage () [virtual]
Delete the message and perform cleanup operations
This method is called automatically by the Mailbox Processor. Here we use the ObjectBase class in OPM to determine if the object is managed by the OPM. If so, then we check the object in; otherwise, we just delete it.
Here, a special case exists for the single recurring TimerMessage: Its not pooled/owned by OPM, but it is poolable (inherited from OPMBase, since the TimerMessage base class is). Since its set to periodically restart, we don't want to delete it. This also means that non-recurring TimerMessages WILL NOT BE DELETED ALSO, so its upto the application developer to keep a reference to them and delete them when they are done with them.
References OPM::isCreatedByOPM(), isPoolable(), and isReusable_.
Referenced by DistributedMailboxProxy::post(), LocalSMMailboxProxy::post(), GroupMailboxProxy::post(), MailboxProcessor::processMailbox(), and LocalMailbox::~LocalMailbox().
MessageBase * MessageBase::deserialize (MessageBuffer * buffer) [static]
Default static deserialization (bootstrap) implementation.
This method only needs to be implemented for distributed messages. Since this method needs to be static in order to register it with the MessageFactory, it does not make sense for it to be virtual. This method is provided here for developer clarity only.
Returns
Either a 'new' created Messate object with the contents of the buffer, or an pooled object 'reserved' from its OPM pool and initialized with the contents of the buffer.
unsigned int MessageBase::getDestinationContextId () const [virtual]
Return the application specific context info for identifying the destination
References destinationContextId_.
unsigned char MessageBase::getDestinationMailboxId () const [virtual]
Returns the destination mailbox for the message
References getMessageId().
virtual unsigned short MessageBase::getMessageId () const [pure virtual]
Returns the unique message identifier for any subclass of MessageBase. MessageId's must be registered in common/MessageIds.h
Implemented in TimerMessage , DiscoveryLocalMessage , AlarmEventMessage , DiscoveryMessage , and ResourceMonitorTimerMessage .
Referenced by DistributedMailbox::createMailbox(), GroupMailbox::createMailbox(), getDestinationMailboxId(), LocalSMMailbox::getMailboxAddress(), DistributedMailboxProxy::post(), LocalSMMailboxProxy::post(), LocalMailbox::post(), GroupMailboxProxy::post(), MailboxProcessor::processMailbox(), and serialize().
unsigned int MessageBase::getPriority ()
Return the priority Level for this message. Default priority is 0. Priorities greater than 0 have greater priority.
Referenced by DistributedMailboxProxy::post(), LocalSMMailboxProxy::post(), LocalMailbox::post(), and GroupMailboxProxy::post().
const MailboxAddress & MessageBase::getSourceAddress () const [virtual]
Return the source mailbox address from which the message was sent
References sourceAddress_.
Referenced by DistributedMailbox::createMailbox(), GroupMailbox::createMailbox(), LocalSMMailbox::getMailboxAddress(), DistributedMailboxProxy::post(), LocalSMMailboxProxy::post(), LocalMailbox::post(), GroupMailboxProxy::post(), and DiscoveryManager::processMailbox().
unsigned int MessageBase::getSourceContextId () const [virtual]
Return the application specific context info for identifying the source
References sourceContextId_.
unsigned short MessageBase::getStaticMessageId () [static]
Returns static message identifier for any subclass of MessageBase.
unsigned int MessageBase::getVersion ()
Get the version number of this message.
References versionNumber_.
bool MessageBase::isPoolable ()
Return whether or not this object is managed by an OPM pool
References ObjectBase::isPoolable().
Referenced by MailboxOwnerHandle::cancelTimer(), deleteMessage(), and LocalMailbox::~LocalMailbox().
bool MessageBase::isReusable ()
Return whether or not this object is Reusable
References isReusable_.
Referenced by MailboxOwnerHandle::cancelTimer().
int MessageBase::serialize (MessageBuffer & buffer) [virtual]
Default serialization implementation.
This method only needs to be implemented for distributed messages.
Returns
OK or ERROR if not successful
Reimplemented in AlarmEventMessage , and DiscoveryMessage .
References getMessageId().
Referenced by DistributedMailboxProxy::post(), LocalSMMailboxProxy::post(), and GroupMailboxProxy::post().
void MessageBase::setPriority (unsigned int priorityLevel = 0)
Flag this message as high priority. This flag will cause the message to be re-ordered in the Mailbox message queue (so will NOT follow FIFO rules). Default priority is 0. Priorities greater than 0 have greater priority.
Referenced by DistributedMailbox::createMailbox(), GroupMailbox::createMailbox(), and LocalSMMailbox::getMailboxAddress().
void MessageBase::setVersion (unsigned int versionNumber)
Set the version for this message. This method is used by the MsgMgr framework to re-apply the version number following deserialization
References versionNumber_.
virtual string MessageBase::toString () [pure virtual]
String'ized debugging method
Returns
string representation of the contents of this object
Implemented in TimerMessage , AlarmEventMessage , DiscoveryMessage , DiscoveryLocalMessage , and ResourceMonitorTimerMessage .
Referenced by DistributedMailbox::createMailbox(), GroupMailbox::createMailbox(), LocalSMMailbox::getMailboxAddress(), DistributedMailboxProxy::post(), LocalSMMailboxProxy::post(), LocalMailbox::post(), and GroupMailboxProxy::post().
Member Data Documentation
unsigned int MessageBase::destinationContextId_ [protected]
Application specific context for identifying the destination. Usage of this value is upto the application.
Referenced by getDestinationContextId(), and AlarmEventMessage::serialize().
bool MessageBase::isReusable_ [protected]
Whether or not this Message is re-usable. If true, then the MsgMgr framework will not consume it.
Referenced by deleteMessage(), isReusable(), ReusableMessageBase::ReusableMessageBase(), ReusableMessageBase::setNoLongerReusable(), and TimerMessage::TimerMessage().
MailboxAddress MessageBase::sourceAddress_ [protected]
Source mailbox identifier of the application that sent the message
Referenced by getSourceAddress(), DiscoveryMessage::serialize(), AlarmEventMessage::serialize(), DiscoveryLocalMessage::toString(), DiscoveryMessage::toString(), and AlarmEventMessage::toString().
unsigned int MessageBase::sourceContextId_ [protected]
Application specific context for identifying the source. Usage of this value is upto the application.
Referenced by getSourceContextId(), and AlarmEventMessage::serialize().
unsigned int MessageBase::versionNumber_ [protected]
Version Number of the message
Referenced by getVersion(), AlarmEventMessage::serialize(), and setVersion().
The documentation for this class was generated from the following files:
MessageBase.h
MessageBase.cpp