CliClient Class Reference
#include <CliClient.h>
Public Member Functions
CliClient ()
virtual ~CliClient ()
int initialize (bool dottedDecimalIORFlag, bool debugFlag, string &debugLevel, string &debugFilename, string &endPointString, string &initRef, string &defaultInitRef)
void processMenu ()
string toString ()
Static Public Member Functions
static void shutdown ()
Detailed Description
Provides a CLI Client interface to the EMS' Client Agent through CORBA.
Note: Previous versions of the TAO Orb used TAO Exception Handling Macros to make the Standard Corba Exceptions compatible with platforms that do not support native C++ exception handling constructs. These TAO specific Macros have now been deprecated (they now cause compiler errors); they have been replaced with the base ACE Exception Handling Macros. However, since our development platform WILL ALWAYS support native C++ exception handling, we are foregoing the use of the ACE Macros, and we will ONLY support the native exception handling for simplicity.
CliClient accepts the following startup options: -h Restricts the use of hostnames in IORs. Invokes -ORBDottedDecimalAddresses 1 on the Orb -d Enable debug messages from within the Orb. Invokes -ORBDebug on the Orb. -l <Debug level>=``> Sets the debug level within the Orb (Max is 10). Invokes -ORBDebugLevel on the Orb. -f <log filename>=``> Sets the log filename for Orb debug logs. Invokes -ORBLogFile on the Orb. (Default is stdout) -e <Endpoint> Orb listens for connections on the interfaces specified by the endpoint URL (Invokes -ORBListenEndpoints) -i <Initial reference>=``> URL the Orb uses for initial resolution of Naming Service (corbaloc) (Invokes -ORBInitRef) -r <Default init=`` ref>=``> URL the Orb uses for default initial resolution of Naming Service (corbaloc) (Invokes -ORBDefaultInitRef)
Note that the correct syntax for -i (the ORBInitRef) -ORBInitRef is: NameService=corbaloc:iiop:localhost:12345/NameService -- or -- NameService=iiop://localhost:12345/NameService The former (corbaloc) syntax is the standard (compliant with the Interoperable Naming Service specification) syntax. The latter syntax is TAO-specific and is deprecated.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
CliClient::CliClient ()
Constructor
Referenced by toString().
CliClient::~CliClient () [virtual]
Virtual Destructor
Member Function Documentation
int CliClient::initialize (bool dottedDecimalIORFlag, bool debugFlag, string & debugLevel, string & debugFilename, string & endPointString, string & initRef, string & defaultInitRef)
Perform CliClient initialization
Parameters
dottedDecimalIORFlag If true, fore-go the use of hostnames in IORs. Instead use IP Addresses
debugFlag If true, enable the Orb inner debug logging
debugLevel Max is 10 -- the most verbose logging
debugFilename Redirect Orb debug logs to a file instead of stdout
endPointString On a multihomed host, instruct the Orb to use the interface described by this endpoint
initRef Use the Interoperable Naming Service url for locating Naming Service reference
defaultInitRef Use the INS url for default reference resolving
Returns
ERROR upon failure; otherwise OK
Referenced by toString().
void CliClient::processMenu ()
Handle Menu Option user input
References CliMenuController::initialize().
Referenced by toString().
void CliClient::shutdown () [static]
Gracefully shutdown the CliClient and all of its threads
Referenced by toString().
string CliClient::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
References CliClient(), initialize(), processMenu(), and shutdown().
The documentation for this class was generated from the following files:
CliClient.h
CliClient.cpp