TimerMessage Class Reference
#include <TimerMessage.h>
Public Member Functions
TimerMessage (const MailboxAddress &sourceAddress, unsigned int versionNumber, ACE_Time_Value timeout, ACE_Time_Value restartInterval=ACE_Time_Value::zero, unsigned int sourceContextId=0, unsigned int destinationContextId=0)
virtual ~TimerMessage ()
ACE_Time_Value & getTimeout ()
ACE_Time_Value & getRestartInterval ()
void setExpirationTime (ACE_Time_Value expirationTime)
ACE_Time_Value & getExpirationTime ()
virtual unsigned short getMessageId () const
string toString ()
Protected Attributes
ACE_Time_Value timeout_
ACE_Time_Value restartInterval_
ACE_Time_Value expirationTime_
Additional Inherited Members
Detailed Description
TimerMessage is the base class implementation for all system timer messages.
All system software Timer Messages (that can tolerate the MsgMgr concurrency latency) must inherit from this class. The exception to this rule is that this class can be created concrete--If an application has no need for passing parameters/values along with the Timer, then it can use this generic/concrete class to get an expiration time.
High resolution or hardware timers (sub-microsecond) must register or schedule themselves manually.
Because the TimerMessage has the capability to be automatically recurring (that is, it can automatically re-schedule itself), the application developer needs to take special notice. This class does not automatically inherit from OPMBase. If a TimerMessage subclass is required to be OPM pooled, then it will need to do multiple inheritance from both MessageBase (or ReusableMessageBase) and OPMBase.
If the TimerMessages are pooled by the OPM, then no special handling is required as the MsgMgr framework will handle the release of the timers back into their respective OPM pools after their handler has completed.
Otherwise, the TimerMessage will behave like a ReusableMessageBase if a non-default 'RestartInterval' parameter is given to make the Timer periodically recurring. In this case, the application has the responsibility to delete the TimerMessage when it is no longer needed. Otherwise, if RestartInterval is defaulted, then the TimerMessage will behave like a MessageBase and be deleted by the MsgMgr. Note: A TimerMessage can be changed to be 'no longer reusable', after which it will behave like a regular MessageBase after the expiration handler is complete (or if the Timer is canceled).
Also note that if a restartInterval is specified to periodically restart the Timer, then it is NOT necessary to re-post the Timer Message. All other reusable messages must be posted again in order to reuse them.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
TimerMessage::TimerMessage (const MailboxAddress & sourceAddress, unsigned int versionNumber, ACE_Time_Value timeout, ACE_Time_Value restartInterval = ACE_Time_Value::zero, unsigned int sourceContextId = 0, unsigned int destinationContextId = 0)
Constructor
Parameters
timeout time interval after which the timer will expire
restartInterval time interval after which the timer will be automatically rescheduled. If this parameter is defaulted, then the TimerMessage will behave like a MessageBase; otherwise, if it is non-default, then it will behave like a ReusableMessageBase. If a non-default restartInterval is specified, it is NOT necessary to re-post (by calling scheduleTimer() again) the message to restart the Timer.
References MessageBase::isReusable_, and TimerMessage().
Referenced by TimerMessage().
TimerMessage::~TimerMessage () [virtual]
Virtual Destructor
Member Function Documentation
ACE_Time_Value & TimerMessage::getExpirationTime ()
Retrieves the 'actual' time that the Timer Expired. This value is set by the MsgMgr framework, and it is provided to the applications so that it can be used to 'judge' the amount of latency introduced by the Timer sitting inside the mailbox queue.
References expirationTime_.
unsigned short TimerMessage::getMessageId () const [virtual]
Returns the unique message identifier for any subclass of MessageBase. MessageId's must be registered in common/MessageIds.h
Implements MessageBase .
Reimplemented in ResourceMonitorTimerMessage .
ACE_Time_Value & TimerMessage::getRestartInterval ()
Return the time interval after which the timer will be automatically rescheduled
References restartInterval_.
Referenced by MailboxOwnerHandle::scheduleTimer().
ACE_Time_Value & TimerMessage::getTimeout ()
Return the time interval after which the timer will expire
References timeout_.
Referenced by MailboxOwnerHandle::scheduleTimer().
void TimerMessage::setExpirationTime (ACE_Time_Value expirationTime)
Sets the time that the Timer actually expires. This is called by the MsgMgr framework. Applications should NOT call this method
References expirationTime_.
Referenced by MailboxBase::handle_timeout().
string TimerMessage::toString () [virtual]
String'ized debugging method
Returns
string representation of the contents of this object
Implements MessageBase .
Reimplemented in ResourceMonitorTimerMessage .
Member Data Documentation
ACE_Time_Value TimerMessage::expirationTime_ [protected]
Records the 'actual' time that the Timer expired
Referenced by getExpirationTime(), and setExpirationTime().
ACE_Time_Value TimerMessage::restartInterval_ [protected]
Time interval after which the timer will be automatically rescheduled
Referenced by getRestartInterval().
ACE_Time_Value TimerMessage::timeout_ [protected]
Time interval after which the timer will expire
Referenced by getTimeout().
The documentation for this class was generated from the following files:
TimerMessage.h
TimerMessage.cpp