LoggerCommon Class Reference
Public Member Functions
virtual ~LoggerCommon ()
Static Public Member Functions
static void convertTimeToString (long time, char *buf)
static void convertTimeToDateString (long time, char *buf)
static void formatLogMessage (LogMessage *logMessage, char *buffer)
static char * wrapFormattedLogText (char *buffer, char *wrapBuffer)
Constructor & Destructor Documentation
LoggerCommon::~LoggerCommon () [virtual]
Virtual Destructor
Member Function Documentation
void LoggerCommon::convertTimeToDateString (long time, char * buf) [static]
Convert raw time stamp to readable date string
void LoggerCommon::convertTimeToString (long time, char * buf) [static]
Convert raw time stamp to readable time string
Referenced by formatLogMessage().
void LoggerCommon::formatLogMessage (LogMessage * logMessage, char * buffer) [static]
Format the logMessage into its viewable format for outputting to a file or to the screen
References LogMessage::arg1, convertTimeToString(), LogMessage::isStringLog, LogMessage::logMessagePI, LogMessage::pid, LogMessage::sequenceId, LogMessage::severityLevel, LogMessage::sourceFilePI, LogMessage::sourceLine, LogMessage::subsystem, and LogMessage::timeStamp.
Referenced by LogProcessor::processLogs(), Logger::straceLog(), and Logger::traceLog().
char * LoggerCommon::wrapFormattedLogText (char * buffer, char * wrapBuffer) [static]
Provide for text wrapping functionality if necessary
Referenced by LogProcessor::processLogs(), Logger::straceLog(), and Logger::traceLog().
The documentation for this class was generated from the following files:
LoggerCommon.h
LoggerCommon.cpp