ems.idls.platformConfig.platformConfig_IPOA Class Reference
Public Member Functions
org.omg.CORBA.portable.OutputStream _invoke (String $method, org.omg.CORBA.portable.InputStream in, org.omg.CORBA.portable.ResponseHandler $rh)
String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
platformConfig_I _this ()
platformConfig_I _this (org.omg.CORBA.ORB orb)
Detailed Description
ems/idls/platformConfig/platformConfig_IPOA.java . Generated by the IDL-to-Java compiler (portable), version `3.2` from platformConfig.idl Tuesday, January 15, 2015 5:02:24 PM CST Command/Method interface
Member Function Documentation
org.omg.CORBA.portable.OutputStream ems.idls.platformConfig.platformConfig_IPOA._invoke (String $method, org.omg.CORBA.portable.InputStream in, org.omg.CORBA.portable.ResponseHandler $rh) [inline]
Retrieve all of the subsystem log levels
Set a specified log level
Set all of the log levels
References ems.idls.platformConfig.platformConfig_IOperations.getLogLevels(), ems.idls.platformConfig.platformConfig_IOperations.setLogLevel(), and ems.idls.platformConfig.platformConfig_IOperations.setLogLevels().
The documentation for this class was generated from the following file:
platformConfig_IPOA.java