MessageTest1Message Class Reference
#include <MessageTest1Message.h>
Public Member Functions
MessageTest1Message (const MailboxAddress &sourceAddress)
virtual ~MessageTest1Message ()
unsigned short getMessageId () const
string toString ()
MessageTest1Message (const MailboxAddress &sourceAddress)
virtual ~MessageTest1Message ()
unsigned short getMessageId () const
string toString ()
MessageTest1Message (const MailboxAddress &sourceAddress)
virtual ~MessageTest1Message ()
unsigned short getMessageId () const
string toString ()
MessageTest1Message (const MailboxAddress &sourceAddress)
virtual ~MessageTest1Message ()
unsigned short getMessageId () const
string toString ()
MessageTest1Message (const MailboxAddress &sourceAddress)
virtual ~MessageTest1Message ()
unsigned short getMessageId () const
string toString ()
MessageTest1Message (const MailboxAddress &sourceAddress)
virtual ~MessageTest1Message ()
unsigned short getMessageId () const
string toString ()
Detailed Description
MessageTest1Message is Test Message #1.
This message demonstrates local mailbox message passing only.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
MessageTest1Message::MessageTest1Message (const MailboxAddress & sourceAddress)
Constructor
MessageTest1Message::~MessageTest1Message () [virtual]
Virtual Destructor
MessageTest1Message::MessageTest1Message (const MailboxAddress & sourceAddress)
Constructor
virtual MessageTest1Message::~MessageTest1Message () [virtual]
Virtual Destructor
MessageTest1Message::MessageTest1Message (const MailboxAddress & sourceAddress)
Constructor
virtual MessageTest1Message::~MessageTest1Message () [virtual]
Virtual Destructor
MessageTest1Message::MessageTest1Message (const MailboxAddress & sourceAddress)
Constructor
virtual MessageTest1Message::~MessageTest1Message () [virtual]
Virtual Destructor
MessageTest1Message::MessageTest1Message (const MailboxAddress & sourceAddress)
Constructor
virtual MessageTest1Message::~MessageTest1Message () [virtual]
Virtual Destructor
MessageTest1Message::MessageTest1Message (const MailboxAddress & sourceAddress)
Constructor
virtual MessageTest1Message::~MessageTest1Message () [virtual]
Virtual Destructor
Member Function Documentation
unsigned short MessageTest1Message::getMessageId () const
Returns the Message Id
unsigned short MessageTest1Message::getMessageId () const
Returns the Message Id
unsigned short MessageTest1Message::getMessageId () const
Returns the Message Id
unsigned short MessageTest1Message::getMessageId () const
Returns the Message Id
unsigned short MessageTest1Message::getMessageId () const
Returns the Message Id
unsigned short MessageTest1Message::getMessageId () const
Returns the Message Id
string MessageTest1Message::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
string MessageTest1Message::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
string MessageTest1Message::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
Referenced by MessageTestRemote::MessageTestRemote(), MessageTest::processMailbox(), MessageTestGroup::processMailbox(), and MessageTestRemote::processMailbox().
string MessageTest1Message::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
string MessageTest1Message::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
string MessageTest1Message::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
The documentation for this class was generated from the following files:
discoverytest1/MessageTest1Message.h
discoverytest1/MessageTest1Message.cpp