DistributedMailboxProxy Class Reference
Public Member Functions
virtual int post (MessageBase *messagePtr, const ACE_Time_Value *timeout=&ACE_Time_Value::zero)
virtual int activate (MailboxOwnerHandle *mailboxOwnerHandle)
virtual int deactivate (MailboxOwnerHandle *mailboxOwnerHandle)
virtual const ACE_Time_Value & getPostDefaultTimeout ()
virtual int getDebugValue ()
virtual void setDebugValue (int debugValue)
MailboxAddress & getMailboxAddress ()
string toString ()
Static Public Member Functions
static MailboxOwnerHandle * createMailbox (const MailboxAddress &remoteAddress)
Protected Member Functions
DistributedMailboxProxy (const MailboxAddress &remoteAddress)
virtual ~DistributedMailboxProxy ()
Additional Inherited Members
Constructor & Destructor Documentation
DistributedMailboxProxy::DistributedMailboxProxy (const MailboxAddress & remoteAddress) [protected]
Constructor
References OPM::createPool(), DistributedMailboxProxy(), MessageBuffer::initialize(), and MailboxBase::isProxy_.
Referenced by DistributedMailboxProxy().
DistributedMailboxProxy::~DistributedMailboxProxy () [protected], [virtual]
Virtual Destructor. Protected since this is a reference counted object.
References MailboxBase::isShuttingDown_.
Member Function Documentation
int DistributedMailboxProxy::activate (MailboxOwnerHandle * mailboxOwnerHandle) [virtual]
Activate the mailbox. For security, one must possess an Owner Handle to activate the mailbox and register it with the Lookup Service.
Reimplemented from MailboxBase .
References MailboxAddress::inetAddress, MailboxBase::isActive(), MailboxLookupService::registerMailbox(), and MailboxBase::setActive().
MailboxOwnerHandle * DistributedMailboxProxy::createMailbox (const MailboxAddress & remoteAddress) [static]
Allows applications to create a mailbox and get a handle to it.
Since we do not want applications to have direct access to a mailbox object this method is provided. Applications that create mailboxes use this method to get a handle to their mailbox rather than have direct access. The handle returned is a owner handle which has all the privileges of the actual mailbox (getMessage/post etc). This method creates the mailbox, activates it (which in turn registers it with the lookup service) and then creates an owner handle, acquires it and then returns that handle. Both the mailbox and the returned handle are created on the heap.
Referenced by MailboxLookupService::find().
int DistributedMailboxProxy::deactivate (MailboxOwnerHandle * mailboxOwnerHandle) [virtual]
Deactivate the mailbox. For security, one must possess an Owner Handle to deactivate the mailbox and deregister it with the Lookup Service.
Reimplemented from MailboxBase .
References MailboxLookupService::deregisterMailbox(), MailboxBase::isActive(), and MailboxBase::setActive().
int DistributedMailboxProxy::getDebugValue () [virtual]
Return the debug flag
Implements MailboxBase .
References MailboxBase::debugValue_.
MailboxAddress & DistributedMailboxProxy::getMailboxAddress () [virtual]
Return the mailbox distributed address
Implements MailboxBase .
const ACE_Time_Value & DistributedMailboxProxy::getPostDefaultTimeout () [virtual]
Return the appropriate default timeout for the post()
Implements MailboxBase .
int DistributedMailboxProxy::post (MessageBase * messagePtr, const ACE_Time_Value * timeout = &ACE_Time_Value::zero) [virtual]
Post a message to the distributed remote mailbox. Subclass implementations should examine the `active_` state. Upon initial failure of the post, this proxy mailbox will close and re-open the socket and attempt to post the message again automatically. If the the repost fails, then ERROR will be returned, and it becomes the responsibility of the application to retry the message after deleting the mailbox handle and performing MailboxLookupService::find (which may return a redundant mate's handle); or, the application can give up and delete the message off of the heap.
Returns
zero for an error, non-zero otherwise.
Implements MailboxBase .
References MailboxBase::debugValue_, MessageBase::deleteMessage(), MessageBase::getMessageId(), MessageBase::getPriority(), MessageBase::getSourceAddress(), MailboxBase::incrementSentCount(), MailboxAddress::inetAddress, MailboxBase::isActive(), MessageBase::serialize(), MessageBase::toString(), and MailboxAddress::toString().
void DistributedMailboxProxy::setDebugValue (int debugValue) [virtual]
Set the debug flag
Implements MailboxBase .
References MailboxBase::debugValue_.
string DistributedMailboxProxy::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
The documentation for this class was generated from the following files:
DistributedMailboxProxy.h
DistributedMailboxProxy.cpp