MailboxLookupService Class Reference
Public Member Functions
virtual ~MailboxLookupService ()
Static Public Member Functions
static void initializeDiscoveryManager ()
static void registerMailbox (MailboxOwnerHandle *mailboxOwnerHandle, MailboxBase *mailboxPtr)
static void deregisterMailbox (MailboxOwnerHandle *mailboxOwnerHandle)
static MailboxHandle * find (const MailboxAddress &address)
static int registerForDiscoveryUpdates (vector< MailboxAddress > &currentlyRegisteredAddresses, MailboxAddress &matchCriteria, MailboxOwnerHandle *mailboxToNotify)
static void listAllMailboxAddresses ()
static void setDebugForAllMailboxAddresses (int debugValue)
static void getDebugForAllMailboxAddresses ()
Constructor & Destructor Documentation
MailboxLookupService::~MailboxLookupService () [virtual]
Virtual Destructor
Member Function Documentation
void MailboxLookupService::deregisterMailbox (MailboxOwnerHandle * mailboxOwnerHandle) [static]
Allows tasks to deregister their mailbox
References DiscoveryManager::deregisterForDiscoveryUpdates(), DiscoveryManager::deregisterLocalAddress(), MailboxOwnerHandle::getMailboxAddress(), Logger::getSubsystemLogLevel(), MailboxOwnerHandle::isProxy(), listAllMailboxAddresses(), MailboxAddress::locationType, and MailboxAddress::mailboxName.
Referenced by LocalMailbox::deactivate(), DistributedMailboxProxy::deactivate(), LocalSMMailboxProxy::deactivate(), GroupMailboxProxy::deactivate(), and MailboxBase::release().
MailboxHandle * MailboxLookupService::find (const MailboxAddress & address) [static]
Allows an application to lookup and get a handle to another specific mailbox. IMPORTANT: Here the returned MailboxHandle pointer is allocated on the heap. It is the responsibility of the Applications to delete the MailboxHandle when it is no longer needed (and to prevent a memory leak).
When the requested address is of LocationType LOCAL_MAILBOX, then the the returned handle will point to a Local Mailbox (and posted messages will be handled by the Local Mailbox post routine). If the requested address is of a remote LocationType (Distributed, LocalSM, or Group), then the returned handle will point to a Proxy Mailbox (and posted messages will be serialized by the Proxy Mailbox's post routine for remote delivery).
References MailboxOwnerHandle::activate(), DistributedMailboxProxy::createMailbox(), LocalSMMailboxProxy::createMailbox(), GroupMailboxProxy::createMailbox(), MailboxOwnerHandle::generateMailboxHandleCopy(), MailboxHandle::getMailboxAddress(), Logger::getSubsystemLogLevel(), MailboxHandle::isProxy(), and MailboxAddress::locationType.
Referenced by FaultManager::initialize(), and FaultManager::processMailbox().
void MailboxLookupService::getDebugForAllMailboxAddresses () [static]
Method to set debug value for all mailboxes
References MailboxOwnerHandle::getMailboxAddress(), Logger::getSubsystemLogLevel(), MailboxOwnerHandle::isProxy(), MailboxAddress::locationType, and DiscoveryManager::processMailbox().
void MailboxLookupService::initializeDiscoveryManager () [static]
Instantiate and start the Discovery Manager
References ThreadManager::createThread(), and DiscoveryManager::initialize().
void MailboxLookupService::listAllMailboxAddresses () [static]
Display a list of all the registered mailbox addresses This method displays its output in trace logs.
References DiscoveryManager::listAllMailboxAddresses().
Referenced by deregisterMailbox(), and registerMailbox().
int MailboxLookupService::registerForDiscoveryUpdates (vector< MailboxAddress > & currentlyRegisteredAddresses, MailboxAddress & matchCriteria, MailboxOwnerHandle * mailboxToNotify) [static]
Allows mailboxes to register for Discovery Update notifications. If a DiscoveryMessage update is received whose discovery Mailbox Address matches that of the matchCriteria, then a copy of the DiscoveryMessage is posted to the mailboxToNotify. The caller is required to pre-allocate a vector of MailboxAddresses which will be populated with 'already-discovered' MailboxAddresses and returned.
Note that current there is no support for a user-initiated deregistration mechanism. This is because the discovery update mechanism should not be used as a substitute for IPC between nodes.
Parameters
matchCriteria MailboxAddress object used to determine which discovery Mailbox Addresses match what the application wants to be notified about. NOTE: The calling application should leave all fields default except those that the caller wished to be used in the match comparison. For example, if the caller wants to be notified when any Mailboxes with the MailboxName 'CallProcessor' are discovered, the matchCriteria field 'MailboxName' will be set to 'CallProcessor' and all other fields left as the default.
mailboxToNotify MailboxOwnerHandle of the mailbox that will receive the DiscoveryMessage notification when an update is received. This mailbox must provide a MessageHandler method for the Discovery Message id (MSGMGR_DISCOVERY_MSG_ID)
Returns
OK upon successful registration; otherwise ERROR
References DiscoveryManager::registerForDiscoveryUpdates().
void MailboxLookupService::registerMailbox (MailboxOwnerHandle * mailboxOwnerHandle, MailboxBase * mailboxPtr) [static]
Allows tasks to register their mailbox
References MailboxBase::deactivate(), MailboxOwnerHandle::getMailboxAddress(), Logger::getSubsystemLogLevel(), MailboxBase::isProxy(), listAllMailboxAddresses(), MailboxAddress::locationType, MailboxAddress::mailboxName, DiscoveryManager::registerLocalAddress(), and MailboxAddress::toString().
Referenced by LocalMailbox::activate(), DistributedMailboxProxy::activate(), LocalSMMailboxProxy::activate(), and GroupMailboxProxy::activate().
void MailboxLookupService::setDebugForAllMailboxAddresses (int debugValue) [static]
Method to set debug value for all mailboxes
Referenced by FaultManager::processMailbox().
The documentation for this class was generated from the following files:
MailboxLookupService.h
MailboxLookupService.cpp