MessageTestGroupMessage Class Reference
#include <MessageTestGroupMessage.h>
Public Member Functions
MessageTestGroupMessage (const MailboxAddress &sourceAddress, int ourIntValue, string ourStringValue)
virtual ~MessageTestGroupMessage ()
unsigned short getMessageId () const
int serialize (MessageBuffer &buffer)
string toString ()
MessageTestGroupMessage (const MailboxAddress &sourceAddress, int ourIntValue, string ourStringValue)
virtual ~MessageTestGroupMessage ()
unsigned short getMessageId () const
int serialize (MessageBuffer &buffer)
string toString ()
Static Public Member Functions
static MessageBase * deserialize (MessageBuffer *buffer)
static MessageBase * deserialize (MessageBuffer *buffer)
Detailed Description
MessageTestGroupMessage is a Test Message for the Group Mailbox.
This message demonstrates distributed and local mailbox message passing.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
MessageTestGroupMessage::MessageTestGroupMessage (const MailboxAddress & sourceAddress, int ourIntValue, string ourStringValue)
Constructor
Referenced by deserialize().
MessageTestGroupMessage::~MessageTestGroupMessage () [virtual]
Virtual Destructor
MessageTestGroupMessage::MessageTestGroupMessage (const MailboxAddress & sourceAddress, int ourIntValue, string ourStringValue)
Constructor
virtual MessageTestGroupMessage::~MessageTestGroupMessage () [virtual]
Virtual Destructor
Member Function Documentation
MessageBase * MessageTestGroupMessage::deserialize (MessageBuffer * buffer) [static]
Subclassed deserialization / bootstrap implementation
References MessageTestGroupMessage().
Referenced by MessageTestGroup::getOwnerHandle().
static MessageBase* MessageTestGroupMessage::deserialize (MessageBuffer * buffer) [static]
Subclassed deserialization / bootstrap implementation
unsigned short MessageTestGroupMessage::getMessageId () const
Returns the Message Id
unsigned short MessageTestGroupMessage::getMessageId () const
Returns the Message Id
int MessageTestGroupMessage::serialize (MessageBuffer & buffer)
Subclassed serialization implementation
int MessageTestGroupMessage::serialize (MessageBuffer & buffer)
Subclassed serialization implementation
string MessageTestGroupMessage::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
Referenced by MessageTestGroup::processMailbox().
string MessageTestGroupMessage::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
The documentation for this class was generated from the following files:
msgmgrgrouptest1/MessageTestGroupMessage.h
msgmgrgrouptest1/MessageTestGroupMessage.cpp