Logger Class Reference
#include <Logger.h>
Public Member Functions
~Logger ()
int initialize (bool sendOutputToLocal)
Static Public Member Functions
static void traceLog (LogEntrySubSystemType subsystem, LogEntrySeverityType severity, int pid, const char *sourceFile, int sourceLine, const char *p_logMessage, long arg1, long arg2, long arg3, long arg4, long arg5, long arg6)
static void straceLog (LogEntrySubSystemType subsystem, LogEntrySeverityType severity, int pid, const char *sourceFile, int sourceLine, const char *p_logMessage)
static LogEntrySeverityType getSubsystemLogLevel (LogEntrySubSystemType subsystem)
static void setSubsystemLogLevel (LogEntrySubSystemType subsystem, LogEntrySeverityType severityLevel)
static Logger * getInstance ()
Detailed Description
Logger provides the main logging mechanism and API to the developers.
Developers use the Log MACROS to issue logs. These macros hide the API mechanism for enqueuing the logs for output. In this way, the logger subsystem can be transparently modified to send output to a.) stdout, b.) the Linux syslog facility, or even c.) the ACE logger framework without impact to the application developers.
The key goal for implementing and maintaining this logger is to allow applications to issue trace logs with the MINIMAL amount of buffer copying possible. This is the key motivator behind supporting a custom implementation.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
Logger::~Logger ()
Destructor
Member Function Documentation
Logger * Logger::getInstance () [static]
Return a singleton instance
Referenced by FaultManager::processMailbox(), ResourceMonitor::toString(), and ProcessManager::toString().
LogEntrySeverityType Logger::getSubsystemLogLevel (LogEntrySubSystemType subsystem) [static]
Method to retrieve the current logging severity level for a particular subsystem
Returns
int severityLevel
Referenced by MailboxLookupService::deregisterMailbox(), MailboxLookupService::find(), MailboxLookupService::getDebugForAllMailboxAddresses(), OSResource::initialize(), ObjectPool::ObjectPool(), MailboxLookupService::registerMailbox(), ObjectPool::release(), and ObjectPool::reserve().
int Logger::initialize (bool sendOutputToLocal)
Perform initialization of shared memory queue, etc.
Parameters
sendOutputToLocal If true, output is redirected to local stdout/stderr rather than enqueued for the LogProcessor process. This is for developer debugging.
Returns
OK on success; otherwise ERROR
Referenced by FaultManager::processMailbox(), ResourceMonitor::toString(), and ProcessManager::toString().
void Logger::setSubsystemLogLevel (LogEntrySubSystemType subsystem, LogEntrySeverityType severityLevel) [static]
Method to set subsystem log severity levels. This method controls the allowable logs output.
References traceLog().
Referenced by FaultManager::processMailbox(), ResourceMonitor::toString(), and ProcessManager::toString().
void Logger::straceLog (LogEntrySubSystemType subsystem, LogEntrySeverityType severity, int pid, const char * sourceFile, int sourceLine, const char * p_logMessage) [static]
Method to handle enqueuing of the log messages
Enqueue a string log message for output (make a copy before inserting in the queue. Memory Management here: p_logMessage gets deleted when the calling method goes out of scope since it was probably a stack variable there. This is why we make a copy of p_logMessage before enqueuing it to our Log Server. The 'logMessage' struct that we create on the first line here will be deleted (including its logMessage buffer--deleted by its destructor) when this method goes out of scope.
A performance optimization for this logger should be to create pool of logMessage structs on the heap and reuse them: reserve one here and fill its contents, then pass it into the log queue where it gets deleted on the other side once it is output to where-ever. NOTE: this pool should not use OPM (circular dependency).
References LoggerCommon::formatLogMessage(), LogMessage::isStringLog, LogMessage::logMessage, LogMessage::logMessagePI, LogMessage::pid, LogMessage::sequenceId, LogMessage::severityLevel, LogMessage::sourceFile, LogMessage::sourceFilePI, LogMessage::sourceLine, LogMessage::subsystem, LogMessage::timeStamp, and LoggerCommon::wrapFormattedLogText().
void Logger::traceLog (LogEntrySubSystemType subsystem, LogEntrySeverityType severity, int pid, const char * sourceFile, int sourceLine, const char * p_logMessage, long arg1, long arg2, long arg3, long arg4, long arg5, long arg6) [static]
Method to handle enqueuing of the log messages.
Enqueue a log message for output Memory Management here: p_logMessage is assumed to be statically allocated memory when this method is used (printf style formatting arguments are passed in as well). For this reason, we only need to make a copy of the buffer for shared memory allocation. The 'logMessage' struct that we create on the first line here will be deleted (including its logMessage buffer--deleted by its destructor) when this method goes out of scope.
A performance optimization for this logger should be to create pool of logMessage structs on the heap and reuse them: reserve one here and fill its contents, then pass it into the log queue where it gets deleted on the other side once it is output to where-ever. NOTE: this pool should not use OPM (circular dependency).
References LogMessage::arg1, LoggerCommon::formatLogMessage(), LogMessage::isStringLog, LogMessage::logMessage, LogMessage::logMessagePI, LogMessage::pid, LogMessage::sequenceId, LogMessage::severityLevel, LogMessage::sourceFile, LogMessage::sourceFilePI, LogMessage::sourceLine, LogMessage::subsystem, LogMessage::timeStamp, and LoggerCommon::wrapFormattedLogText().
Referenced by setSubsystemLogLevel().
The documentation for this class was generated from the following files:
Logger.h
Logger.cpp