ConnectionSet Class Reference
Public Member Functions
ConnectionSet (string connectionSetName)
virtual ~ConnectionSet ()
void setUserid (string userid)
void setPassword (string password)
void setDriverName (string driverName)
void setConnectionType (ConnectionSetType connectionType)
void setConnectionString (string connectionString)
void setNumberConnections (int numberConnections)
void setDSN (string dsn)
int performActivation ()
int performDeactivation ()
DbConnectionHandle * reserveConnection ()
DbConnectionHandle * reserveConnectionNonBlocking ()
void releaseConnection (DbConnectionHandle *connectionHandle)
string toString ()
Constructor & Destructor Documentation
ConnectionSet::ConnectionSet (string connectionSetName)
Constructor
ConnectionSet::~ConnectionSet () [virtual]
Virtual Destructor
Member Function Documentation
int ConnectionSet::performActivation ()
Perform activation for the connection set. This includes connection establishment, error handling, and creation of the OPM pool for storing the active connections.
Returns
ERROR upon failure; otherwise OK
References OPM::createPool(), PgConnection::initialize(), and DbConnectionHandle::initialize().
int ConnectionSet::performDeactivation ()
Perform deactivation of the connection set. This should include connection tear down, error handling, and destruction of the OPM pool for the connections, but currently there is no OPM support for deallocating the pool of objects. We can loop through all of the 'Available' connection objects and perform a disconnect/shutdown. HOWEVER, this does assume that the application has released all of the connection objects back into the pool already (so that we can re-reserve them here).
Returns
ERROR upon failure; otherwise OK
References reserveConnectionNonBlocking(), and DbConnectionHandle::shutdown().
void ConnectionSet::releaseConnection (DbConnectionHandle * connectionHandle)
Method to release the DbConnection back into the Connection Set pool. This method is called from the similarly named static method in the DataManager.
DbConnectionHandle * ConnectionSet::reserveConnection ()
Method to retrieve a pointer to a DbConnection from the Connection Set pool. This method blocks until a DbConnection becomes available if they are all currently in use. This method is called from the similarly named static method in the DataManager.
DbConnectionHandle * ConnectionSet::reserveConnectionNonBlocking ()
Method to retrieve a pointer to a DbConnection from the Connection Set pool. This method does NOT block if there are no DbConnections available in the pool. NOTE that the pools are configured not to GROW and/or SHRINK. This method is called from the similarly named static method in the DataManager.
Returns
NULL if no DbConnection available
Referenced by performDeactivation().
void ConnectionSet::setConnectionString (string connectionString)
Set the Connection String associated with the connection
Referenced by DataManager::initialize().
void ConnectionSet::setConnectionType (ConnectionSetType connectionType)
Set the Connection Type associated with the connection
Referenced by DataManager::initialize().
void ConnectionSet::setDriverName (string driverName)
Set the Driver Name associated with the connection
Referenced by DataManager::initialize().
void ConnectionSet::setDSN (string dsn)
Set the DSN
Referenced by DataManager::initialize().
void ConnectionSet::setNumberConnections (int numberConnections)
Set the number of connections
Referenced by DataManager::initialize().
void ConnectionSet::setPassword (string password)
Set the Password associated with the connection
Referenced by DataManager::initialize().
void ConnectionSet::setUserid (string userid)
Set the Userid associated with the connection
Referenced by DataManager::initialize().
string ConnectionSet::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
The documentation for this class was generated from the following files:
ConnectionSet.h
ConnectionSet.cpp