AlarmEventMessage Class Reference
Public Member Functions
AlarmEventMessage (const MailboxAddress &sourceAddress, AlarmEventMessageType messageType, string neid, unsigned short managedObject, unsigned int managedObjectInstance, unsigned short alarmCode, unsigned short eventCode, unsigned int pid, unsigned int timeStamp, unsigned int sourceContextId=0, unsigned int destinationContextId=0)
virtual ~AlarmEventMessage ()
AlarmEventMessageType getMessageType () const
unsigned short getMessageId () const
string getNEID () const
unsigned short getManagedObject () const
unsigned int getManagedObjectInstance () const
unsigned short getAlarmCode () const
unsigned short getEventCode () const
unsigned int getPid () const
unsigned int getTimestamp () const
int serialize (MessageBuffer &buffer)
string toString ()
Static Public Member Functions
static MessageBase * deserialize (MessageBuffer *buffer)
Additional Inherited Members
Constructor & Destructor Documentation
AlarmEventMessage::AlarmEventMessage (const MailboxAddress & sourceAddress, AlarmEventMessageType messageType, string neid, unsigned short managedObject, unsigned int managedObjectInstance, unsigned short alarmCode, unsigned short eventCode, unsigned int pid, unsigned int timeStamp, unsigned int sourceContextId = 0, unsigned int destinationContextId = 0)
Constructor
Referenced by deserialize().
AlarmEventMessage::~AlarmEventMessage () [virtual]
Virtual Destructor
Member Function Documentation
MessageBase * AlarmEventMessage::deserialize (MessageBuffer * buffer) [static]
Subclassed deserialization / bootstrap implementation
References AlarmEventMessage().
unsigned short AlarmEventMessage::getAlarmCode () const
Returns the alarm code
unsigned short AlarmEventMessage::getEventCode () const
Returns the event code
unsigned short AlarmEventMessage::getManagedObject () const
Returns the managed object class
unsigned int AlarmEventMessage::getManagedObjectInstance () const
Returns the managed object instance
unsigned short AlarmEventMessage::getMessageId () const [virtual]
Returns the Message Id
Implements MessageBase .
AlarmEventMessageType AlarmEventMessage::getMessageType () const
Returns the Message Type (Alarm, Clear, EventReport)
string AlarmEventMessage::getNEID () const
Returns the NEID that the alarm applies to
unsigned int AlarmEventMessage::getPid () const
Returns the process id
unsigned int AlarmEventMessage::getTimestamp () const
Returns the timestamp
int AlarmEventMessage::serialize (MessageBuffer & buffer) [virtual]
Subclassed serialization implementation
Reimplemented from MessageBase .
References MessageBase::destinationContextId_, MessageBase::sourceAddress_, MessageBase::sourceContextId_, and MessageBase::versionNumber_.
string AlarmEventMessage::toString () [virtual]
String'ized debugging method
Returns
string representation of the contents of this object
Implements MessageBase .
References MessageBase::sourceAddress_, and MailboxAddress::toString().
The documentation for this class was generated from the following files:
AlarmEventMessage.h
AlarmEventMessage.cpp