MailboxHandle Class Reference
#include <MailboxHandle.h>
Public Member Functions
MailboxHandle (MailboxBase *mailboxPtr)
virtual ~MailboxHandle ()
virtual int post (MessageBase *messagePtr, const ACE_Time_Value *timeout=&ACE_Time_Value::zero)
virtual int getDebugValue ()
virtual void setDebugValue (int debugValue)
virtual bool isProxy ()
virtual MailboxAddress & getMailboxAddress ()
virtual unsigned int getSentCount ()
string toString ()
Protected Attributes
MailboxBase * mailboxPtr_
Detailed Description
MailboxHandle is a developer handle to a local or remote type mailbox.
The mailbox handles prevent application developers from getting direct references to the mailboxes themselves. This is the programmatic interface that developers use to access the mailbox functionality.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
MailboxHandle::MailboxHandle (MailboxBase * mailboxPtr)
Constructor. Stores a pointer to the mailbox
References MailboxBase::acquire(), MailboxHandle(), and mailboxPtr_.
Referenced by MailboxHandle().
MailboxHandle::~MailboxHandle () [virtual]
Virtual Destructor
References mailboxPtr_, and MailboxBase::release().
Member Function Documentation
int MailboxHandle::getDebugValue () [virtual]
Returns the Debug flag value for this mailbox.
References MailboxBase::getDebugValue(), and mailboxPtr_.
MailboxAddress & MailboxHandle::getMailboxAddress () [virtual]
Return the mailbox address
References MailboxBase::getMailboxAddress(), and mailboxPtr_.
Referenced by MailboxLookupService::find().
unsigned int MailboxHandle::getSentCount () [virtual]
Return the sent message counter value
References MailboxBase::getSentCount(), and mailboxPtr_.
bool MailboxHandle::isProxy () [virtual]
Return whether this mailbox is a remote proxy or not
References MailboxBase::isProxy(), and mailboxPtr_.
Referenced by MailboxLookupService::find().
int MailboxHandle::post (MessageBase * messagePtr, const ACE_Time_Value * timeout = &ACE_Time_Value::zero) [virtual]
Post a message to this mailbox
Returns
ERROR for an error; otherwise OK
References mailboxPtr_, and MailboxBase::post().
Referenced by FaultManager::processMailbox().
void MailboxHandle::setDebugValue (int debugValue) [virtual]
Sets the Debug flag value for this mailbox.
References mailboxPtr_, and MailboxBase::setDebugValue().
string MailboxHandle::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
Member Data Documentation
MailboxBase* MailboxHandle::mailboxPtr_ [protected]
Pointer to the encapsulated mailbox
Referenced by getDebugValue(), getMailboxAddress(), getSentCount(), isProxy(), MailboxHandle(), post(), setDebugValue(), and ~MailboxHandle().
The documentation for this class was generated from the following files:
MailboxHandle.h
MailboxHandle.cpp