ThreadTest Class Reference
#include <ThreadTest.h>
Public Member Functions
ThreadTest ()
virtual ~ThreadTest ()
void initialize ()
Static Public Member Functions
static void performTests (void)
static void performRestartTests (void)
Detailed Description
ThreadTest is the Unit Test for the Thread Monitoring, Recovery, and Restart
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
ThreadTest::ThreadTest ()
Constructor
ThreadTest::~ThreadTest () [virtual]
Virtual Destructor
Member Function Documentation
void ThreadTest::initialize ()
Initialization
References performRestartTests(), and performTests().
Referenced by performRestartTests().
void ThreadTest::performRestartTests (void) [static]
Perform Restart Tests
References initialize().
Referenced by initialize().
void ThreadTest::performTests (void) [static]
Perform Tests
Referenced by initialize().
The documentation for this class was generated from the following files:
ThreadTest.h
ThreadTest.cpp