UnboundedSMQueue< T > Class Template Reference
#include <UnboundedSMQueue.h>
Public Types
typedef ACE_Unbounded_Queue< T > BASE
Public Member Functions
UnboundedSMQueue (ACE_Allocator *allocator)
virtual ~UnboundedSMQueue ()
int enqueue_tail (const T &new_item, ACE_Allocator *allocator)
int dequeue_head (T &item, ACE_Allocator *allocator)
void delete_nodes (ACE_Allocator *allocator)
int is_empty (ACE_Allocator *allocator)
Detailed Description
template<class T>
*
class UnboundedSMQueue< T >
UnboundedSMQueue extends the ACE Unbounded Queue (for infinite re-growth) to add allocation support for Shared Memory. Items added to this queue get copied to Position Independent shared memory where they become accessible to other processes.
UnboundedSMQueue is built to be the basis for exchanging tracelog messages between processes and for exchanges between MsgMgr mailboxes in separate processes.
NOTE: Our Strategy for using Shared Memory is NOT to create/allocate pools of shared memory objects (which would use Position Independent pointers) that the applications would reference and use. Rather, we create our containers which enforce concurrency in shared memory (such as this queue), and then we pass process-local objects through the shared memory from one process to another. (ALSO NOTE: creating pools of objects in shared memory is the job of the in-memory database provider)
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
template<class T > UnboundedSMQueue< T >::UnboundedSMQueue (ACE_Allocator * allocator) [inline]
Constructor
Referenced by UnboundedSMQueue< T >::is_empty().
template<class T > virtual UnboundedSMQueue< T >::~UnboundedSMQueue () [inline], [virtual]
Virtual Destructor
Member Function Documentation
template<class T > void UnboundedSMQueue< T >::delete_nodes (ACE_Allocator * allocator) [inline]
Clear the Contents
Referenced by FaultSMQueue::clearQueue(), LoggerSMQueue::clearQueue(), and LocalSMMailboxQueue::clearQueue().
template<class T > int UnboundedSMQueue< T >::dequeue_head (T & item, ACE_Allocator * allocator) [inline]
Dequeue Method
Referenced by FaultSMQueue::dequeueAlarm(), LoggerSMQueue::dequeueLog(), and LocalSMMailboxQueue::dequeueMessage().
template<class T > int UnboundedSMQueue< T >::enqueue_tail (const T & new_item, ACE_Allocator * allocator) [inline]
Enqueue Method
Referenced by FaultSMQueue::enqueueAlarm(), LoggerSMQueue::enqueueLog(), and LocalSMMailboxQueue::enqueueMessage().
template<class T > int UnboundedSMQueue< T >::is_empty (ACE_Allocator * allocator) [inline]
Return if the queue is empty
References UnboundedSMQueue< T >::UnboundedSMQueue().
Referenced by FaultSMQueue::dequeueAlarm(), LoggerSMQueue::dequeueLog(), LocalSMMailboxQueue::dequeueMessage(), LoggerSMQueue::isEmpty(), FaultSMQueue::isEmpty(), and LocalSMMailboxQueue::isEmpty().
The documentation for this class was generated from the following file:
UnboundedSMQueue.h