GroupMailbox Class Reference
Public Member Functions
virtual bool rename (const MailboxAddress &newGroupAddress)
virtual int activate (MailboxOwnerHandle *mailboxOwnerHandle)
virtual int deactivate (MailboxOwnerHandle *mailboxOwnerHandle)
MailboxAddress & getMailboxAddress ()
string toString ()
Static Public Member Functions
static MailboxOwnerHandle * createMailbox (const MailboxAddress &groupAddress, unsigned int multicastLoopbackEnabled=TRUE, unsigned int multicastTTL=1)
Protected Member Functions
GroupMailbox (const MailboxAddress &groupAddress, unsigned int multicastLoopbackEnabled_, unsigned int multicastTTL_)
virtual ~GroupMailbox ()
Additional Inherited Members
Constructor & Destructor Documentation
GroupMailbox::GroupMailbox (const MailboxAddress & groupAddress, unsigned int multicastLoopbackEnabled_, unsigned int multicastTTL_) [protected]
Constructor - protected so that applications cannot create their own mailboxes and must use the static createMailbox() method
References GroupMailbox().
Referenced by GroupMailbox().
GroupMailbox::~GroupMailbox () [protected], [virtual]
Virtual Destructor. Protected since this is a reference counted object.
References MailboxBase::isShuttingDown_.
Member Function Documentation
int GroupMailbox::activate (MailboxOwnerHandle * mailboxOwnerHandle) [virtual]
Activate the mailbox. For security, one must possess an Owner Handle in order to activate the mailbox and register it with the Lookup Service.
Reimplemented from LocalMailbox .
References LocalMailbox::activate(), LocalMailbox::deactivate(), MailboxAddress::inetAddress, and MailboxBase::isActive().
MailboxOwnerHandle * GroupMailbox::createMailbox (const MailboxAddress & groupAddress, unsigned int multicastLoopbackEnabled = TRUE, unsigned int multicastTTL = 1) [static]
Allows applications to create a mailbox and get a handle to it.
Since we do not want applications to have direct access to a mailbox object this method is provided. Applications that create mailboxes use this method to get a handle to their mailbox rather than have direct access. The handle returned is a owner handle which has all the privileges of the actual mailbox (getMessage/post etc). This method creates the mailbox, activates it (which in turn registers it with the lookup service) and then creates an owner handle, acquires it and then returns that handle. Both the mailbox and the returned handle are created on the heap.
Parameters
groupAddress source mailbox address that this mailbox will have
multicastLoopbackEnabled set to TRUE to enable multicast loopback
multicastTTL If we experience problems with Multicast packets getting from one network to another, we need to probably change the TTL. By default, it is set to 1 to allow for only 1 hop (within the same subnet, routers will not forward). Also, setting to 0 will restrict to within the same host.
Returns
pointer to a mailbox owner handle
References MessageBuffer::areContentsProcessed(), MessageBuffer::clearBuffer(), ThreadManager::createThread(), MailboxBase::debugValue_, MessageBuffer::getBuffer(), MessageBase::getMessageId(), MessageBase::getSourceAddress(), MailboxBase::incrementReceivedCount(), MailboxAddress::inetAddress, MailboxAddress::locationType, LocalMailbox::post(), MessageFactory::recreateMessageFromBuffer(), MailboxBase::selectReactor_, MessageBuffer::setInsertPosition(), MessageBase::setPriority(), LocalMailbox::startReactor(), and MessageBase::toString().
Referenced by DiscoveryManager::initialize().
int GroupMailbox::deactivate (MailboxOwnerHandle * mailboxOwnerHandle) [virtual]
Deactivate the mailbox. For security, one must possess an Owner Handle in order to deactivate the mailbox and deregister it with the Lookup Service.
Reimplemented from LocalMailbox .
References LocalMailbox::deactivate(), and MailboxAddress::inetAddress.
MailboxAddress & GroupMailbox::getMailboxAddress () [virtual]
Return the mailbox group address
Implements MailboxBase .
References MailboxBase::isShuttingDown_.
bool GroupMailbox::rename (const MailboxAddress & newGroupAddress) [virtual]
Method to allow application to rename a mailbox's group address.
TBD: What are the redundancy implications and usage here??
Reimplemented from MailboxBase .
string GroupMailbox::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
The documentation for this class was generated from the following files:
GroupMailbox.h
GroupMailbox.cpp