LocalSMMailbox Class Reference
Public Member Functions
virtual int activate (MailboxOwnerHandle *mailboxOwnerHandle)
virtual int deactivate (MailboxOwnerHandle *mailboxOwnerHandle)
MailboxAddress & getMailboxAddress ()
string toString ()
Static Public Member Functions
static MailboxOwnerHandle * createMailbox (const MailboxAddress &localAddress)
Protected Member Functions
LocalSMMailbox (const MailboxAddress &localAddress, const char *queueName, const char *coordinatingMutexName)
virtual ~LocalSMMailbox ()
Additional Inherited Members
Constructor & Destructor Documentation
LocalSMMailbox::LocalSMMailbox (const MailboxAddress & localAddress, const char * queueName, const char * coordinatingMutexName) [protected]
Constructor - protected so that applications cannot create their own mailboxes and must use the static createMailbox() method
References MailboxBase::debugValue_, LocalSMMailbox(), and MailboxAddress::toString().
Referenced by LocalSMMailbox().
LocalSMMailbox::~LocalSMMailbox () [protected], [virtual]
Virtual Destructor. Protected since this is a reference counted object.
References MailboxBase::isShuttingDown_.
Member Function Documentation
int LocalSMMailbox::activate (MailboxOwnerHandle * mailboxOwnerHandle) [virtual]
Activate the mailbox. For security, one must possess an Owner handle to activate the mailbox and register it with the Lookup Service.
Reimplemented from LocalMailbox .
References LocalMailbox::activate(), ThreadManager::createThread(), and MailboxBase::isActive().
MailboxOwnerHandle * LocalSMMailbox::createMailbox (const MailboxAddress & localAddress) [static]
Allows applications to create a mailbox and get a handle to it.
Since we do not want applications to have direct access to a mailbox object this method is provided. Applications that create mailboxes use this method to get a handle to their mailbox rather than have direct access. The handle returned is a owner handle which has all the privileges of the actual mailbox (getMessage/post etc). This method creates the mailbox, activates it (which in turn registers it with the lookup service) and then creates an owner handle, acquires it and then returns that handle. Both the mailbox and the returned handle are created on the heap.
References ThreadManager::createThread(), MailboxAddress::locationType, MailboxAddress::mailboxName, MailboxBase::selectReactor_, LocalSMMailboxQueue::setupQueue(), and LocalMailbox::startReactor().
int LocalSMMailbox::deactivate (MailboxOwnerHandle * mailboxOwnerHandle) [virtual]
Deactivate the mailbox. For security, one must possess an Owner handle to deactivate the mailbox and deregister it with the Lookup Service.
Reimplemented from LocalMailbox .
References LocalMailbox::deactivate().
MailboxAddress & LocalSMMailbox::getMailboxAddress () [virtual]
Return the mailbox address
Reimplemented from LocalMailbox .
References MessageBuffer::assignBuffer(), LocalSMBuffer::bufferLength, LocalSMBuffer::bufferPI, MessageBuffer::clearBuffer(), MailboxBase::debugValue_, LocalSMMailboxQueue::dequeueMessage(), MessageBase::getMessageId(), MessageBase::getSourceAddress(), MailboxBase::incrementReceivedCount(), MailboxAddress::inetAddress, MailboxBase::isActive(), LocalSMMailboxQueue::isEmpty(), LocalMailbox::post(), LocalSMBuffer::priorityLevel, MessageFactory::recreateMessageFromBuffer(), LocalSMBuffer::reset(), MessageBuffer::setInsertPosition(), MessageBase::setPriority(), and MessageBase::toString().
string LocalSMMailbox::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
The documentation for this class was generated from the following files:
LocalSMMailbox.h
LocalSMMailbox.cpp