MessageTestGroup Class Reference
#include <MessageTestGroup.h>
Public Member Functions
MessageTestGroup ()
virtual ~MessageTestGroup ()
void processMailbox ()
MailboxOwnerHandle * getOwnerHandle ()
string toString ()
Static Public Member Functions
static MessageTestGroup * getInstance ()
Detailed Description
MessageTestGroup is a collection of unit test procedures for the MsgMgr framework. This class deals exclusively with Group Mailboxes.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
MessageTestGroup::MessageTestGroup ()
Constructor
Referenced by toString().
MessageTestGroup::~MessageTestGroup () [virtual]
Virtual Destructor
Member Function Documentation
MessageTestGroup * MessageTestGroup::getInstance () [static]
Returns static singleton instance
Referenced by toString().
MailboxOwnerHandle * MessageTestGroup::getOwnerHandle ()
Returns pointer to the owner handle of the main mailbox
References MessageTestGroupMessage::deserialize().
Referenced by toString().
void MessageTestGroup::processMailbox ()
Start the mailbox processing loop
References MessageTest1Message::toString(), and MessageTestGroupMessage::toString().
Referenced by toString().
string MessageTestGroup::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
References getInstance(), getOwnerHandle(), MessageTestGroup(), and processMailbox().
The documentation for this class was generated from the following files:
MessageTestGroup.h
MessageTestGroup.cpp