MessageBlockWrapper Class Reference
#include <MessageBlockWrapper.h>
Public Member Functions
MessageBlockWrapper (int blockSize=0)
virtual ~MessageBlockWrapper ()
void clean ()
void base (char *data, size_t size)
char * base (void) const
void msg_priority (unsigned long priority)
string toString ()
Static Public Member Functions
static OPMBase * initialize (int initializer)
Additional Inherited Members
Detailed Description
MessageBlockWrapper is a wrapper class around the ACE_Message_Block class.
This simple wrapper exists so that we can create a pool of ACE_Message_Blocks inside the OPM.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
MessageBlockWrapper::MessageBlockWrapper (int blockSize = 0)
Constructor
Referenced by initialize().
MessageBlockWrapper::~MessageBlockWrapper () [virtual]
Virtual Destructor
Member Function Documentation
void MessageBlockWrapper::base (char * data, size_t size)
Overridden ACE_Message_Block Method
Referenced by LocalMailbox::post().
char * MessageBlockWrapper::base (void) const
Overridden ACE_Message_Block Method
void MessageBlockWrapper::clean () [virtual]
OPMBase clean method gets called when the object gets released back into its pool
Implements OPMBase .
OPMBase * MessageBlockWrapper::initialize (int initializer) [static]
OPMBase static initializer method for bootstrapping the objects
References MessageBlockWrapper().
Referenced by LocalMailbox::LocalMailbox().
void MessageBlockWrapper::msg_priority (unsigned long priority)
Overridden ACE_Message_Block Method
string MessageBlockWrapper::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
The documentation for this class was generated from the following files:
MessageBlockWrapper.h
MessageBlockWrapper.cpp