MailboxProcessor Class Reference
Public Member Functions
MailboxProcessor (MessageHandlerList *handlerList, MailboxOwnerHandle &mailboxOwnerHandle)
virtual ~MailboxProcessor ()
void processMailbox (int numberThreads=1)
Constructor & Destructor Documentation
MailboxProcessor::MailboxProcessor (MessageHandlerList * handlerList, MailboxOwnerHandle & mailboxOwnerHandle)
Constructor. Associate a Mailbox with its Message Handler List
References MailboxProcessor().
Referenced by MailboxProcessor().
MailboxProcessor::~MailboxProcessor () [virtual]
Virtual Destructor.
Member Function Documentation
void MailboxProcessor::processMailbox (int numberThreads = 1)
Reads messages from the queue and calls the appropriate message handler.
If the queue is empty it will block. After the message has been processed it will be deleted (or it will be checked in to the OPM if it is an OPM managed object). So applications SHOULD NOT DELETE messages when they handle them. If the mailbox has not be activated by the application, then getMessage() will return NULL, and this method will return.
Parameters
numberThreads if more than 1 thread is given as a parameter, then a ThreadManager thread pool will be created to service the Mailbox queue. NOTE!! If the developer chooses to use a ThreadPool for processing the the Mailbox queue, the developer is responsible for ensuring that all of the Mailbox Handlers are THREAD SAFE!!!
References ThreadManager::createThreadPool(), MessageBase::deleteMessage(), MessageHandlerList::find(), MailboxOwnerHandle::getMessage(), and MessageBase::getMessageId().
Referenced by ResourceMonitor::processMailbox(), ProcessManager::processMailbox(), FaultManager::processMailbox(), and DiscoveryManager::processMailbox().
The documentation for this class was generated from the following files:
MailboxProcessor.h
MailboxProcessor.cpp