SystemInfo Class Reference
#include <SystemInfo.h>
Public Member Functions
virtual ~SystemInfo ()
Static Public Member Functions
static const string & getLocalNEID ()
static unsigned int getShelfNumber ()
static unsigned int getSlotNumber ()
Detailed Description
SystemInfo provides static access to system wide attributes such as NEID, Shelf Number, Slot Number, etc.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
virtual SystemInfo::~SystemInfo () [virtual]
Virtual Destructor
Member Function Documentation
const string & SystemInfo::getLocalNEID () [static]
Return the local card's NEID (Network Element Id). This method reads the Local NEID from the environment the first time it is called. After that, it caches the value and just returns the cached value (so a complete restart is needed if this value needs to change).
Returns
the 9 digit NEID string, or it returns `000000000` upon failure if it could not be taken from the environment, its length is not 9, or its characters are not digits.
Referenced by OSResource::checkCPUUsage(), OSResource::checkDiskUsage(), OSResource::checkMemoryUsage(), DiscoveryManager::DiscoveryManager(), ResourceMonitor::initialize(), ProcessManager::initialize(), and FaultManager::initialize().
unsigned int SystemInfo::getShelfNumber () [static]
Return the local card's shelf number
Referenced by ProcessManager::initialize().
unsigned int SystemInfo::getSlotNumber () [static]
Return the local card's slot number in the shelf
Referenced by ProcessManager::initialize().
The documentation for this class was generated from the following files:
SystemInfo.h
SystemInfo.cpp