MessageFactory Class Reference
Public Types
typedef map< unsigned short, MessageBootStrapMethod > MessageFactoryRegistry
Public Member Functions
virtual ~MessageFactory ()
Static Public Member Functions
static void registerSupport (unsigned short messageId, MessageBootStrapMethod &messageCreator)
static MessageBase * recreateMessageFromBuffer (MessageBuffer &buffer)
static void listRegisteredMessages ()
Member Typedef Documentation
typedef map<unsigned short, MessageBootStrapMethod> MessageFactory::MessageFactoryRegistry
Map to implement the registry for mapping Message Bootstrap methods to their Message Ids
Constructor & Destructor Documentation
MessageFactory::~MessageFactory () [virtual]
Virtual Destructor
Member Function Documentation
void MessageFactory::listRegisteredMessages () [static]
Output registered message Ids
MessageBase * MessageFactory::recreateMessageFromBuffer (MessageBuffer & buffer) [static]
Convert the buffer back into its Message object form
Referenced by DistributedMailbox::createMailbox(), GroupMailbox::createMailbox(), and LocalSMMailbox::getMailboxAddress().
void MessageFactory::registerSupport (unsigned short messageId, MessageBootStrapMethod & messageCreator) [static]
Allows applications to register Message Factory support for a specified Message Id and supplied static initializer (bootstrap) method.
Developers should note that the static bootstrap method is most usually the overriden static 'deserialize' method implemented within the Message class (inherited from MessageBase). However, if complex deserialization logic is required (or if deserialization is dependent on application variables), any static bootstrap method can be supplied here.
Referenced by DiscoveryManager::initialize().
The documentation for this class was generated from the following files:
MessageFactory.h
MessageFactory.cpp