DbConnectionHandle Class Reference
#include <DbConnectionHandle.h>
Public Member Functions
DbConnectionHandle ()
virtual ~DbConnectionHandle ()
void clean ()
void addUserDefinedIdentifier (string &identifier)
string & getUserDefinedIdentifier ()
void clearUserDefinedIdentifier ()
int checkConnectionHealth ()
int executeCommand (string &command)
int executeCommand (const char *command)
int executeCommandWithParams (const char *command, int numberParams, const char *const *paramValues, const int *paramLengths, const int *isBinary)
int beginTransaction ()
int rollbackTransaction ()
int commitTransaction ()
int initializePreparedCommand (const char *statementName, const char *sqlCommand, int numberParams, const DataManagerFieldType *paramTypeArray)
int executePreparedCommand (const char *statementName, int numberParams, const char *const *paramValues, const int *paramLengths, const int *isBinary)
int closeCommandResult ()
int getColumnCount ()
string getColumnName (int columnIndex)
int getColumnIndex (const char *columnName)
int getRowCount ()
string getStringValueAt (int rowIndex, int columnIndex)
short getShortValueAt (int rowIndex, int columnIndex)
int getIntValueAt (int rowIndex, int columnIndex)
bool getBooleanValueAt (int rowIndex, int columnIndex)
string getTimestampValueAt (int rowIndex, int columnIndex)
bool isValueNULL (int rowIndex, int columnIndex)
int getValueLength (int rowIndex, int columnIndex)
int shutdown ()
string toString ()
Static Public Member Functions
static OPMBase * initialize (int initializer)
Friends
class DataManager
class ConnectionSet
Additional Inherited Members
Detailed Description
DbConnectionHandle class provides a wrapper around the 'real' DbConnection object.
The strategy here is to prevent the application designer user from gaining access to the DbConnection object and doing something they shouldn't.
Additionally, DbConnectionHandle stores the Thread Id of the thread that reserved the connection. For each operation, it checks to see if the thread that is performing the operation is the same thread that reserved the connection. If it is determined to be different, this can indicate that the application is using a stale pointer to a connection that has already been release back into the pool. The database driver API is 'mostly' thread safe. However, the architecture of the driver is such that it is intended for use by a single thread--this means that once a query has been performed on the connection and the result set has been returned to the client side via the connection, another query should not be issued until the result set has been completely analyzed (all processing on it complete), and the result set has been closed.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
DbConnectionHandle::DbConnectionHandle ()
Constructor
Referenced by initialize().
DbConnectionHandle::~DbConnectionHandle () [virtual]
Virtual Destructor
Member Function Documentation
void DbConnectionHandle::addUserDefinedIdentifier (string & identifier)
Allows the Application Developer to 'tag' a particular connection (through this connection handle) with some user-defined identification data. This data tag will be preserved even if the connection it checked back into the pool (released) and then reserved again. Thus, the developer can identify which connection was used for which previous tasks.
References DbConnection::addUserDefinedIdentifier().
int DbConnectionHandle::beginTransaction ()
Begin a transaction on this connection. Autocommit is ENABLED for all executed commands UNLESS beginTransaction has been called--that is, beginTransaction disabled autocommit until either rollbackTransaction or commitTransaction is called.
References DbConnection::beginTransaction().
int DbConnectionHandle::checkConnectionHealth ()
Check the health of the database connection.
Returns
OK if the connection is valid; otherwise ERROR
References DbConnection::checkConnectionHealth().
void DbConnectionHandle::clean () [virtual]
Inherited from OPMBase. Pure Virtual method will be called before releasing the object back into the OPM pool.
Implements OPMBase .
void DbConnectionHandle::clearUserDefinedIdentifier ()
Clears the user-defined data and resets the internal string to empty
References DbConnection::clearUserDefinedIdentifier().
int DbConnectionHandle::closeCommandResult ()
If an outstanding/open resultSet exists for this connection, then close it. return ERROR for failure; otherwise OK
References DbConnection::closeCommandResult().
Referenced by OSResource::initialize(), and FaultManager::processMailbox().
int DbConnectionHandle::commitTransaction ()
Commit the outstanding transaction on this connection
References DbConnection::commitTransaction().
int DbConnectionHandle::executeCommand (string & command)
Execute an SQL command to the database using this connection. This command can be a QUERY, UPDATE, INSERT, or DELETE operation.
Returns
OK if the command was executed successfully; otherwise ERROR
References DbConnection::executeCommand().
Referenced by OSResource::initialize(), and FaultManager::processMailbox().
int DbConnectionHandle::executeCommand (const char * command)
Execute an SQL command to the database using this connection. This command can be a QUERY, UPDATE, INSERT, or DELETE operation.
Returns
OK if the command was executed successfully; otherwise ERROR
References DbConnection::executeCommand().
int DbConnectionHandle::executeCommandWithParams (const char * command, int numberParams, const char *const * paramValues, const int * paramLengths, const int * isBinary)
Execute an SQL command to the database using this connection. This command can be a QUERY, UPDATE, INSERT or DELETE operation.
Parameters
numberParams number of passed in parameters in the char* array
paramValues specifies the actual values of the parameters (char* array)
paramLengths specifies the actual data lengths of binary-format parameters. It is ignored for null parameters and text-format parameters. The array pointer may be null when there are no binary parameters.
isBinary array for each param value to determine if the value is binary or textual (TRUE for binary / FALSE for text). The array pointer may be null when there are no binary parameters.
Returns
OK if the command was executed successfully; otherwise ERROR
References DbConnection::executeCommandWithParams().
int DbConnectionHandle::executePreparedCommand (const char * statementName, int numberParams, const char *const * paramValues, const int * paramLengths, const int * isBinary)
Execute an SQL prepared statement command to the database using this connection. This command can be a QUERY, UPDATE, INSERT, or DELETE operation.
Parameters
statementName string name assigned to the statement when initializePreparedCommand is called.
numberParams number of passed in parameters in the char* array
paramValues specifies the actual values of the parameters (char* array)
paramLengths specifies the actual data lengths of binary-format parameters. It is ignored for null parameters and text-format parameters. The array pointer may be null when there are no binary parameters.
isBinary array for each param value to determine if the value is binary or textual (TRUE for binary / FALSE for text). The array pointer may be null when there are no binary parameters.
Returns
OK if the command was successfully executed; otherwise ERROR
References DbConnection::executePreparedCommand().
bool DbConnectionHandle::getBooleanValueAt (int rowIndex, int columnIndex)
Return the value at the specified column/row location in the current commandResult. The value returned will be a boolean type. NOTE: Use of this method requires that the developer be aware of the of the schema and result field type.
References DbConnection::getBooleanValueAt().
int DbConnectionHandle::getColumnCount ()
Return the number of columns in the current commandResult structure
References DbConnection::getColumnCount().
Referenced by OSResource::initialize(), and FaultManager::processMailbox().
int DbConnectionHandle::getColumnIndex (const char * columnName)
Return the column index based on the specified column name
Returns
ERROR upon failure; otherwise the column Index >= 0
References DbConnection::getColumnIndex().
Referenced by OSResource::initialize(), and FaultManager::processMailbox().
string DbConnectionHandle::getColumnName (int columnIndex)
Return the specified column header name in the current commandResult
References DbConnection::getColumnName().
Referenced by FaultManager::processMailbox().
int DbConnectionHandle::getIntValueAt (int rowIndex, int columnIndex)
Return the value at the specified column/row location in the current commandResult. The value returned will be a 4-byte integer type. NOTE: Use of this method requires that the developer be aware of the of the schema and result field type.
References DbConnection::getIntValueAt().
Referenced by OSResource::initialize(), and FaultManager::processMailbox().
int DbConnectionHandle::getRowCount ()
Return the number of rows in the current commandResult
References DbConnection::getRowCount().
Referenced by OSResource::initialize(), and FaultManager::processMailbox().
short DbConnectionHandle::getShortValueAt (int rowIndex, int columnIndex)
Return the value at the specified column/row location in the current commandResult. The value returned will be a 2-byte short type. NOTE: Use of this method requires that the developer be aware of the of the schema and result field type.
References DbConnection::getShortValueAt().
Referenced by OSResource::initialize(), and FaultManager::processMailbox().
string DbConnectionHandle::getStringValueAt (int rowIndex, int columnIndex)
Return the value at the specified column/row location in the current commandResult. The value is returned as a string. NOTE: Use of this method requires that the developer be aware of the of the schema and result field type.
References DbConnection::getStringValueAt().
Referenced by FaultManager::processMailbox().
string DbConnectionHandle::getTimestampValueAt (int rowIndex, int columnIndex)
Return the value at the specified column/row location in the current commandResult. The value returned will be a string. NOTE: Use of this method requires that the developer be aware of the of the schema and result field type.
References DbConnection::getTimestampValueAt().
Referenced by FaultManager::processMailbox().
string & DbConnectionHandle::getUserDefinedIdentifier ()
Returns the user-defined identifier data
Returns
empty string if no user-defined data has been previously set
References DbConnection::getUserDefinedIdentifier().
int DbConnectionHandle::getValueLength (int rowIndex, int columnIndex)
Returns the actual length of a field value in bytes
References DbConnection::getValueLength().
OPMBase * DbConnectionHandle::initialize (int initializer) [static]
Inherited from OPMBase. Method will be called when the pool is created with these objects. This method bootstraps the creation of each object. THIS OVERRIDES the initialize method in OPMBASE (can't be both virtual and static)
Parameters
initializer - Initializer integer or pointer to initialization data needed by the object.
Returns
Pointer to the new OPMBase object.
References DbConnectionHandle().
Referenced by ConnectionSet::performActivation().
int DbConnectionHandle::initializePreparedCommand (const char * statementName, const char * sqlCommand, int numberParams, const DataManagerFieldType * paramTypeArray)
Setup for a prepared statement command on this connection
Parameters
statementName string name arbitrarily assigned to the statement
sqlCommand QUERY, UPDATE, INSERT, or DELETE sql operation.
numberParams number of passed in parameters in the char* array
paramTypeArray array of field types because the database cannot infer the field type formatting without it.
Returns
OK if the preparation was successful; otherwise ERROR
References DbConnection::initializePreparedCommand().
bool DbConnectionHandle::isValueNULL (int rowIndex, int columnIndex)
Returns true if the field Value is NULL
References DbConnection::isValueNULL().
int DbConnectionHandle::rollbackTransaction ()
Rollback a transaction on this connection
References DbConnection::rollbackTransaction().
int DbConnectionHandle::shutdown ()
Close the socket connection to the database server
Returns
ERROR on failure; otherwise OK
References DbConnection::shutdown().
Referenced by ConnectionSet::performDeactivation().
string DbConnectionHandle::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
Friends And Related Function Documentation
friend class ConnectionSet [friend]
ConnectionSet is a friend to allow access to associate/dissociate connections (Required unless we give application designer access to these methods)
friend class DataManager [friend]
DataManager has to be a friend to allow calling getConnectionSetName (Required unless we give application designer access to these methods)
The documentation for this class was generated from the following files:
DbConnectionHandle.h
DbConnectionHandle.cpp