ems.guiclient.Session_IImpl Class Reference
Public Member Functions
Session_IImpl ()
ems.idls.session.Session_I associatedSession ()
void ping ()
void endSession ()
void setAssociatedSession (ems.idls.session.Session_I associatedSession)
final String toString ()
Public Attributes
ems.idls.session.Session_I associatedSession_ = null
Detailed Description
Session_IImpl extends from the Session_IPOA skeleton file (server implementation) that was created from running the idlj Java IDL compiler on the session.IDL file.
Here we add the Gui Client's implementation for the session interface.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
ems.guiclient.Session_IImpl.Session_IImpl () [inline]
Default Constructor
Member Function Documentation
ems.idls.session.Session_I ems.guiclient.Session_IImpl.associatedSession () [inline]
Return a reference to the remote session for determining communication validity
Implements ems.idls.session.Session_IOperations .
References ems.guiclient.Session_IImpl.associatedSession_.
Referenced by ems.guiclient.Session_IImpl.setAssociatedSession().
void ems.guiclient.Session_IImpl.endSession () [inline]
Respond to a remotely invoked End Session request
Implements ems.idls.session.Session_IOperations .
void ems.guiclient.Session_IImpl.ping () [inline]
Respond to a remotely invoked Ping method
Implements ems.idls.session.Session_IOperations .
void ems.guiclient.Session_IImpl.setAssociatedSession (ems.idls.session.Session_I associatedSession) [inline]
Store the associated session
References ems.guiclient.Session_IImpl.associatedSession(), and ems.guiclient.Session_IImpl.associatedSession_.
Referenced by ems.guiclient.GuiClient.initializeOrb().
final String ems.guiclient.Session_IImpl.toString () [inline]
String'ized debugging method
Returns
string representation of the contents of this object
Member Data Documentation
ems.idls.session.Session_I ems.guiclient.Session_IImpl.associatedSession_ = null
Reference to the associated session
Referenced by ems.guiclient.Session_IImpl.associatedSession(), and ems.guiclient.Session_IImpl.setAssociatedSession().
The documentation for this class was generated from the following file:
Session_IImpl.java