DataManagerTest Class Reference
#include <DataManagerTest.h>
Public Member Functions
DataManagerTest ()
~DataManagerTest ()
int initialize ()
void cleanup ()
int runTest1 ()
int runTest2 ()
int runTest3 ()
int runTest4 ()
int runTest5 ()
Detailed Description
Test class exercises the Data Manager
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
DataManagerTest::DataManagerTest ()
Default Constructor
Referenced by runTest5().
DataManagerTest::~DataManagerTest ()
Default Destructor
Member Function Documentation
void DataManagerTest::cleanup ()
Clean up the connection / release
Referenced by runTest5().
int DataManagerTest::initialize ()
Initialize method. Initialize the DataManager and setup connections to the database.
Returns
ERROR on failure; otherwise OK
Referenced by runTest5().
int DataManagerTest::runTest1 ()
Test method: Basic Perform Testing of operations on the database using execCommand: a simple query and results parsing
Returns
ERROR on failure; otherwise OK
Referenced by runTest4(), and runTest5().
int DataManagerTest::runTest2 ()
Test method: Parameterized arguments to the sql statement Perform testing of execCommandWithParams.
Returns
ERROR on failure; otherwise OK
Referenced by runTest5().
int DataManagerTest::runTest3 ()
Test method: Test boolean type specific results Perform Testing of getBooleanValueAt on query results.
Returns
ERROR on failure; otherwise OK
Referenced by runTest5().
int DataManagerTest::runTest4 ()
Test method: Test a multistep transaction
Returns
ERROR on failure; otherwise OK
References runTest1().
Referenced by runTest5().
int DataManagerTest::runTest5 ()
Test method: Test preparing and executing a Prepared statement
Returns
ERROR on failure; otherwise OK
References cleanup(), DataManagerTest(), initialize(), runTest1(), runTest2(), runTest3(), runTest4(), and runTest5().
Referenced by runTest5().
The documentation for this class was generated from the following files:
DataManagerTest.h
DataManagerTest.cpp