MessageTest Class Reference
#include <MessageTest.h>
Public Member Functions
MessageTest ()
virtual ~MessageTest ()
void processMailbox ()
MailboxOwnerHandle * getOwnerHandle ()
string toString ()
Static Public Member Functions
static MessageTest * getInstance ()
Detailed Description
MessageTest is a collection of unit test procedures for the MsgMgr framework.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
MessageTest::MessageTest ()
Constructor
Referenced by toString().
MessageTest::~MessageTest () [virtual]
Virtual Destructor
Member Function Documentation
MessageTest * MessageTest::getInstance () [static]
Returns static singleton instance
Referenced by toString().
MailboxOwnerHandle * MessageTest::getOwnerHandle ()
Returns pointer to the owner handle of the main mailbox
Referenced by toString().
void MessageTest::processMailbox ()
Start the mailbox processing loop
References MessageTest1Message::toString(), and MessageTest2Message::toString().
Referenced by toString().
string MessageTest::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
References getInstance(), getOwnerHandle(), MessageTest(), and processMailbox().
The documentation for this class was generated from the following files:
MessageTest.h
MessageTest.cpp