CliMenuPlatformConfig Class Reference
#include <CliMenuPlatformConfig.h>
Public Member Functions
CliMenuPlatformConfig ()
virtual ~CliMenuPlatformConfig ()
void initialize (platformConfig::platformConfig_I_ptr platformConfig_I_ptr)
string getLogLevels ()
void setLogLevel (int subsystem, int severityLevel)
Additional Inherited Members
Detailed Description
CliMenuPlatformConfig contains static handler methods for platform configuration requests.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
CliMenuPlatformConfig::CliMenuPlatformConfig ()
Constructor
CliMenuPlatformConfig::~CliMenuPlatformConfig () [virtual]
Virtual Destructor
Member Function Documentation
string CliMenuPlatformConfig::getLogLevels ()
Retrieve all of the subsystem / severity log level pairs from the agent
Referenced by CliMenuController::initialize().
void CliMenuPlatformConfig::initialize (platformConfig::platformConfig_I_ptr platformConfig_I_ptr)
Initialization Method
Referenced by CliMenuController::initialize().
void CliMenuPlatformConfig::setLogLevel (int subsystem, int severityLevel)
Set the log level severity based on the subsystem id
Referenced by CliMenuController::initialize().
The documentation for this class was generated from the following files:
CliMenuPlatformConfig.h
CliMenuPlatformConfig.cpp