LogProcessor Class Reference
Public Member Functions
LogProcessor ()
virtual ~LogProcessor ()
int initialize (OutputModeType outputMode, char *logFile, int numberKeptLogFiles, int sizeKeptLogFiles)
void processLogs ()
Static Public Member Functions
static void catchShutdownSignal ()
Constructor & Destructor Documentation
LogProcessor::LogProcessor ()
Constructor
Referenced by processLogs().
LogProcessor::~LogProcessor () [virtual]
Virtual Destructor
Member Function Documentation
void LogProcessor::catchShutdownSignal () [static]
Catch the shutdown signal and begin the graceful shutdown
References LoggerSMQueue::dequeueLog(), and LoggerSMQueue::isEmpty().
Referenced by initialize().
int LogProcessor::initialize (OutputModeType outputMode, char * logFile, int numberKeptLogFiles, int sizeKeptLogFiles)
Initialize the Log Processor.
Parameters
outputMode to file, stdout/err, or syslog
logFile the filename if -f file output mode is selected
numberKeptLogFiles number of log files to preserve during rollover (for -f file mode only)
sizeKeptLogFiles size of each log file to allow prior to rollover (for -f file mode only)
Returns
OK on success; otherwise ERROR.
References catchShutdownSignal(), and LoggerSMQueue::setupQueue().
Referenced by processLogs().
void LogProcessor::processLogs ()
Start the log processing loop. This method blocks forever.
References LoggerSMQueue::dequeueLog(), LoggerCommon::formatLogMessage(), initialize(), LoggerSMQueue::isEmpty(), LogProcessor(), processLogs(), LogMessage::severityLevel, and LoggerCommon::wrapFormattedLogText().
Referenced by processLogs().
The documentation for this class was generated from the following files:
LogProcessor.h
LogProcessor.cpp