ClientAgent Class Reference
#include <ClientAgent.h>
Public Member Functions
ClientAgent ()
virtual ~ClientAgent ()
void processMailbox ()
int initialize (bool dottedDecimalIORFlag, bool debugFlag, string &debugLevel, string &debugFilename, string &endPointString, string &initRef, string &defaultInitRef)
string toString ()
Static Public Member Functions
static void catchShutdownSignal ()
Detailed Description
CORBA Enabled Agent for receiving and processing client commands from the various client interfaces.
ClientAgent implements the CORBA Server for handling the various client interfaces. This module uses the ACE/TAO Corba Orb, which is fully OMG CORBA 2.3 compliant.
Note: Previous versions of the TAO Orb used TAO Exception Handling Macros to make the Standard Corba Exceptions compatible with platforms that do not support native C++ exception handling constructs. These TAO specific Macros have now been deprecated (they now cause compiler errors); they have been replaced with the base ACE Exception Handling Macros. However, since our development platform WILL ALWAYS support native C++ exception handling, we are foregoing the use of the ACE Macros, and we will ONLY support the native exception handling for simplicity.
ClientAgent accepts the following startup options: -l Local Logger Mode only (do not enqueue logs to shared memory) -h Restricts the use of hostnames in IORs. Invokes -ORBDottedDecimalAddresses 1 on the Orb -d Enable debug messages from within the Orb. Invokes -ORBDebug on the Orb. -v <Debug level>=``> Sets the debug level within the Orb (Max is 10). Invokes -ORBDebugLevel on the Orb. -f <log filename>=``> Sets the log filename for Orb debug logs. Invokes -ORBLogFile on the Orb. (Default is stdout) -e <Endpoint> Orb listens for connections on the interfaces specified by the endpoint URL (Invokes -ORBListenEndpoints) -i <Initial reference>=``> URL the Orb uses for initial resolution of Naming Service (corbaloc) (Invokes -ORBInitRef) -r <Default init=`` ref>=``> URL the Orb uses for default initial resolution of Naming Service (corbaloc) (Invokes -ORBDefaultInitRef)
Note that the correct syntax for -i (the ORBInitRef) -ORBInitRef is: NameService=corbaloc:iiop:localhost:12345/NameService -- or -- NameService=iiop://localhost:12345/NameService The former (corbaloc) syntax is the standard (compliant with the Interoperable Naming Service specification) syntax. The latter syntax is TAO-specific and is deprecated.
Client Agent implements the following IDL interfaces: -session Performs heartbeat monitoring (bidirectionally) between agent and its clients -platformConfig Handles get/set requests for the following platform configuration data sections: -- Log Level configuration, When updating log levels at runtime, the Agent will set the the new log levels in shared memory for all of the Log clients to use as well as set the same values in the database for persistence. These log level values will be read by the Agent upon startup each time and set in shared memory. -alarms Alarm Management and notification interface
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
ClientAgent::ClientAgent ()
Constructor
Referenced by toString().
ClientAgent::~ClientAgent () [virtual]
Virtual Destructor
Member Function Documentation
void ClientAgent::catchShutdownSignal () [static]
Catch the shutdown signal and begin the graceful shutdown
Referenced by initialize().
int ClientAgent::initialize (bool dottedDecimalIORFlag, bool debugFlag, string & debugLevel, string & debugFilename, string & endPointString, string & initRef, string & defaultInitRef)
Perform ClientAgent initialization
Parameters
dottedDecimalIORFlag If true, fore-go the use of hostnames in IORs. Instead use IP Addresses
debugFlag If true, enable the Orb inner debug logging
debugLevel Max is 10 -- the most verbose logging
debugFilename Redirect Orb debug logs to a file instead of stdout
endPointString On a multihomed host, instruct the Orb to use the interface described by this endpoint
initRef Use the Interoperable Naming Service url for locating Naming Service reference
defaultInitRef Use the INS url for default reference resolving
Returns
ERROR upon failure; otherwise OK
References catchShutdownSignal().
Referenced by toString().
void ClientAgent::processMailbox ()
Start the mailbox processing loop
Referenced by toString().
string ClientAgent::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
References ClientAgent(), initialize(), and processMailbox().
The documentation for this class was generated from the following files:
ClientAgent.h
ClientAgent.cpp