FaultSMQueue Class Reference
#include <FaultSMQueue.h>
Public Types
typedef UnboundedSMQueue< FaultMessage > FAULTSMQUEUE
Public Member Functions
FaultSMQueue (const char *queueName, const char *coordinatingMutexName)
virtual ~FaultSMQueue ()
int setupQueue ()
int enqueueAlarm (FaultMessage &message)
int dequeueAlarm (FaultMessage &message)
void clearQueue ()
bool isEmpty ()
string toString ()
Detailed Description
FaultSMQueue sets up an Unbounded Queue in Shared Memory for the purpose of raising and clearing FaultMessageType messages (alarms, clear alarms, and informational event reports) to the Fault Manager which will raise those to the EMS.
This shared memory queue uses the Position Independent Malloc/Allocation factory in ACE, and it handles queue growth using the automatic OS exception handling facilities to trap SIGSEGV and perform an ACE::remap.
Author
Stephen Horton
Revision
1
Member Typedef Documentation
typedef UnboundedSMQueue<FaultMessage> FaultSMQueue::FAULTSMQUEUE
Shared Memory Queue type for FaultMessages
Constructor & Destructor Documentation
FaultSMQueue::FaultSMQueue (const char * queueName, const char * coordinatingMutexName)
Constructor
FaultSMQueue::~FaultSMQueue () [virtual]
Virtual Destructor
Member Function Documentation
void FaultSMQueue::clearQueue ()
Clears the contents (alarms) of the shared memory queue
References UnboundedSMQueue< T >::delete_nodes().
int FaultSMQueue::dequeueAlarm (FaultMessage & message)
Dequeue a FaultMessage from the shared memory queue. The calling code is responsible for allocating the FaultMessage and passing it in as a reference to be populated.
Returns
OK on success; otherwise ERROR
References UnboundedSMQueue< T >::dequeue_head(), and UnboundedSMQueue< T >::is_empty().
Referenced by FaultManager::processMailbox().
int FaultSMQueue::enqueueAlarm (FaultMessage & message)
Enqueue a FaultMessage to the shared memory queue
Returns
OK on success; otherwise ERROR
References UnboundedSMQueue< T >::enqueue_tail().
Referenced by Faults::clearAlarm(), Faults::raiseAlarm(), and Faults::reportEvent().
bool FaultSMQueue::isEmpty ()
Returns true if the queue is empty
References UnboundedSMQueue< T >::is_empty().
Referenced by FaultManager::processMailbox().
int FaultSMQueue::setupQueue ()
Create the (or get a reference to an already created) queue
Returns
OK on success; otherwise ERROR
References SharedMemoryManager::getAllocator().
Referenced by Faults::initialize(), and FaultManager::initialize().
string FaultSMQueue::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
The documentation for this class was generated from the following files:
FaultSMQueue.h
FaultSMQueue.cpp