DiscoveryMessage Class Reference
Public Member Functions
DiscoveryMessage (const MailboxAddress &sourceAddress, DiscoveryOperationType operation, unsigned int originatingPID, const MailboxAddress &discoveryAddress)
DiscoveryMessage (const DiscoveryMessage &rhs)
virtual ~DiscoveryMessage ()
unsigned short getMessageId () const
DiscoveryOperationType getOperationType () const
const MailboxAddress & getDiscoveryAddress () const
unsigned int getOriginatingPID () const
int serialize (MessageBuffer &buffer)
string toString ()
Static Public Member Functions
static MessageBase * deserialize (MessageBuffer *buffer)
Additional Inherited Members
Constructor & Destructor Documentation
DiscoveryMessage::DiscoveryMessage (const MailboxAddress & sourceAddress, DiscoveryOperationType operation, unsigned int originatingPID, const MailboxAddress & discoveryAddress)
Constructor
Parameters
sourceAddress Mailbox Address for this DiscoveryManager (on this node)
operation Type of discovery operation (register, deregister, etc.)
discoveryAddress Mailbox Address that is being registered/deregistered
Referenced by deserialize().
DiscoveryMessage::DiscoveryMessage (const DiscoveryMessage & rhs)
Copy Constructor
DiscoveryMessage::~DiscoveryMessage () [virtual]
Virtual Destructor
Member Function Documentation
MessageBase * DiscoveryMessage::deserialize (MessageBuffer * buffer) [static]
Subclassed deserialization / bootstrap implementation
References DiscoveryMessage().
Referenced by DiscoveryManager::initialize().
const MailboxAddress & DiscoveryMessage::getDiscoveryAddress () const
Returns the Discovery Address which is being registered/deregistered
Referenced by DiscoveryManager::processMailbox().
unsigned short DiscoveryMessage::getMessageId () const [virtual]
Returns the Message Id
Implements MessageBase .
DiscoveryOperationType DiscoveryMessage::getOperationType () const
Returns the Discovery Operation type
Referenced by DiscoveryManager::processMailbox().
unsigned int DiscoveryMessage::getOriginatingPID () const
Returns the PID of the process that originated this message. Used to verify and filter out messages from our own DiscoveryManager
Referenced by DiscoveryManager::processMailbox().
int DiscoveryMessage::serialize (MessageBuffer & buffer) [virtual]
Subclassed serialization implementation
Reimplemented from MessageBase .
References MessageBase::sourceAddress_.
string DiscoveryMessage::toString () [virtual]
String'ized debugging method
Returns
string representation of the contents of this object
Implements MessageBase .
References MessageBase::sourceAddress_, and MailboxAddress::toString().
Referenced by DiscoveryManager::processMailbox().
The documentation for this class was generated from the following files:
DiscoveryMessage.h
DiscoveryMessage.cpp