CliMenuController Class Reference
Public Member Functions
CliMenuController ()
virtual ~CliMenuController ()
void initialize (session::Session_I_ptr session_I_ptr, platformConfig::platformConfig_I_ptr platformConfig_I_ptr, alarms::alarmInterface_ptr alarmInterface_ptr)
Additional Inherited Members
Constructor & Destructor Documentation
CliMenuController::CliMenuController ()
Constructor
CliMenuController::~CliMenuController () [virtual]
Virtual Destructor
Member Function Documentation
void CliMenuController::initialize (session::Session_I_ptr session_I_ptr, platformConfig::platformConfig_I_ptr platformConfig_I_ptr, alarms::alarmInterface_ptr alarmInterface_ptr)
Initialize the Menu and display the Main Menu Options
References CliMenuAlarms::getAlarmInventory(), CliMenuPlatformConfig::getLogLevels(), CliMenuAlarms::getOutstandingAlarms(), CliMenuStateActions::initialize(), CliMenuPlatformConfig::initialize(), CliMenuAlarms::initialize(), CliMenuStateActions::sendLock(), CliMenuStateActions::sendUnlock(), and CliMenuPlatformConfig::setLogLevel().
Referenced by CliClient::processMenu().
The documentation for this class was generated from the following files:
CliMenuController.h
CliMenuController.cpp