ObjectPool Class Reference
#include <ObjectPool.h>
Public Member Functions
ObjectPool (int objectPoolID, int initialCapacity, double thresholdPercentage, int capacityIncrement, const char *objectType, long objectInitParam, OPM_INIT_PTR bootStrapMethod, OPMGrowthModeType growthMode)
virtual ~ObjectPool ()
virtual OPMBase * reserve (bool blockWaitingForAccess=true)
virtual bool release (OPMBase *object, const char *callingFileName, int callingLineNumb)
int getCurrentCapacity ()
int getCurrentUsedObjects ()
const char * getObjectType ()
int getCapacityIncrement ()
double getThresholdPercentage ()
long getObjectInitParam ()
virtual bool isEmpty ()
virtual bool containsObject (OPMBase *object)
virtual void setCapacityIncrement (int capacityIncrement)
virtual void printUsageSummary ()
Protected Attributes
int capacityIncrement_
Detailed Description
ObjectPool stores objects of a particular type in the OPM and keeps track of which objects are free and which are in use.
Object pool contains methods for reserving and releasing pooled objects and for manipulating the capacity increments of the data structures (pool supports both growing and shrinking based on increment size), computing the count of free objects, setting the threshold and increment values, and performing cleanup.
This class is currently NOT THREAD SAFE.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
ObjectPool::ObjectPool (int objectPoolID, int initialCapacity, double thresholdPercentage, int capacityIncrement, const char * objectType, long objectInitParam, OPM_INIT_PTR bootStrapMethod, OPMGrowthModeType growthMode)
Constructor initializes the pool to a configurable size and sets the individual object's initializer to be stored in the Pool.
Parameters
objectPoolID Object PoolID that identifies this object pool in the OPM
initialCapacity Starting size of the pool in objects
thresholdPercentage Percentage of current capacity to trigger automatic growth.
capacityIncrement Number of objects to add to the current size when increasing capacity
objectType const char* describing the class object stored in this pool
objectInitParam - Integer parameter or pointer to initialization data needed by the object or 0(NULL) if not needed (passed to OPMBase::initialize).
bootStrapMethod pointer to a function or method (OPMBase::initialize) that will create the object and return a pointer to it
growthMode Either NO_GROWTH, GROWTH_ALLOWED, or GROW_AND_SHRINK
References capacityIncrement_, Logger::getSubsystemLogLevel(), and OPMLinkedList::insertFirst().
ObjectPool::~ObjectPool () [virtual]
Virtual Destructor
References OPMLinkedList::deleteListContents().
Member Function Documentation
bool ObjectPool::containsObject (OPMBase * object) [virtual]
Method to check if a specified object is in the Free Linked List or the Used Linked List. This method traverses both lists looking for pointer equality.
Returns
true if the Object is in the list
 false if the Object is NOT in the list
Reimplemented in SyncObjectPool .
References OPMLinkedList::containsObject().
Referenced by SyncObjectPool::containsObject(), OPM::isCreatedByOPM(), and release().
int ObjectPool::getCapacityIncrement ()
Return the capacity increment size for this pool
References capacityIncrement_.
Referenced by OPM::getPoolCapacityIncrement().
int ObjectPool::getCurrentCapacity ()
Return the current capacity of this pool
Referenced by OPM::checkForUnreleasedObjects().
int ObjectPool::getCurrentUsedObjects ()
Return the current number of Used Objects in this pool
Referenced by OPM::checkForUnreleasedObjects().
long ObjectPool::getObjectInitParam ()
Return the initializer for the objects in this pool (if there is one)
Referenced by OPM::getPoolObjectInitParam().
const char * ObjectPool::getObjectType ()
Return the object type String being held in this pool
Referenced by OPM::checkForUnreleasedObjects().
double ObjectPool::getThresholdPercentage ()
Return the threshold percentage for this pool
Referenced by OPM::getPoolThresholdPercentage().
bool ObjectPool::isEmpty () [virtual]
Method to test if this pool is empty
Returns
true if the Free List is empty
 false if the Free List is NOT empty
Reimplemented in SyncObjectPool .
References OPMLinkedList::isEmpty().
Referenced by SyncObjectPool::isEmpty().
bool ObjectPool::release (OPMBase * object, const char * callingFileName, int callingLineNumb) [virtual]
Release an object back into the pool after using it. This makes the object available again for use in other tasks. This method automatically monitors the number of in-use objects and will shrink the pool when the number drops below the previous increment's threshold value.
Parameters
object Object to release back into the pool.
callingFileName - Specifies the source file from which the object is being released (this will be printed as a DEBUG log using a MACRO)
callingLineNumb - Specifies the source line from which the object is being released (this will be printed as a DEBUG log using a MACRO)
Returns
true if the specified Object was successfully released
 false if the Object Reference was not found in the USED data structure (could be wrong pool, is already released, or was not created via OPM)
References capacityIncrement_, containsObject(), OPMBase::getPoolID(), Logger::getSubsystemLogLevel(), OPMLinkedList::insertFirst(), OPMLinkedList::remove(), OPMLinkedList::removeFirst(), and OPMBase::setPoolID().
Referenced by OPM::getPoolCapacityIncrement(), OPM::getPoolObjectInitParam(), OPM::getPoolThresholdPercentage(), OPM::isCreatedByOPM(), OPM::printPoolSummary(), SyncObjectPool::release(), OPM::releaseObject(), OPM::reserveObject(), and OPM::setPoolCapacityIncrement().
OPMBase * ObjectPool::reserve (bool blockWaitingForAccess = true) [virtual]
Reserve an object for use, thus making it unavailable for other tasks. This method automatically monitors the number of in-use objects and will grow the pool when the number exceeds the threshold. If the object pool is specified to be non-resizable, then an error will be displayed and NULL returned if no available objects exist.
Parameters
blockWaitingForAccess If true, this method will block until an object becomes available if they are all in use. Otherwise, if false, this method will return NULL if all objects are in use. Note that this parameter is used ONLY with SyncObjectPool. It has no meaning here, other than for inheritance.
Reimplemented in SyncObjectPool .
References Logger::getSubsystemLogLevel(), OPMLinkedList::insertFirst(), OPMLinkedList::isEmpty(), and OPMLinkedList::removeFirst().
Referenced by SyncObjectPool::reserve(), and OPM::reserveObject().
void ObjectPool::setCapacityIncrement (int capacityIncrement) [virtual]
Method to set or reset the capacity increment of this Object Pool
Parameters
capacityIncrement The new capacity increment value
Reimplemented in SyncObjectPool .
References capacityIncrement_.
Referenced by OPM::setPoolCapacityIncrement().
Member Data Documentation
int ObjectPool::capacityIncrement_ [protected]
Pool Increment Size which is the number of objects to add when growing
Referenced by getCapacityIncrement(), ObjectPool(), release(), SyncObjectPool::setCapacityIncrement(), and setCapacityIncrement().
The documentation for this class was generated from the following files:
ObjectPool.h
ObjectPool.cpp