MailboxOwnerHandle Class Reference
Public Member Functions
MailboxOwnerHandle (MailboxBase *mailboxPtr)
virtual ~MailboxOwnerHandle ()
virtual int post (MessageBase *messagePtr, const ACE_Time_Value *timeout=&ACE_Time_Value::zero)
long scheduleTimer (TimerMessage *timerMessagePtr)
int cancelTimer (long timerId, TimerMessage *timerMessagePtr)
int resetTimerInterval (long timerId, TimerMessage *timerMessagePtr, const ACE_Time_Value &newInterval)
int activate ()
int deactivate ()
virtual MessageBase * getMessage (unsigned short timeout=0)
virtual MessageBase * getMessageNonBlocking ()
virtual int getDebugValue ()
virtual void setDebugValue (int debugValue)
virtual bool isProxy ()
virtual MailboxAddress & getMailboxAddress ()
virtual unsigned int getSentCount ()
bool rename (const MailboxAddress &newRemoteAddress)
MailboxHandle * generateMailboxHandleCopy ()
string toString ()
Protected Attributes
MailboxBase * mailboxPtr_
Constructor & Destructor Documentation
MailboxOwnerHandle::MailboxOwnerHandle (MailboxBase * mailboxPtr)
Constructor. Stores a pointer to the mailbox
References MailboxBase::acquire(), MailboxOwnerHandle(), and mailboxPtr_.
Referenced by MailboxOwnerHandle().
MailboxOwnerHandle::~MailboxOwnerHandle () [virtual]
Virtual Destructor
References mailboxPtr_, and MailboxBase::release().
Member Function Documentation
int MailboxOwnerHandle::activate ()
This method activates the mailbox
Returns
OK on success; ERROR for failure
References MailboxBase::activate(), and mailboxPtr_.
Referenced by MailboxLookupService::find(), DiscoveryManager::initialize(), ResourceMonitor::processMailbox(), ProcessManager::processMailbox(), FaultManager::processMailbox(), and DiscoveryManager::processMailbox().
int MailboxOwnerHandle::cancelTimer (long timerId, TimerMessage * timerMessagePtr)
Cancel an outstanding, active Timer Message. NOTE that the TimerMessage is provided here and is deleted when the timer is canceled -if- the Timer is not Owned/Pooled by the OPM and its not reusable. If the timer is Owned/Pooled by the OPM, then it will be released back into the pool here. If the timer is reusable, then it is upto the application to delete it.
Returns
OK if cancellation succeeded and ERROR if the TimerId wasn't found
References MailboxBase::decrementActiveTimers(), MailboxBase::getReactor(), OPM::isCreatedByOPM(), MessageBase::isPoolable(), MessageBase::isReusable(), and mailboxPtr_.
int MailboxOwnerHandle::deactivate ()
This method deactivates the mailbox
Returns
OK on success; ERROR for failure
References MailboxBase::deactivate(), and mailboxPtr_.
MailboxHandle * MailboxOwnerHandle::generateMailboxHandleCopy ()
Return a regular Mailbox Handle to this same encapsulated Mailbox. NOTE: This method call creates a Mailbox Handle on the heap. It then becomes the callers responsibility to delete the regular handle when finished with it to prevent a memory leak.
References mailboxPtr_.
Referenced by MailboxLookupService::find().
int MailboxOwnerHandle::getDebugValue () [virtual]
Returns the Debug flag value for this mailbox.
References MailboxBase::getDebugValue(), and mailboxPtr_.
MailboxAddress & MailboxOwnerHandle::getMailboxAddress () [virtual]
Return the mailbox address
References MailboxBase::getMailboxAddress(), and mailboxPtr_.
Referenced by MailboxLookupService::deregisterMailbox(), MailboxLookupService::getDebugForAllMailboxAddresses(), FaultManager::processMailbox(), and MailboxLookupService::registerMailbox().
MessageBase * MailboxOwnerHandle::getMessage (unsigned short timeout = 0) [virtual]
Will block until a message is available. May return NULL if no message available (if mailbox deactivated).
References MailboxBase::getMessage(), and mailboxPtr_.
Referenced by MailboxProcessor::processMailbox().
MessageBase * MailboxOwnerHandle::getMessageNonBlocking () [virtual]
Will not block until a message is available.
If the application has a need to do non-blocking calls to get (or check to see if) messages pending on the mailbox queue, then the application needs to implement this call -instead- of calling MailboxProcess::processMailbox(). If this is indeed the case, then the application will either need to implement the case switching on the Message Type -or- implement the find for the MessageHandlerList (functor lookup).
Returns
NULL if no message available (and if mailbox deactivated).
References MailboxBase::getMessageNonBlocking(), and mailboxPtr_.
unsigned int MailboxOwnerHandle::getSentCount () [virtual]
Return the sent message counter value
References MailboxBase::getSentCount(), and mailboxPtr_.
bool MailboxOwnerHandle::isProxy () [virtual]
Return whether this mailbox is a remote proxy or not
References MailboxBase::isProxy(), and mailboxPtr_.
Referenced by MailboxLookupService::deregisterMailbox(), and MailboxLookupService::getDebugForAllMailboxAddresses().
int MailboxOwnerHandle::post (MessageBase * messagePtr, const ACE_Time_Value * timeout = &ACE_Time_Value::zero) [virtual]
Post a message to this mailbox
Returns
ERROR for an error; otherwise OK
References mailboxPtr_, and MailboxBase::post().
Referenced by DiscoveryManager::deregisterLocalAddress(), DiscoveryManager::listAllMailboxAddresses(), DiscoveryManager::processMailbox(), and DiscoveryManager::registerLocalAddress().
bool MailboxOwnerHandle::rename (const MailboxAddress & newRemoteAddress)
Rename the Mailbox address
References mailboxPtr_, and MailboxBase::rename().
int MailboxOwnerHandle::resetTimerInterval (long timerId, TimerMessage * timerMessagePtr, const ACE_Time_Value & newInterval)
Reset the timer interval for a specified outstanding, active Timer Message. In other words, change how often the timer is periodically restarted. A value of ACE_Time_Value::zero will cause the timer to NOT be restarted again.
Returns
OK if successful, ERROR if not.
References MailboxBase::getReactor(), mailboxPtr_, and ReusableMessageBase::setNoLongerReusable().
long MailboxOwnerHandle::scheduleTimer (TimerMessage * timerMessagePtr)
Schedule a Timer Message to expire at the specified timeout. When the Timer expires, it is enqueued to the local mailbox.
Returns
TimerId for this Timer, or ERROR
References MailboxBase::getReactor(), TimerMessage::getRestartInterval(), TimerMessage::getTimeout(), MailboxBase::incrementActiveTimers(), and mailboxPtr_.
Referenced by ResourceMonitor::initialize(), and FaultManager::initialize().
void MailboxOwnerHandle::setDebugValue (int debugValue) [virtual]
Sets the Debug flag value for this mailbox.
References mailboxPtr_, and MailboxBase::setDebugValue().
Referenced by FaultManager::processMailbox(), and DiscoveryManager::processMailbox().
string MailboxOwnerHandle::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
Member Data Documentation
MailboxBase* MailboxOwnerHandle::mailboxPtr_ [protected]
Pointer to the encapsulated mailbox
Referenced by activate(), cancelTimer(), deactivate(), generateMailboxHandleCopy(), getDebugValue(), getMailboxAddress(), getMessage(), getMessageNonBlocking(), getSentCount(), isProxy(), MailboxOwnerHandle(), post(), rename(), resetTimerInterval(), scheduleTimer(), setDebugValue(), and ~MailboxOwnerHandle().
The documentation for this class was generated from the following files:
MailboxOwnerHandle.h
MailboxOwnerHandle.cpp