FaultManager Class Reference
Public Member Functions
FaultManager ()
virtual ~FaultManager ()
void processMailbox ()
int initialize (int faultReportPeriod)
Static Public Member Functions
static void catchShutdownSignal ()
Constructor & Destructor Documentation
FaultManager::FaultManager ()
Constructor
Referenced by processMailbox().
FaultManager::~FaultManager () [virtual]
Virtual Destructor
Member Function Documentation
void FaultManager::catchShutdownSignal () [static]
Catch the shutdown signal and begin the graceful shutdown
Referenced by initialize().
int FaultManager::initialize (int faultReportPeriod)
Perform FaultManager initialization
Parameters
faultReportPeriod Interval period for which Fault Manager will publish a fault report of outstanding alarms in the trace logs
Returns
ERROR on failure; otherwise OK
References DataManager::activateConnectionSet(), catchShutdownSignal(), ThreadManager::createThread(), MailboxLookupService::find(), SystemInfo::getLocalNEID(), MailboxAddress::inetAddress, DataManager::initialize(), MailboxAddress::locationType, MailboxAddress::mailboxName, MailboxAddress::neid, MailboxOwnerHandle::scheduleTimer(), and FaultSMQueue::setupQueue().
Referenced by processMailbox().
void FaultManager::processMailbox ()
Start the mailbox processing loop
References MailboxOwnerHandle::activate(), MessageHandlerList::add(), FaultMessage::alarmCode, FaultMessage::alarmSeverity, DbConnectionHandle::closeCommandResult(), DistributedMailbox::createMailbox(), FaultSMQueue::dequeueAlarm(), FaultMessage::eventCode, DbConnectionHandle::executeCommand(), FaultManager(), MailboxLookupService::find(), DbConnectionHandle::getColumnCount(), DbConnectionHandle::getColumnIndex(), DbConnectionHandle::getColumnName(), Logger::getInstance(), DbConnectionHandle::getIntValueAt(), MailboxOwnerHandle::getMailboxAddress(), DbConnectionHandle::getRowCount(), DbConnectionHandle::getShortValueAt(), DbConnectionHandle::getStringValueAt(), DbConnectionHandle::getTimestampValueAt(), OPM::initialize(), initialize(), Logger::initialize(), FaultSMQueue::isEmpty(), FaultMessage::managedObject, FaultMessage::managedObjectInstance, FaultMessage::neidPI, FaultMessage::pid, MailboxHandle::post(), MailboxProcessor::processMailbox(), processMailbox(), DataManager::releaseConnection(), DataManager::reserveConnection(), MailboxLookupService::setDebugForAllMailboxAddresses(), MailboxOwnerHandle::setDebugValue(), Logger::setSubsystemLogLevel(), and FaultMessage::timeStamp.
Referenced by processMailbox().
The documentation for this class was generated from the following files:
FaultManager.h
FaultManager.cpp