LocalSMMailboxQueue Class Reference
Public Types
typedef UnboundedSMQueue< LocalSMBuffer > LOCAL_SM_MAILBOX_QUEUE
Public Member Functions
LocalSMMailboxQueue (const char *queueName, const char *coordinatingMutexName)
virtual ~LocalSMMailboxQueue ()
int setupQueue ()
int enqueueMessage (LocalSMBuffer &buffer)
int dequeueMessage (LocalSMBuffer &buffer)
void clearQueue ()
bool isEmpty ()
string toString ()
Member Typedef Documentation
typedef UnboundedSMQueue<LocalSMBuffer> LocalSMMailboxQueue::LOCAL_SM_MAILBOX_QUEUE
Shared Memory Queue type for LocalSMBuffer Messages
Constructor & Destructor Documentation
LocalSMMailboxQueue::LocalSMMailboxQueue (const char * queueName, const char * coordinatingMutexName)
Constructor
LocalSMMailboxQueue::~LocalSMMailboxQueue () [virtual]
Virtual Destructor
Member Function Documentation
void LocalSMMailboxQueue::clearQueue ()
Clears the MessageBase contents of the shared memory queue
References UnboundedSMQueue< T >::delete_nodes().
int LocalSMMailboxQueue::dequeueMessage (LocalSMBuffer & buffer)
Dequeue a Message from the shared memory queue. The calling code is responsible for allocating the Message and passing it in as a reference to be populated.
Returns
OK on success; otherwise ERROR
References UnboundedSMQueue< T >::dequeue_head(), and UnboundedSMQueue< T >::is_empty().
Referenced by LocalSMMailbox::getMailboxAddress().
int LocalSMMailboxQueue::enqueueMessage (LocalSMBuffer & buffer)
Enqueue a Message to the shared memory queue
Returns
OK on success; otherwise ERROR
References UnboundedSMQueue< T >::enqueue_tail().
Referenced by LocalSMMailboxProxy::post().
bool LocalSMMailboxQueue::isEmpty ()
Returns true if the queue is empty
References UnboundedSMQueue< T >::is_empty().
Referenced by LocalSMMailbox::getMailboxAddress().
int LocalSMMailboxQueue::setupQueue ()
Create the (or get a reference to an already created) queue
Returns
OK on success; otherwise ERROR
References SharedMemoryManager::getAllocator().
Referenced by LocalSMMailboxProxy::createMailbox(), and LocalSMMailbox::createMailbox().
string LocalSMMailboxQueue::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
The documentation for this class was generated from the following files:
LocalSMMailboxQueue.h
LocalSMMailboxQueue.cpp