ReusableMessageBase Class Reference
#include <ReusableMessageBase.h>
Public Member Functions
ReusableMessageBase (const MailboxAddress &sourceAddress, unsigned int versionNumber, unsigned int sourceContextId=0, unsigned int destinationContextId=0)
virtual ~ReusableMessageBase ()
void setHasBeenProcessed (bool hasBeenProcessed)
bool hasBeenProcessed ()
void setNoLongerReusable ()
Additional Inherited Members
Detailed Description
ReusableMessageBase inherits from the MessageBase to provide for Messages that are reusable/resendable without the MsgMgr framework consuming them; that is, they will not be consumed when the MsgMgr is done processing them (so they can be sent over and over again).
Once the ReusableMessageBase is no longer needed (in the case the Message is recurring for only a finite number of times), the developer can mark the message as no longer reusable which will cause the MsgMgr framework to delete it when the current/next iteration is complete.
ReusableMessageBase also provides the developer with a way to mark the message as 'havingBeenProcessed' in its current iteration, as well as a way to reset that condition on the next iteration.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
ReusableMessageBase::ReusableMessageBase (const MailboxAddress & sourceAddress, unsigned int versionNumber, unsigned int sourceContextId = 0, unsigned int destinationContextId = 0)
Constructor
References MessageBase::isReusable_, and ReusableMessageBase().
Referenced by ReusableMessageBase().
ReusableMessageBase::~ReusableMessageBase () [virtual]
Virtual Destructor
Member Function Documentation
bool ReusableMessageBase::hasBeenProcessed ()
Accessor method used to determine if the Message has already been processed this time around
Referenced by setHasBeenProcessed().
void ReusableMessageBase::setHasBeenProcessed (bool hasBeenProcessed)
Mutator method to set whether or not the Message has already been processed this time around
References hasBeenProcessed().
void ReusableMessageBase::setNoLongerReusable ()
Mark this Message as no longer reusable so that it can be consumed by the MsgMgr framework
References MessageBase::isReusable_.
Referenced by MailboxOwnerHandle::resetTimerInterval().
The documentation for this class was generated from the following files:
ReusableMessageBase.h
ReusableMessageBase.cpp