ProcessDeathHandler Class Reference
Public Member Functions
ProcessDeathHandler (RestartProcessMethod &restartProcessMethod)
virtual ~ProcessDeathHandler ()
virtual int handle_exit (ACE_Process *process)
virtual int handle_input (ACE_HANDLE pid)
virtual int handle_close (ACE_HANDLE handle, ACE_Reactor_Mask close_mask)
virtual int handle_signal (int signum, siginfo_t *=0, ucontext_t *=0)
void setProcessIdentity (pid_t processID, string &processName)
void setTerminatedFlag (bool hasBeenTerminated)
string toString ()
Constructor & Destructor Documentation
ProcessDeathHandler::ProcessDeathHandler (RestartProcessMethod & restartProcessMethod)
Constructor
ProcessDeathHandler::~ProcessDeathHandler () [virtual]
Virtual Destructor
Member Function Documentation
int ProcessDeathHandler::handle_close (ACE_HANDLE handle, ACE_Reactor_Mask close_mask) [virtual]
ACE Event Handler implementation
int ProcessDeathHandler::handle_exit (ACE_Process * process) [virtual]
ACE Event Handler implementation
int ProcessDeathHandler::handle_input (ACE_HANDLE pid) [virtual]
ACE Event Handler implementation
int ProcessDeathHandler::handle_signal (int signum, siginfo_t * = 0, ucontext_t * = 0) [virtual]
ACE Event Handler implementation
void ProcessDeathHandler::setProcessIdentity (pid_t processID, string & processName)
Initialize the process identity info (ID and Name)
Referenced by ProcessController::init(), and ProcessController::restartProcess().
void ProcessDeathHandler::setTerminatedFlag (bool hasBeenTerminated)
Method to set/reset whether or not this process has been manually terminated
Referenced by ProcessController::fini(), and ProcessController::init().
string ProcessDeathHandler::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
The documentation for this class was generated from the following files:
ProcessDeathHandler.h
ProcessDeathHandler.cpp