OPMBase Class Reference
Public Member Functions
OPMBase ()
virtual ~OPMBase ()
bool isNextNull ()
bool isPrevNull ()
OPMBase * getNext ()
void setNext (OPMBase *newObject)
OPMBase * getPrev ()
void setPrev (OPMBase *newObject)
int getPoolID ()
void setPoolID (int poolID)
const char * getObjectTypeStr ()
void setObjectTypeStr (const char *objectType)
string toString ()
virtual void clean ()=0
Static Public Member Functions
static OPMBase * initialize (int initializer)
Protected Attributes
OPMBase * next_
OPMBase * prev_
const char * objectType_
int poolID_
Additional Inherited Members
Constructor & Destructor Documentation
OPMBase::OPMBase ()
Constructor
References ObjectBase::setPoolable().
OPMBase::~OPMBase () [virtual]
Virtual Destructor
References objectType_.
Member Function Documentation
virtual void OPMBase::clean () [pure virtual]
Pure Virtual method will be called before releasing the object back into the pool.
Implemented in DbConnectionHandle , LocalSMBuffer , PgConnection , MessageBuffer , and MessageBlockWrapper .
OPMBase * OPMBase::getNext ()
Return the next OPMBase object referred to in the Linked List
References next_.
Referenced by OPMLinkedList::containsObject(), OPMLinkedList::deleteListContents(), OPMLinkedList::remove(), OPMLinkedList::removeFirst(), and OPMLinkedList::toString().
const char * OPMBase::getObjectTypeStr ()
Return a pointer to the object type string for this object
References objectType_.
int OPMBase::getPoolID ()
Return the integer poolID that identifies which pool this object belongs to
References poolID_.
Referenced by OPM::isCreatedByOPM(), and ObjectPool::release().
OPMBase * OPMBase::getPrev ()
Return the previous OPMBase object referred to in the Linked List
References prev_.
Referenced by OPMLinkedList::remove().
static OPMBase* OPMBase::initialize (int initializer) [static]
Static method will be called when the pool is created with these objects. This method bootstraps the creation of each object. This method must be static, but SHOULD ALSO BE VIRTUAL so users are forced to implement it.
Parameters
initializer - Initializer integer or pointer to initialization data needed by the object - may be 0 if unused.
Returns
Pointer to the new OPMBase object.
bool OPMBase::isNextNull ()
Return whether or not there is a next node in the Linked List
References next_.
Referenced by OPMLinkedList::containsObject(), OPMLinkedList::deleteListContents(), and OPMLinkedList::toString().
bool OPMBase::isPrevNull ()
Return whether or not there is a previous node in the Linked List
References prev_.
void OPMBase::setNext (OPMBase * newObject)
Set the next OPMBase object referred to in the Linked List
References next_.
Referenced by OPMLinkedList::deleteListContents(), OPMLinkedList::insertLast(), and OPMLinkedList::remove().
void OPMBase::setObjectTypeStr (const char * objectType)
Set the object type string for this object - called upon object creation
References objectType_.
Referenced by LocalSMBuffer::LocalSMBuffer().
void OPMBase::setPoolID (int poolID)
Set the integer poolID that identifies which pool this object belongs to
References poolID_.
Referenced by ObjectPool::release().
void OPMBase::setPrev (OPMBase * newObject)
Set the previous OPMBase object referred to in the Linked List
References prev_.
Referenced by OPMLinkedList::deleteListContents(), OPMLinkedList::insertFirst(), OPMLinkedList::remove(), and OPMLinkedList::removeFirst().
string OPMBase::toString ()
String'ized debugging tool
References objectType_, and poolID_.
Referenced by OPMLinkedList::toString().
Member Data Documentation
OPMBase* OPMBase::next_ [protected]
Pointer reference to the 'next' OPMBase object in the Linked List implemented in Object Pool.
Referenced by getNext(), isNextNull(), and setNext().
const char* OPMBase::objectType_ [protected]
Pointer to the char* object type for this object
Referenced by getObjectTypeStr(), setObjectTypeStr(), toString(), and ~OPMBase().
int OPMBase::poolID_ [protected]
PoolID used to -self- identify which object pool this object belongs to
Referenced by getPoolID(), setPoolID(), and toString().
OPMBase* OPMBase::prev_ [protected]
Pointer reference to the 'previous' OPMBase object in the Linked List implemented in Object Pool.
Referenced by getPrev(), isPrevNull(), and setPrev().
The documentation for this class was generated from the following files:
OPMBase.h
OPMBase.cpp