MessageTestRemoteMessage Class Reference
#include <MessageTestRemoteMessage.h>
Public Member Functions
MessageTestRemoteMessage (const MailboxAddress &sourceAddress, int ourIntValue, string ourStringValue)
virtual ~MessageTestRemoteMessage ()
unsigned short getMessageId () const
int serialize (MessageBuffer &buffer)
string toString ()
MessageTestRemoteMessage (const MailboxAddress &sourceAddress, int ourIntValue, string ourStringValue)
virtual ~MessageTestRemoteMessage ()
unsigned short getMessageId () const
int serialize (MessageBuffer &buffer)
string toString ()
MessageTestRemoteMessage (const MailboxAddress &sourceAddress, int ourIntValue, string ourStringValue)
virtual ~MessageTestRemoteMessage ()
unsigned short getMessageId () const
int serialize (MessageBuffer &buffer)
string toString ()
MessageTestRemoteMessage (const MailboxAddress &sourceAddress, int ourIntValue, string ourStringValue)
virtual ~MessageTestRemoteMessage ()
unsigned short getMessageId () const
int serialize (MessageBuffer &buffer)
string toString ()
MessageTestRemoteMessage (const MailboxAddress &sourceAddress, int ourIntValue, string ourStringValue)
virtual ~MessageTestRemoteMessage ()
unsigned short getMessageId () const
int serialize (MessageBuffer &buffer)
string toString ()
MessageTestRemoteMessage (const MailboxAddress &sourceAddress, int ourIntValue, string ourStringValue)
virtual ~MessageTestRemoteMessage ()
unsigned short getMessageId () const
int serialize (MessageBuffer &buffer)
string toString ()
MessageTestRemoteMessage (const MailboxAddress &sourceAddress, int ourIntValue, string ourStringValue)
virtual ~MessageTestRemoteMessage ()
unsigned short getMessageId () const
int serialize (MessageBuffer &buffer)
string toString ()
Static Public Member Functions
static MessageBase * deserialize (MessageBuffer *buffer)
static MessageBase * deserialize (MessageBuffer *buffer)
static MessageBase * deserialize (MessageBuffer *buffer)
static MessageBase * deserialize (MessageBuffer *buffer)
static MessageBase * deserialize (MessageBuffer *buffer)
static MessageBase * deserialize (MessageBuffer *buffer)
static MessageBase * deserialize (MessageBuffer *buffer)
Detailed Description
MessageTestRemoteMessage is a Test Message for the Distributed Mailbox.
This message demonstrates distributed and local mailbox message passing.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
MessageTestRemoteMessage::MessageTestRemoteMessage (const MailboxAddress & sourceAddress, int ourIntValue, string ourStringValue)
Constructor
Referenced by deserialize().
MessageTestRemoteMessage::~MessageTestRemoteMessage () [virtual]
Virtual Destructor
MessageTestRemoteMessage::MessageTestRemoteMessage (const MailboxAddress & sourceAddress, int ourIntValue, string ourStringValue)
Constructor
virtual MessageTestRemoteMessage::~MessageTestRemoteMessage () [virtual]
Virtual Destructor
MessageTestRemoteMessage::MessageTestRemoteMessage (const MailboxAddress & sourceAddress, int ourIntValue, string ourStringValue)
Constructor
virtual MessageTestRemoteMessage::~MessageTestRemoteMessage () [virtual]
Virtual Destructor
MessageTestRemoteMessage::MessageTestRemoteMessage (const MailboxAddress & sourceAddress, int ourIntValue, string ourStringValue)
Constructor
virtual MessageTestRemoteMessage::~MessageTestRemoteMessage () [virtual]
Virtual Destructor
MessageTestRemoteMessage::MessageTestRemoteMessage (const MailboxAddress & sourceAddress, int ourIntValue, string ourStringValue)
Constructor
virtual MessageTestRemoteMessage::~MessageTestRemoteMessage () [virtual]
Virtual Destructor
MessageTestRemoteMessage::MessageTestRemoteMessage (const MailboxAddress & sourceAddress, int ourIntValue, string ourStringValue)
Constructor
virtual MessageTestRemoteMessage::~MessageTestRemoteMessage () [virtual]
Virtual Destructor
MessageTestRemoteMessage::MessageTestRemoteMessage (const MailboxAddress & sourceAddress, int ourIntValue, string ourStringValue)
Constructor
virtual MessageTestRemoteMessage::~MessageTestRemoteMessage () [virtual]
Virtual Destructor
Member Function Documentation
MessageBase * MessageTestRemoteMessage::deserialize (MessageBuffer * buffer) [static]
Subclassed deserialization / bootstrap implementation
References MessageTestRemoteMessage().
Referenced by MessageTestRemote::getLocalMailboxAddress(), and MessageTestRemote::MessageTestRemote().
static MessageBase* MessageTestRemoteMessage::deserialize (MessageBuffer * buffer) [static]
Subclassed deserialization / bootstrap implementation
static MessageBase* MessageTestRemoteMessage::deserialize (MessageBuffer * buffer) [static]
Subclassed deserialization / bootstrap implementation
static MessageBase* MessageTestRemoteMessage::deserialize (MessageBuffer * buffer) [static]
Subclassed deserialization / bootstrap implementation
static MessageBase* MessageTestRemoteMessage::deserialize (MessageBuffer * buffer) [static]
Subclassed deserialization / bootstrap implementation
static MessageBase* MessageTestRemoteMessage::deserialize (MessageBuffer * buffer) [static]
Subclassed deserialization / bootstrap implementation
static MessageBase* MessageTestRemoteMessage::deserialize (MessageBuffer * buffer) [static]
Subclassed deserialization / bootstrap implementation
unsigned short MessageTestRemoteMessage::getMessageId () const
Returns the Message Id
unsigned short MessageTestRemoteMessage::getMessageId () const
Returns the Message Id
unsigned short MessageTestRemoteMessage::getMessageId () const
Returns the Message Id
unsigned short MessageTestRemoteMessage::getMessageId () const
Returns the Message Id
unsigned short MessageTestRemoteMessage::getMessageId () const
Returns the Message Id
unsigned short MessageTestRemoteMessage::getMessageId () const
Returns the Message Id
unsigned short MessageTestRemoteMessage::getMessageId () const
Returns the Message Id
int MessageTestRemoteMessage::serialize (MessageBuffer & buffer)
Subclassed serialization implementation
int MessageTestRemoteMessage::serialize (MessageBuffer & buffer)
Subclassed serialization implementation
int MessageTestRemoteMessage::serialize (MessageBuffer & buffer)
Subclassed serialization implementation
int MessageTestRemoteMessage::serialize (MessageBuffer & buffer)
Subclassed serialization implementation
int MessageTestRemoteMessage::serialize (MessageBuffer & buffer)
Subclassed serialization implementation
int MessageTestRemoteMessage::serialize (MessageBuffer & buffer)
Subclassed serialization implementation
int MessageTestRemoteMessage::serialize (MessageBuffer & buffer)
Subclassed serialization implementation
string MessageTestRemoteMessage::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
string MessageTestRemoteMessage::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
string MessageTestRemoteMessage::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
string MessageTestRemoteMessage::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
string MessageTestRemoteMessage::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
string MessageTestRemoteMessage::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
string MessageTestRemoteMessage::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
Referenced by MessageTestRemote::MessageTestRemote(), and MessageTestRemote::processMailbox().
The documentation for this class was generated from the following files:
discoverytest1/MessageTestRemoteMessage.h
discoverytest1/MessageTestRemoteMessage.cpp