LocalSMMailboxProxy Class Reference
Public Member Functions
virtual int post (MessageBase *messagePtr, const ACE_Time_Value *timeout=&ACE_Time_Value::zero)
virtual int activate (MailboxOwnerHandle *mailboxOwnerHandle)
virtual int deactivate (MailboxOwnerHandle *mailboxOwnerHandle)
virtual const ACE_Time_Value & getPostDefaultTimeout ()
virtual int getDebugValue ()
virtual void setDebugValue (int debugValue)
MailboxAddress & getMailboxAddress ()
string toString ()
Static Public Member Functions
static MailboxOwnerHandle * createMailbox (const MailboxAddress &localAddress)
Protected Member Functions
LocalSMMailboxProxy (const MailboxAddress &localAddress, const char *queueName, const char *coordinatingMutexName)
virtual ~LocalSMMailboxProxy ()
Additional Inherited Members
Constructor & Destructor Documentation
LocalSMMailboxProxy::LocalSMMailboxProxy (const MailboxAddress & localAddress, const char * queueName, const char * coordinatingMutexName) [protected]
Constructor
References OPM::createPool(), MessageBuffer::initialize(), LocalSMBuffer::initialize(), MailboxBase::isProxy_, LocalSMMailboxProxy(), and MailboxAddress::toString().
Referenced by LocalSMMailboxProxy().
LocalSMMailboxProxy::~LocalSMMailboxProxy () [protected], [virtual]
Virtual Destructor. Protected since this is a reference counted object.
References MailboxBase::isShuttingDown_.
Member Function Documentation
int LocalSMMailboxProxy::activate (MailboxOwnerHandle * mailboxOwnerHandle) [virtual]
Activate the mailbox. Here, activate always returns true since all we have to do is map into shared memory. It returns true regardless if the Shared Memory Queue already exists in shared memory or if we had to create it (meaning we are enqueuing, but no one is listening).
For security, one must possess an Owner Handle to activate the mailbox and register it with the Lookup Service.
Reimplemented from MailboxBase .
References MailboxBase::isActive(), MailboxLookupService::registerMailbox(), and MailboxBase::setActive().
MailboxOwnerHandle * LocalSMMailboxProxy::createMailbox (const MailboxAddress & localAddress) [static]
Allows applications to create a mailbox and get a handle to it.
Since we do not want applications to have direct access to a mailbox object this method is provided. Applications that create mailboxes use this method to get a handle to their mailbox rather than have direct access. The handle returned is a owner handle which has all the privileges of the actual mailbox (getMessage/post etc). This method creates the mailbox, activates it (which in turn registers it with the lookup service) and then creates an owner handle, acquires it and then returns that handle. Both the mailbox and the returned handle are created on the heap.
References MailboxAddress::mailboxName, and LocalSMMailboxQueue::setupQueue().
Referenced by MailboxLookupService::find().
int LocalSMMailboxProxy::deactivate (MailboxOwnerHandle * mailboxOwnerHandle) [virtual]
Deactivate the mailbox. For security, one must possess an Owner Handle to deactivate the mailbox and deregister it with the Lookup Service.
Reimplemented from MailboxBase .
References MailboxLookupService::deregisterMailbox(), MailboxBase::isActive(), and MailboxBase::setActive().
int LocalSMMailboxProxy::getDebugValue () [virtual]
Return the debug flag
Implements MailboxBase .
References MailboxBase::debugValue_.
MailboxAddress & LocalSMMailboxProxy::getMailboxAddress () [virtual]
Return the mailbox address
Implements MailboxBase .
const ACE_Time_Value & LocalSMMailboxProxy::getPostDefaultTimeout () [virtual]
Return the appropriate default timeout for the post()
Implements MailboxBase .
int LocalSMMailboxProxy::post (MessageBase * messagePtr, const ACE_Time_Value * timeout = &ACE_Time_Value::zero) [virtual]
Post a message to the distributed remote mailbox. Subclass implementations should examine the `active_` state.
Returns
zero for an error, non-zero otherwise.
Implements MailboxBase .
References LocalSMBuffer::buffer, LocalSMBuffer::bufferLength, LocalSMBuffer::bufferPI, MailboxBase::debugValue_, MessageBase::deleteMessage(), LocalSMMailboxQueue::enqueueMessage(), MessageBase::getMessageId(), MessageBase::getPriority(), MessageBase::getSourceAddress(), MailboxBase::incrementSentCount(), MailboxAddress::inetAddress, MailboxBase::isActive(), MessageBase::serialize(), MessageBase::toString(), and MailboxAddress::toString().
void LocalSMMailboxProxy::setDebugValue (int debugValue) [virtual]
Set the debug flag
Implements MailboxBase .
References MailboxBase::debugValue_.
string LocalSMMailboxProxy::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
The documentation for this class was generated from the following files:
LocalSMMailboxProxy.h
LocalSMMailboxProxy.cpp