CliMenuAlarms Class Reference
#include <CliMenuAlarms.h>
Public Member Functions
CliMenuAlarms ()
virtual ~CliMenuAlarms ()
void initialize (alarms::alarmInterface_ptr alarmInterface_ptr)
string getOutstandingAlarms ()
string getAlarmInventory ()
Additional Inherited Members
Detailed Description
CliMenuAlarms contains static handler methods for alarm requests.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
CliMenuAlarms::CliMenuAlarms ()
Constructor
CliMenuAlarms::~CliMenuAlarms () [virtual]
Virtual Destructor
Member Function Documentation
string CliMenuAlarms::getAlarmInventory ()
Retrieve the Inventory of all possible Alarms in the system
References alarms::alarmInterface::getAlarmInventory().
Referenced by CliMenuController::initialize().
string CliMenuAlarms::getOutstandingAlarms ()
Retrieve all of the Outstanding Alarms the agent
References alarms::alarmInterface::getOutstandingAlarms().
Referenced by CliMenuController::initialize().
void CliMenuAlarms::initialize (alarms::alarmInterface_ptr alarmInterface_ptr)
Initialization Method
Referenced by CliMenuController::initialize().
The documentation for this class was generated from the following files:
CliMenuAlarms.h
CliMenuAlarms.cpp