ProcessManager Class Reference
#include <ProcessManager.h>
Public Member Functions
ProcessManager ()
virtual ~ProcessManager ()
void processMailbox ()
int initialize (int argc, ACE_TCHAR *argv[], string usageString)
string toString ()
Static Public Member Functions
static void catchShutdownSignal ()
static void startReactor ()
Detailed Description
The process manager provides for the configuration and startup of all platform and application processes as well as process monitoring
ProcessManager makes use of the ACE Service Configurator class to manage passing configuration information to the processes. The Service Configurator manages a configuration file (with default name 'svc.conf'), and it provides for the dynamic reconfiguration of processes using the SIGHUP signal. The Service Configurator provides interfaces for starting, stopping, pausing, resuming, reconfiguring etc. the services (processes) on-the-fly without stopping the whole system. This feature forms the basis for the system patch management strategy.
ProcessManager also makes use of the ACE_Process_Manager class to handle spawning of processes, monitoring child process death, etc.
ProcessManager accepts the following startup options: -b Daemonize the Process Manager process -d Verbose diagnostics as process directives are forked -f Read a different file other than svc.conf -n Do not process static directives -s Designate which signal to use for reconfigure instead of SIGHUP -S Pass in a process directive not specified in the svc.conf file -y Process static directives -l Local Logger Mode only (do not enqueue logs to shared memory) -r Redirect stdout/stderr to a specified file
The svc.conf configuration file that drives the Process Manager accepts the following format. For statically linked services (these are optional features that will run within the Process Manager OS process): static <service name>=``> [`argc/argv options for the service`] For dynamically linked services, for example, those services intended to run within their own OS process: dynamic <service name>=``> <service type>=``> <DLL/.so name>:<factory_function> [`argc/argv options`] where the 'service type' is either a Service_Object *, Module *, or Stream * -and- where the `argc/argv options` have the following format: `<process executable name> <'NULL' or redirected IO filename> <process options>` The following additional service directives are supported: remove <service name>=``> shuts down the service/process suspend <service name>=``> suspends activity for the process resume <service name>=``> resumes activity for the process Note that `argc/argv options`
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
ProcessManager::ProcessManager ()
Constructor
Referenced by toString().
ProcessManager::~ProcessManager () [virtual]
Virtual Destructor
Member Function Documentation
void ProcessManager::catchShutdownSignal () [static]
Method to catch OS signals
Referenced by initialize().
int ProcessManager::initialize (int argc, ACE_TCHAR * argv[], string usageString)
Perform Process Manager initialization
References catchShutdownSignal(), ThreadManager::createThread(), SystemInfo::getLocalNEID(), SystemInfo::getShelfNumber(), SystemInfo::getSlotNumber(), MailboxAddress::locationType, and startReactor().
Referenced by toString().
void ProcessManager::processMailbox ()
Start the mailbox processing loop
References MailboxOwnerHandle::activate(), and MailboxProcessor::processMailbox().
Referenced by toString().
void ProcessManager::startReactor () [static]
This method starts the reactor thread needed for processing Process Death Handlers and auto-reaping the exit statuses of the child processes.
Referenced by initialize().
string ProcessManager::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
References LocalMailbox::createMailbox(), Logger::getInstance(), OPM::initialize(), initialize(), Logger::initialize(), processMailbox(), ProcessManager(), and Logger::setSubsystemLogLevel().
The documentation for this class was generated from the following files:
ProcessManager.h
ProcessManager.cpp