MessageTestTimerMessage Class Reference
#include <MessageTestTimerMessage.h>
Public Member Functions
MessageTestTimerMessage (const MailboxAddress &sourceAddress, ACE_Time_Value timeout, ACE_Time_Value restartInterval)
virtual ~MessageTestTimerMessage ()
unsigned short getMessageId () const
string toString ()
MessageTestTimerMessage (const MailboxAddress &sourceAddress, ACE_Time_Value timeout, ACE_Time_Value restartInterval)
MessageTestTimerMessage (const MailboxAddress &sourceAddress, ACE_Time_Value timeout)
virtual ~MessageTestTimerMessage ()
unsigned short getMessageId () const
string toString ()
MessageTestTimerMessage (const MailboxAddress &sourceAddress, ACE_Time_Value timeout, ACE_Time_Value restartInterval)
virtual ~MessageTestTimerMessage ()
unsigned short getMessageId () const
string toString ()
MessageTestTimerMessage (const MailboxAddress &sourceAddress, ACE_Time_Value timeout, ACE_Time_Value restartInterval)
virtual ~MessageTestTimerMessage ()
unsigned short getMessageId () const
string toString ()
MessageTestTimerMessage (const MailboxAddress &sourceAddress, ACE_Time_Value timeout, ACE_Time_Value restartInterval)
virtual ~MessageTestTimerMessage ()
unsigned short getMessageId () const
string toString ()
MessageTestTimerMessage (const MailboxAddress &sourceAddress, ACE_Time_Value timeout, ACE_Time_Value restartInterval)
virtual ~MessageTestTimerMessage ()
unsigned short getMessageId () const
string toString ()
Detailed Description
MessageTestTimerMessage is Test Message #1.
This message demonstrates timer message passing only.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
MessageTestTimerMessage::MessageTestTimerMessage (const MailboxAddress & sourceAddress, ACE_Time_Value timeout, ACE_Time_Value restartInterval)
Constructor
MessageTestTimerMessage::~MessageTestTimerMessage () [virtual]
Virtual Destructor
Referenced by MessageTestTimerMessage().
MessageTestTimerMessage::MessageTestTimerMessage (const MailboxAddress & sourceAddress, ACE_Time_Value timeout, ACE_Time_Value restartInterval)
Constructor
MessageTestTimerMessage::MessageTestTimerMessage (const MailboxAddress & sourceAddress, ACE_Time_Value timeout)
Constructor
References getMessageId(), toString(), and ~MessageTestTimerMessage().
virtual MessageTestTimerMessage::~MessageTestTimerMessage () [virtual]
Virtual Destructor
MessageTestTimerMessage::MessageTestTimerMessage (const MailboxAddress & sourceAddress, ACE_Time_Value timeout, ACE_Time_Value restartInterval)
Constructor
virtual MessageTestTimerMessage::~MessageTestTimerMessage () [virtual]
Virtual Destructor
MessageTestTimerMessage::MessageTestTimerMessage (const MailboxAddress & sourceAddress, ACE_Time_Value timeout, ACE_Time_Value restartInterval)
Constructor
virtual MessageTestTimerMessage::~MessageTestTimerMessage () [virtual]
Virtual Destructor
MessageTestTimerMessage::MessageTestTimerMessage (const MailboxAddress & sourceAddress, ACE_Time_Value timeout, ACE_Time_Value restartInterval)
Constructor
virtual MessageTestTimerMessage::~MessageTestTimerMessage () [virtual]
Virtual Destructor
MessageTestTimerMessage::MessageTestTimerMessage (const MailboxAddress & sourceAddress, ACE_Time_Value timeout, ACE_Time_Value restartInterval)
Constructor
virtual MessageTestTimerMessage::~MessageTestTimerMessage () [virtual]
Virtual Destructor
Member Function Documentation
unsigned short MessageTestTimerMessage::getMessageId () const
Returns the Message Id
Referenced by MessageTestTimerMessage().
unsigned short MessageTestTimerMessage::getMessageId () const
Returns the Message Id
unsigned short MessageTestTimerMessage::getMessageId () const
Returns the Message Id
unsigned short MessageTestTimerMessage::getMessageId () const
Returns the Message Id
unsigned short MessageTestTimerMessage::getMessageId () const
Returns the Message Id
unsigned short MessageTestTimerMessage::getMessageId () const
Returns the Message Id
string MessageTestTimerMessage::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
string MessageTestTimerMessage::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
string MessageTestTimerMessage::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
Referenced by MessageTestTimerMessage().
string MessageTestTimerMessage::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
string MessageTestTimerMessage::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
string MessageTestTimerMessage::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
The documentation for this class was generated from the following files:
discoverytest1/MessageTestTimerMessage.h
discoverytest1/MessageTestTimerMessage.cpp