DbConnection Class Reference
#include <DbConnection.h>
Public Member Functions
virtual ~DbConnection ()
void addUserDefinedIdentifier (string &identifier)
string & getUserDefinedIdentifier ()
void clearUserDefinedIdentifier ()
virtual int checkConnectionHealth ()=0
virtual int executeCommand (string &command)=0
virtual int executeCommand (const char *command)=0
virtual int executeCommandWithParams (const char *command, int numberParams, const char *const *paramValues, const int *paramLengths, const int *isBinary)=0
virtual int beginTransaction ()=0
virtual int rollbackTransaction ()=0
virtual int commitTransaction ()=0
virtual int initializePreparedCommand (const char *statementName, const char *sqlCommand, int numberParams, const DataManagerFieldType *paramTypeArray)=0
virtual int executePreparedCommand (const char *statementName, int numberParams, const char *const *paramValues, const int *paramLengths, const int *isBinary)=0
virtual int closeCommandResult ()=0
virtual int getColumnCount ()=0
virtual string getColumnName (int columnIndex)=0
virtual int getColumnIndex (const char *columnName)=0
virtual int getRowCount ()=0
virtual const char * getStringValueAt (int rowIndex, int columnIndex)=0
virtual short getShortValueAt (int rowIndex, int columnIndex)=0
virtual int getIntValueAt (int rowIndex, int columnIndex)=0
virtual bool getBooleanValueAt (int rowIndex, int columnIndex)=0
virtual const char * getTimestampValueAt (int rowIndex, int columnIndex)=0
virtual bool isValueNULL (int rowIndex, int columnIndex)=0
virtual int getValueLength (int rowIndex, int columnIndex)=0
virtual void shutdown ()=0
string toString ()
Protected Member Functions
DbConnection ()
Additional Inherited Members
Detailed Description
DbConnection provides an abstract base class for deriving all database-specific connection classes from.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
DbConnection::~DbConnection () [virtual]
Virtual Destructor
DbConnection::DbConnection () [protected]
Constructor
Member Function Documentation
void DbConnection::addUserDefinedIdentifier (string & identifier)
Allows the Application Developer to 'tag' a particular connection (through this connection handle) with some user-defined identification data. This data tag will be preserved even if the connection it checked back into the pool (released) and then reserved again. Thus, the developer can identify which connection was used for which previous tasks.
Referenced by DbConnectionHandle::addUserDefinedIdentifier().
virtual int DbConnection::beginTransaction () [pure virtual]
Begin a transaction on this connection. Autocommit is ENABLED for all executed commands UNLESS beginTransaction has been called--that is, beginTransaction disabled autocommit until either rollbackTransaction or commitTransaction is called.
Implemented in PgConnection .
Referenced by DbConnectionHandle::beginTransaction().
virtual int DbConnection::checkConnectionHealth () [pure virtual]
Check the health of the database connection.
Returns
OK if the connection is valid; otherwise ERROR
Implemented in PgConnection .
Referenced by DbConnectionHandle::checkConnectionHealth().
void DbConnection::clearUserDefinedIdentifier ()
Clears the user-defined data and resets the internal string to empty
Referenced by DbConnectionHandle::clearUserDefinedIdentifier().
virtual int DbConnection::closeCommandResult () [pure virtual]
If an outstanding/open command resultSet exists for this connection, then close it.
Implemented in PgConnection .
Referenced by DbConnectionHandle::closeCommandResult().
virtual int DbConnection::commitTransaction () [pure virtual]
Commit the outstanding transaction on this connection
Implemented in PgConnection .
Referenced by DbConnectionHandle::commitTransaction().
virtual int DbConnection::executeCommand (string & command) [pure virtual]
Execute an SQL command to the database using this connection. This command can be a QUERY, UPDATE, INSERT, or DELETE operation.
Returns
OK if the command was executed successfully; otherwise ERROR
Implemented in PgConnection .
Referenced by DbConnectionHandle::executeCommand().
virtual int DbConnection::executeCommand (const char * command) [pure virtual]
Execute an SQL command to the database using this connection. This command can be a QUERY, UPDATE, INSERT, or DELETE operation. (To work with ostringstream)
Returns
OK if the command was executed successfully; otherwise ERROR
Implemented in PgConnection .
virtual int DbConnection::executeCommandWithParams (const char * command, int numberParams, const char *const * paramValues, const int * paramLengths, const int * isBinary) [pure virtual]
Execute an SQL command to the database using this connection. This command can be a QUERY, UPDATE, INSERT or DELETE operation.
Parameters
numberParams number of passed in parameters in the char* array
paramValues specifies the actual values of the parameters (char* array)
paramLengths specifies the actual data lengths of binary-format parameters. It is ignored for null parameters and text-format parameters. The array pointer may be null when there are no binary parameters.
isBinary array for each param value to determine if the value is binary or textual (TRUE for binary / FALSE for text). The array pointer may be null when there are no binary parameters.
Returns
OK if the command was executed successfully; otherwise ERROR
Implemented in PgConnection .
Referenced by DbConnectionHandle::executeCommandWithParams().
virtual int DbConnection::executePreparedCommand (const char * statementName, int numberParams, const char *const * paramValues, const int * paramLengths, const int * isBinary) [pure virtual]
Execute an SQL prepared statement command to the database using this connection. This command can be a QUERY, UPDATE, INSERT, or DELETE operation.
Parameters
statementName string name assigned to the statement when initializePreparedCommand is called.
numberParams number of passed in parameters in the char* array
paramValues specifies the actual values of the parameters (char* array)
paramLengths specifies the actual data lengths of binary-format parameters. It is ignored for null parameters and text-format parameters. The array pointer may be null when there are no binary parameters.
isBinary array for each param value to determine if the value is binary or textual (TRUE for binary / FALSE for text). The array pointer may be null when there are no binary parameters.
Returns
OK if the command was successfully executed; otherwise ERROR
Implemented in PgConnection .
Referenced by DbConnectionHandle::executePreparedCommand().
virtual bool DbConnection::getBooleanValueAt (int rowIndex, int columnIndex) [pure virtual]
Return the value at the specified column/row location in the current commandResult. The value returned will be a boolean type. NOTE: Use of this method requires that the developer be aware of the of the schema and result field type.
Implemented in PgConnection .
Referenced by DbConnectionHandle::getBooleanValueAt().
virtual int DbConnection::getColumnCount () [pure virtual]
Return the number of columns in the current commandResult structure
Implemented in PgConnection .
Referenced by DbConnectionHandle::getColumnCount().
virtual int DbConnection::getColumnIndex (const char * columnName) [pure virtual]
Return the column index based on the specified column name
Implemented in PgConnection .
Referenced by DbConnectionHandle::getColumnIndex().
virtual string DbConnection::getColumnName (int columnIndex) [pure virtual]
Return the specified column header name in the current commandResult
Implemented in PgConnection .
Referenced by DbConnectionHandle::getColumnName().
virtual int DbConnection::getIntValueAt (int rowIndex, int columnIndex) [pure virtual]
Return the value at the specified column/row location in the current commandResult. The value returned will be a 4-byte integer type. NOTE: Use of this method requires that the developer be aware of the of the schema and result field type.
Implemented in PgConnection .
Referenced by DbConnectionHandle::getIntValueAt().
virtual int DbConnection::getRowCount () [pure virtual]
Return the number of rows in the current commandResult
Implemented in PgConnection .
Referenced by DbConnectionHandle::getRowCount().
virtual short DbConnection::getShortValueAt (int rowIndex, int columnIndex) [pure virtual]
Return the value at the specified column/row location in the current commandResult. The value returned will be a 2-byte short type. NOTE: Use of this method requires that the developer be aware of the of the schema and result field type.
Implemented in PgConnection .
Referenced by DbConnectionHandle::getShortValueAt().
virtual const char* DbConnection::getStringValueAt (int rowIndex, int columnIndex) [pure virtual]
Return the value at the specified column/row location in the current commandResult. The value is returned as a string. NOTE: Use of this method requires that the developer be aware of the of the schema and result field type.
Implemented in PgConnection .
Referenced by DbConnectionHandle::getStringValueAt().
virtual const char* DbConnection::getTimestampValueAt (int rowIndex, int columnIndex) [pure virtual]
Return the value at the specified column/row location in the current commandResult. The value returned will be a string. NOTE: Use of this method requires that the developer be aware of the of the schema and result field type.
Implemented in PgConnection .
Referenced by DbConnectionHandle::getTimestampValueAt().
string & DbConnection::getUserDefinedIdentifier ()
Returns the user-defined identifier data
Returns
empty string if no user-defined data has been previously set
Referenced by DbConnectionHandle::getUserDefinedIdentifier().
virtual int DbConnection::getValueLength (int rowIndex, int columnIndex) [pure virtual]
Returns the actual length of a field value in bytes
Implemented in PgConnection .
Referenced by DbConnectionHandle::getValueLength().
virtual int DbConnection::initializePreparedCommand (const char * statementName, const char * sqlCommand, int numberParams, const DataManagerFieldType * paramTypeArray) [pure virtual]
Setup for a prepared statement command on this connection
Parameters
statementName string name arbitrarily assigned to the statement
sqlCommand QUERY, UPDATE, INSERT, or DELETE sql operation.
numberParams number of passed in parameters in the char* array
paramTypeArray array of field types because the database cannot infer the field type formatting without it.
Returns
OK if the preparation was successful; otherwise ERROR
Implemented in PgConnection .
Referenced by DbConnectionHandle::initializePreparedCommand().
virtual bool DbConnection::isValueNULL (int rowIndex, int columnIndex) [pure virtual]
Returns true if the field Value is NULL
Implemented in PgConnection .
Referenced by DbConnectionHandle::isValueNULL().
virtual int DbConnection::rollbackTransaction () [pure virtual]
Rollback a transaction on this connection
Implemented in PgConnection .
Referenced by DbConnectionHandle::rollbackTransaction().
virtual void DbConnection::shutdown () [pure virtual]
Close the socket connection to the database server
Implemented in PgConnection .
Referenced by DbConnectionHandle::shutdown().
string DbConnection::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
The documentation for this class was generated from the following files:
DbConnection.h
DbConnection.cpp