SyncObjectPool Class Reference
#include <SyncObjectPool.h>
Public Member Functions
SyncObjectPool (int objectPoolID, int initialCapacity, double thresholdPercentage, int capacityIncrement, const char *objectType, long objectInitParam, OPM_INIT_PTR bootStrapMethod, OPMGrowthModeType growthMode)
virtual ~SyncObjectPool ()
OPMBase * reserve (bool blockWaitingForAccess=true)
bool release (OPMBase *object, char *callingFileName, int callingLineNumb)
bool isEmpty ()
bool containsObject (OPMBase *object)
void setCapacityIncrement (int capacityIncrement)
void printUsageSummary ()
Additional Inherited Members
Detailed Description
SyncObjectPool provides a wrapper class for making Object Pool thread safe. It is the responsibility of the developer to determine if the Object Pool will be accessed from multiple threads.
Object pool contains methods for reserving and releasing pooled objects and for manipulating the capacity increments of the data structures (pool supports both growing and shrinking based on increment size), computing the count of free objects, setting the threshold and increment values, and performing cleanup.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
SyncObjectPool::SyncObjectPool (int objectPoolID, int initialCapacity, double thresholdPercentage, int capacityIncrement, const char * objectType, long objectInitParam, OPM_INIT_PTR bootStrapMethod, OPMGrowthModeType growthMode)
Constructor initializes the pool to a configurable size and sets the individual object's initializer to be stored in the Pool.
Parameters
objectPoolID Object PoolID that identifies this object pool in the OPM
initialCapacity Starting size of the pool in objects
thresholdPercentage Percentage of current capacity to trigger automatic growth.
capacityIncrement Number of objects to add to the current size when increasing capacity
objectType const char* describing the class object stored in this pool
objectInitParam - Long parameter or pointer to initialization data needed by the object or 0(NULL) if not needed (passed to OPMBase::initialize).
bootStrapMethod pointer to a function or method (OPMBase::initialize) that will create the object and return a pointer to it
growthMode Either NO_GROWTH, GROWTH_ALLOWED, or GROW_AND_SHRINK
SyncObjectPool::~SyncObjectPool () [virtual]
Virtual Destructor
Member Function Documentation
bool SyncObjectPool::containsObject (OPMBase * object) [virtual]
Method to check if a specified object is in the Free Linked List or the Used Linked List. This method traverses both lists looking for pointer equality.
Returns
true if the Object is in the list
 false if the Object is NOT in the list
Reimplemented from ObjectPool .
References ObjectPool::containsObject().
bool SyncObjectPool::isEmpty () [virtual]
Method to test if this pool is empty
Returns
true if the Free List is empty
 false if the Free List is NOT empty
Reimplemented from ObjectPool .
References ObjectPool::isEmpty().
bool SyncObjectPool::release (OPMBase * object, char * callingFileName, int callingLineNumb)
Release an object back into the pool after using it. This makes the object available again for use in other tasks. This method automatically monitors the number of in-use objects and will shrink the pool when the number drops below the previous increment's threshold value.
Parameters
object Object to release back into the pool.
callingFileName - Specifies the source file from which the object is being released (this will be printed as a DEBUG log using a MACRO)
callingLineNumb - Specifies the source line from which the object is being released (this will be printed as a DEBUG log using a MACRO)
Returns
true if the specified Object was successfully released
 false if the Object Reference was not found in the USED data structure (could be wrong pool, is already released, or was not created via OPM)
References ObjectPool::release().
OPMBase * SyncObjectPool::reserve (bool blockWaitingForAccess = true) [virtual]
Reserve an object for use, thus making it unavailable for other tasks. This method automatically monitors the number of in-use objects and will grow the pool when the number exceeds the threshold. If the object pool is specified to be non-resizable, then an error will be displayed and NULL returned if no available objects exist.
Parameters
blockWaitingForAccess If true, this method will block until an object becomes available if they are all in use. Otherwise, if false, this method will return NULL if all objects are in use.
Reimplemented from ObjectPool .
References ObjectPool::reserve().
void SyncObjectPool::setCapacityIncrement (int capacityIncrement) [virtual]
Method to set or reset the capacity increment of this Object Pool
Parameters
capacityIncrement The new capacity increment value
Reimplemented from ObjectPool .
References ObjectPool::capacityIncrement_.
The documentation for this class was generated from the following files:
SyncObjectPool.h
SyncObjectPool.cpp