GroupMailboxProxy Class Reference
Public Member Functions
virtual int post (MessageBase *messagePtr, const ACE_Time_Value *timeout=&ACE_Time_Value::zero)
virtual int activate (MailboxOwnerHandle *mailboxOwnerHandle)
virtual int deactivate (MailboxOwnerHandle *mailboxOwnerHandle)
virtual const ACE_Time_Value & getPostDefaultTimeout ()
virtual int getDebugValue ()
virtual void setDebugValue (int debugValue)
MailboxAddress & getMailboxAddress ()
string toString ()
Static Public Member Functions
static MailboxOwnerHandle * createMailbox (const MailboxAddress &groupAddress, unsigned int multicastLoopbackEnabled=TRUE, unsigned int multicastTTL=1)
Protected Member Functions
GroupMailboxProxy (const MailboxAddress &groupAddress, unsigned int multicastLoopbackEnabled_, unsigned int multicastTTL_)
virtual ~GroupMailboxProxy ()
Additional Inherited Members
Constructor & Destructor Documentation
GroupMailboxProxy::GroupMailboxProxy (const MailboxAddress & groupAddress, unsigned int multicastLoopbackEnabled_, unsigned int multicastTTL_) [protected]
Constructor
References OPM::createPool(), GroupMailboxProxy(), MessageBuffer::initialize(), and MailboxBase::isProxy_.
Referenced by GroupMailboxProxy().
GroupMailboxProxy::~GroupMailboxProxy () [protected], [virtual]
Virtual Destructor. Protected since this is a reference counted object.
References MailboxBase::isShuttingDown_.
Member Function Documentation
int GroupMailboxProxy::activate (MailboxOwnerHandle * mailboxOwnerHandle) [virtual]
Activate the mailbox. For security, one must possess an Owner Handle to activate the mailbox and register it with the Lookup Service.
Reimplemented from MailboxBase .
References MailboxAddress::inetAddress, MailboxBase::isActive(), MailboxLookupService::registerMailbox(), and MailboxBase::setActive().
MailboxOwnerHandle * GroupMailboxProxy::createMailbox (const MailboxAddress & groupAddress, unsigned int multicastLoopbackEnabled = TRUE, unsigned int multicastTTL = 1) [static]
Allows applications to create a mailbox and get a handle to it.
Since we do not want applications to have direct access to a mailbox object this method is provided. Applications that create mailboxes use this method to get a handle to their mailbox rather than have direct access. The handle returned is a owner handle which has all the privileges of the actual mailbox (getMessage/post etc). This method creates the mailbox, activates it (which in turn registers it with the lookup service) and then creates an owner handle, acquires it and then returns that handle. Both the mailbox and the returned handle are created on the heap.
Parameters
groupAddress source mailbox address that this mailbox will have
multicastLoopbackEnabled set to TRUE to enable multicast loopback
multicastTTL If we experience problems with Multicast packets getting from one network to another, we need to probably change the TTL. By default, it is set to 1 to allow for only 1 hop. (within the same subnet, routers will not forward). Also, setting to 0 will restrict to within the same host.
Returns
pointer to a mailbox owner handle
Referenced by MailboxLookupService::find(), and DiscoveryManager::processMailbox().
int GroupMailboxProxy::deactivate (MailboxOwnerHandle * mailboxOwnerHandle) [virtual]
Deactivate the mailbox. For security, one must possess an Owner Handle to deactivate the mailbox and deregister it with the Lookup Service.
Reimplemented from MailboxBase .
References MailboxLookupService::deregisterMailbox(), MailboxAddress::inetAddress, MailboxBase::isActive(), and MailboxBase::setActive().
int GroupMailboxProxy::getDebugValue () [virtual]
Return the debug flag
Implements MailboxBase .
References MailboxBase::debugValue_.
MailboxAddress & GroupMailboxProxy::getMailboxAddress () [virtual]
Return the mailbox group address
Implements MailboxBase .
const ACE_Time_Value & GroupMailboxProxy::getPostDefaultTimeout () [virtual]
Return the appropriate default timeout for the post()
Implements MailboxBase .
int GroupMailboxProxy::post (MessageBase * messagePtr, const ACE_Time_Value * timeout = &ACE_Time_Value::zero) [virtual]
Post a message to the group mailbox. Subclass implementations should examine the `active_` state. Upon initial failure of the post, this proxy mailbox will close and re-open the socket and attempt to post the message again automatically. If the the repost fails, then ERROR will be returned, and it becomes the responsibility of the application to retry the message after deleting the mailbox handle and performing MailboxLookupService::find (which may return a redundant mate's handle); or, the application can give up and delete the message off of the heap.
Returns
ERROR upon failure; OK otherwise.
Implements MailboxBase .
References MailboxBase::debugValue_, MessageBase::deleteMessage(), MessageBase::getMessageId(), MessageBase::getPriority(), MessageBase::getSourceAddress(), MailboxBase::incrementSentCount(), MailboxAddress::inetAddress, MailboxBase::isActive(), MessageBase::serialize(), MessageBase::toString(), and MailboxAddress::toString().
void GroupMailboxProxy::setDebugValue (int debugValue) [virtual]
Set the debug flag
Implements MailboxBase .
References MailboxBase::debugValue_.
string GroupMailboxProxy::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
The documentation for this class was generated from the following files:
GroupMailboxProxy.h
GroupMailboxProxy.cpp