MessageHandlerList Class Reference
Public Member Functions
MessageHandlerList ()
virtual ~MessageHandlerList ()
bool add (unsigned short messageId, const MessageHandler &handler)
void remove (unsigned short messageId)
const MessageHandler & find (unsigned short messageId)
void setDefault (MessageHandler &defaultHandler)
void restoreDefault ()
void listAllMessageHandlers ()
string toString ()
Constructor & Destructor Documentation
MessageHandlerList::MessageHandlerList ()
Constructor
MessageHandlerList::~MessageHandlerList () [virtual]
Virtual Destructor
Member Function Documentation
bool MessageHandlerList::add (unsigned short messageId, const MessageHandler & handler)
Perform the mapping between message Id and handler function
Returns
true if the mapping was successful
Referenced by DiscoveryManager::initialize(), FaultManager::processMailbox(), and ResourceMonitor::toString().
const MessageHandler & MessageHandlerList::find (unsigned short messageId)
Return a handler for a given message Id.
Returns
default handler if message Id could not be found
Referenced by MailboxProcessor::processMailbox().
void MessageHandlerList::listAllMessageHandlers ()
List all mappings between message Id and handler functions
void MessageHandlerList::remove (unsigned short messageId)
Remove the mapping between message Id and handler function
void MessageHandlerList::restoreDefault ()
Restore the default message handler
void MessageHandlerList::setDefault (MessageHandler & defaultHandler)
Change the default handler
string MessageHandlerList::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
The documentation for this class was generated from the following files:
MessageHandlerList.h
MessageHandlerList.cpp