MessageBuffer Class Reference
Public Member Functions
MessageBuffer (unsigned short bufferSize=MAX_MESSAGE_LENGTH, bool performNetworkConversion=true)
MessageBuffer (unsigned char *bufferPtr, unsigned short bufferSize, bool performNetworkConversion=true)
virtual ~MessageBuffer ()
void clean ()
unsigned char * getBuffer ()
unsigned int getBufferLength ()
unsigned int getMaxBufferLength ()
void setInsertPosition (unsigned short nBytes)
void setNetworkConversion (bool performNetworkConversion)
void clearBuffer ()
void assignBuffer (unsigned char *bufferPtr, unsigned short bufferSize)
void assignEmptyBuffer (unsigned char *bufferPtr, unsigned short maxBufferSize)
MessageBuffer & operator<< (int intValue)
MessageBuffer & operator<< (unsigned char charValue)
MessageBuffer & operator<< (unsigned short shortValue)
MessageBuffer & operator<< (unsigned int uintValue)
MessageBuffer & operator<< (string &stringValue)
MessageBuffer & operator<< (bool boolValue)
MessageBuffer & operator<< (MailboxAddress &mailboxValue)
MessageBuffer & operator>> (int &intValue)
MessageBuffer & operator>> (unsigned char &charValue)
MessageBuffer & operator>> (unsigned short &shortValue)
MessageBuffer & operator>> (unsigned int &uintValue)
MessageBuffer & operator>> (string &stringValue)
MessageBuffer & operator>> (bool &boolValue)
MessageBuffer & operator>> (MailboxAddress &mailboxValue)
bool areContentsProcessed ()
string toString ()
Static Public Member Functions
static OPMBase * initialize (int initializer)
Additional Inherited Members
Constructor & Destructor Documentation
MessageBuffer::MessageBuffer (unsigned short bufferSize = MAX_MESSAGE_LENGTH, bool performNetworkConversion = true)
Constructor
References MessageBuffer().
Referenced by MessageBuffer().
MessageBuffer::MessageBuffer (unsigned char * bufferPtr, unsigned short bufferSize, bool performNetworkConversion = true)
Constructor
References MessageBuffer().
MessageBuffer::~MessageBuffer () [virtual]
Virtual Destructor
Member Function Documentation
bool MessageBuffer::areContentsProcessed ()
Method to return whether or not this Message Buffer has been completely deserialized based on the position of the deserializeFromPtr
Referenced by DistributedMailbox::createMailbox(), and GroupMailbox::createMailbox().
void MessageBuffer::assignBuffer (unsigned char * bufferPtr, unsigned short bufferSize)
Method to assign the contents of the buffer
Referenced by LocalSMMailbox::getMailboxAddress().
void MessageBuffer::assignEmptyBuffer (unsigned char * bufferPtr, unsigned short maxBufferSize)
Method to assign empty contents to the buffer
void MessageBuffer::clean () [virtual]
OPMBase clean method gets called when the object gets released back into its pool
Implements OPMBase .
References clearBuffer().
void MessageBuffer::clearBuffer ()
Method to clear out the buffer
Referenced by clean(), DistributedMailbox::createMailbox(), GroupMailbox::createMailbox(), and LocalSMMailbox::getMailboxAddress().
unsigned char * MessageBuffer::getBuffer ()
Method to return the encapsulated buffer
Referenced by DistributedMailbox::createMailbox(), and GroupMailbox::createMailbox().
unsigned int MessageBuffer::getBufferLength ()
Return the size of the encapsulated buffer contents
unsigned int MessageBuffer::getMaxBufferLength ()
Return the max buffer length
OPMBase * MessageBuffer::initialize (int initializer) [static]
OPMBase static initializer method for bootstrapping the objects
Parameters
initializer Here the initializer will be the message buffer size to create. This assumes that we will have an OPM object pool for each size of Message Buffer that we need.
Referenced by DistributedMailboxProxy::DistributedMailboxProxy(), GroupMailboxProxy::GroupMailboxProxy(), and LocalSMMailboxProxy::LocalSMMailboxProxy().
MessageBuffer & MessageBuffer::operator<< (int intValue)
Overloaded insertion operators for the buffer
References MailboxAddress::inetAddress, MailboxAddress::locationType, MailboxAddress::mailboxName, MailboxAddress::mailboxType, MailboxAddress::neid, MailboxAddress::redundantRole, MailboxAddress::shelfNumber, and MailboxAddress::slotNumber.
MessageBuffer & MessageBuffer::operator>> (int & intValue)
Overloaded extraction operators for the buffer
References MailboxAddress::inetAddress, MailboxAddress::locationType, MailboxAddress::mailboxName, MailboxAddress::mailboxType, MailboxAddress::neid, MailboxAddress::redundantRole, MailboxAddress::shelfNumber, and MailboxAddress::slotNumber.
void MessageBuffer::setInsertPosition (unsigned short nBytes)
Method to control the insertion position into the buffer
Referenced by DistributedMailbox::createMailbox(), GroupMailbox::createMailbox(), and LocalSMMailbox::getMailboxAddress().
void MessageBuffer::setNetworkConversion (bool performNetworkConversion)
Method to set the Network Conversion mode.
Parameters
performNetworkConversion true is network bit conversion should be performed; otherwise false (for shared memory operations)
string MessageBuffer::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
The documentation for this class was generated from the following files:
MessageBuffer.h
MessageBuffer.cpp