MessageTestRemote Class Reference
#include <MessageTestRemote.h>
Public Member Functions
MessageTestRemote (string &localMailboxName, int localPortNumber)
virtual ~MessageTestRemote ()
void processMailbox ()
MailboxOwnerHandle * getOwnerHandle ()
MailboxAddress & getLocalMailboxAddress ()
string toString ()
MessageTestRemote ()
virtual ~MessageTestRemote ()
void processMailbox ()
MailboxOwnerHandle * getOwnerHandle ()
string toString ()
MessageTestRemote ()
virtual ~MessageTestRemote ()
void processMailbox ()
MailboxOwnerHandle * getOwnerHandle ()
string toString ()
MessageTestRemote ()
virtual ~MessageTestRemote ()
void processMailbox ()
MailboxOwnerHandle * getOwnerHandle ()
string toString ()
Static Public Member Functions
static MessageTestRemote * getInstance ()
static MessageTestRemote * getInstance ()
static MessageTestRemote * getInstance ()
static MessageTestRemote * getInstance ()
Detailed Description
MessageTestRemote is a collection of unit test procedures for the MsgMgr framework. This class deals exclusively with Distributed Mailboxes when using the Discovery functionality.
Author
Stephen Horton
Revision
1
MessageTestRemote is a collection of unit test procedures for the MsgMgr framework. This class deals exclusively with Distributed Mailboxes (in this case multithreaded send / recv)
Author
Stephen Horton
Revision
1
MessageTestRemote is a collection of unit test procedures for the MsgMgr framework. This class deals exclusively with Distributed Mailboxes.
Author
Stephen Horton
Revision
1
MessageTestRemote is a collection of unit test procedures for the MsgMgr framework. This class deals exclusively with Local Shared Memory Mailboxes.
Author
Stephen Horton
Revision
1
Constructor & Destructor Documentation
MessageTestRemote::MessageTestRemote (string & localMailboxName, int localPortNumber)
Constructor
MessageTestRemote::~MessageTestRemote () [virtual]
Virtual Destructor
Referenced by MessageTestRemote().
MessageTestRemote::MessageTestRemote ()
Constructor
References MessageTestRemoteMessage::deserialize(), getInstance(), getOwnerHandle(), processMailbox(), MessageTest1Message::toString(), toString(), MessageTestRemoteMessage::toString(), and ~MessageTestRemote().
Referenced by toString().
virtual MessageTestRemote::~MessageTestRemote () [virtual]
Virtual Destructor
MessageTestRemote::MessageTestRemote ()
Constructor
virtual MessageTestRemote::~MessageTestRemote () [virtual]
Virtual Destructor
MessageTestRemote::MessageTestRemote ()
Constructor
virtual MessageTestRemote::~MessageTestRemote () [virtual]
Virtual Destructor
Member Function Documentation
static MessageTestRemote* MessageTestRemote::getInstance () [static]
Returns static singleton instance
static MessageTestRemote* MessageTestRemote::getInstance () [static]
Returns static singleton instance
static MessageTestRemote* MessageTestRemote::getInstance () [static]
Returns static singleton instance
MessageTestRemote * MessageTestRemote::getInstance () [static]
Returns static singleton instance
Referenced by MessageTestRemote(), and toString().
MailboxAddress & MessageTestRemote::getLocalMailboxAddress ()
Returns a reference to the local Mailbox Address
References MessageTestRemoteMessage::deserialize().
Referenced by toString().
MailboxOwnerHandle* MessageTestRemote::getOwnerHandle ()
Returns pointer to the owner handle of the main mailbox
MailboxOwnerHandle* MessageTestRemote::getOwnerHandle ()
Returns pointer to the owner handle of the main mailbox
MailboxOwnerHandle* MessageTestRemote::getOwnerHandle ()
Returns pointer to the owner handle of the main mailbox
MailboxOwnerHandle * MessageTestRemote::getOwnerHandle ()
Returns pointer to the owner handle of the main mailbox
Referenced by MessageTestRemote(), and toString().
void MessageTestRemote::processMailbox ()
Start the mailbox processing loop
void MessageTestRemote::processMailbox ()
Start the mailbox processing loop
void MessageTestRemote::processMailbox ()
Start the mailbox processing loop
void MessageTestRemote::processMailbox ()
Start the mailbox processing loop
References MessageTest1Message::toString(), and MessageTestRemoteMessage::toString().
Referenced by MessageTestRemote(), and toString().
string MessageTestRemote::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
string MessageTestRemote::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
string MessageTestRemote::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
string MessageTestRemote::toString ()
String'ized debugging method
Returns
string representation of the contents of this object
References getInstance(), getLocalMailboxAddress(), getOwnerHandle(), MessageTestRemote(), and processMailbox().
Referenced by MessageTestRemote().
The documentation for this class was generated from the following files:
discoverytest1/MessageTestRemote.h
discoverytest1/MessageTestRemote.cpp