ems.idls.session.Session_IOperations Interface Reference
Public Member Functions
ems.idls.session.Session_I associatedSession ()
void ping ()
void endSession ()
Detailed Description
ems/idls/session/Session_IOperations.java . Generated by the IDL-to-Java compiler (portable), version `3.2` from session.idl Tuesday, January 15, 2015 5:02:24 PM CST
The Session_I interface provides capabilities to manage the client-server connection. Its main purpose is to enable either a client or server to detect the loss of communication with the associated party.
For a single communication session between an NMS and an EMS, there are two Session_I objects. One is maintained on the NMS; the other one is maintained on the EMS. The Session_I object maintained on the EMS is actually an EmsSession_I, while the Session_I object maintained on the NMS is actually an NmsSession_I (both inherit from Session_I).
Each Session_I object is responsible to `ping` the other Session_I object periodically to detect communication failures. Exactly when this is done is up to the implementation.
When a Session_I object detects a communication failure, or when the endSession operation is called on it, all resources allocated with that communication session must be freed and the Session_I object must be deleted.
Member Function Documentation
ems.idls.session.Session_I ems.idls.session.Session_IOperations.associatedSession ()
This attribute contains a reference to the Session_I on the other side (NMS/EMS) to which the object is associated. This attribute can be checked to make sure the NmsSession_I/EmsSession_I association is still valid (in particular in case of communication failures).
Implemented in ems.guiclient.Session_IImpl , and ems.idls.session._Session_IStub .
Referenced by ems.idls.session.Session_IPOA._invoke().
void ems.idls.session.Session_IOperations.endSession ()
Allows for a controlled disconnect between parties. All resources allocated for the session are deleted by operation.
Implemented in ems.idls.session._Session_IStub , and ems.guiclient.Session_IImpl .
Referenced by ems.idls.session.Session_IPOA._invoke().
void ems.idls.session.Session_IOperations.ping ()
Allows for the detection of loss of communication. It is implementation specific to differenciate intermittent problems from loss of connection.
Implemented in ems.guiclient.Session_IImpl , and ems.idls.session._Session_IStub .
Referenced by ems.idls.session.Session_IPOA._invoke().
The documentation for this interface was generated from the following file:
Session_IOperations.java