ems.idls.platformConfig.platformConfig_IOperations Interface Reference
Public Member Functions
void getLogLevels (ems.idls.platformConfig.platformConfigLogLevelsHolder logLevels)
void setLogLevel (ems.idls.platformConfig.platformConfigLogLevel logLevel)
void setLogLevels (ems.idls.platformConfig.platformConfigLogLevel[] logLevels)
Detailed Description
ems/idls/platformConfig/platformConfig_IOperations.java . Generated by the IDL-to-Java compiler (portable), version `3.2` from platformConfig.idl Tuesday, January 15, 2015 5:02:24 PM CST Command/Method interface
Member Function Documentation
void ems.idls.platformConfig.platformConfig_IOperations.getLogLevels (ems.idls.platformConfig.platformConfigLogLevelsHolder logLevels)
Retrieve all of the subsystem log levels
Implemented in ems.idls.platformConfig._platformConfig_IStub .
Referenced by ems.idls.platformConfig.platformConfig_IPOA._invoke().
void ems.idls.platformConfig.platformConfig_IOperations.setLogLevel (ems.idls.platformConfig.platformConfigLogLevel logLevel)
Set a specified log level
Implemented in ems.idls.platformConfig._platformConfig_IStub .
Referenced by ems.idls.platformConfig.platformConfig_IPOA._invoke().
void ems.idls.platformConfig.platformConfig_IOperations.setLogLevels (ems.idls.platformConfig.platformConfigLogLevel[] logLevels)
Set all of the log levels
Implemented in ems.idls.platformConfig._platformConfig_IStub .
Referenced by ems.idls.platformConfig.platformConfig_IPOA._invoke().
The documentation for this interface was generated from the following file:
platformConfig_IOperations.java