Source = \
	ObjectBase.cpp \
	ObjectPool.cpp \
	OPM.cpp \
	OPMBase.cpp \
	OPMLinkedList.cpp \
	SyncObjectPool.cpp \

IncludeDirs = \
        /usr/include \
        ${COMPILER_VERSION} \
        ${ACE_ROOT} \

LibraryDirs = \
        /usr/lib \
        ${ACE_ROOT}/ace \

Libraries = \
        ACE \
	platformlogger \

Main      = 

include $(DEV_ROOT)/make/Makefile
