Packages = \
	platform/utilities \
	platform/logger \
	platform/threadmgr \
	platform/opm \
	platform/datamgr \
	platform/msgmgr \
	platform/messages \
	platform/faultmgr \
	platform/processmgr \
	platform/resourcemon \

IncludeDirs = \
	/usr/include \
	${COMPILER_VERSION} \
	${ACE_ROOT} \
	
LibraryDirs = \
	/usr/lib \
        ${ACE_ROOT}/ace \

Libraries = \
	ACE \


include $(DEV_ROOT)/make/Makefile
