Packages = \
	unittest/test1 \
	unittest/test2 \
	unittest/test3 \
	unittest/loggertest \
	unittest/loggertest2 \
	unittest/cleanloggerSM \
	unittest/datamgrtest \
	unittest/opmtest \
	unittest/msgmgrtest1 \
	unittest/msgmgrtest2 \
	unittest/msgmgrtest3 \
	unittest/msgmgrtest2sm \
	unittest/msgmgrtest3sm \
	unittest/msgmgrgrouptest1 \
	unittest/msgmgrgrouptest2 \
	unittest/msgmgr_mt_recv \
	unittest/msgmgr_mt_send \
	unittest/discoverytest1 \
	unittest/threadtest \
	unittest/versionid \

IncludeDirs = \
	/usr/include \
	${COMPILER_VERSION} \
	${ACE_ROOT} \
	
LibraryDirs = \
	/usr/lib \
        ${ACE_ROOT}/ace \

Libraries = \
	ACE \

include $(DEV_ROOT)/make/Makefile
